import { test, expect } from '@playwright/test';
test('appearance follows system changes, persists per-account settings, and leaves media unsaturated', async ({ page }) => {
  await page.route(url => url.pathname === '/lib/matrix.ts', route => route.fulfill({ contentType: 'text/javascript', body: `const records={};const listeners=new Set();export const getMatrixClient=()=>client;export const onMatrixUpdate=()=>()=>{};export const client={getAccountData:key=>records[key]?{getContent:()=>records[key]}:undefined,getAccountDataFromServer:async key=>records[key],setAccountData:async(key,value)=>{records[key]=value;listeners.forEach(fn=>fn({getType:()=>key}));},on:(_event,fn)=>listeners.add(fn),off:(_event,fn)=>listeners.delete(fn)};` }));
  await page.route('**/appearance-component-test', route => route.fulfill({ contentType: 'text/html', body: `<!doctype html><html><head><style>:root{--primary:#866037;--accent:#ede0c7;--accent-foreground:#76522e;--ring:#b78a56;--sidebar-accent:#4b4c47;--sidebar-accent-foreground:#f0d7a7;--sidebar-primary:#d7b880;--mint-surface:#ebe8d8;--mint-text:#62684e}</style></head><body><div class='channel-overview'>Members</div><img id='photo' alt='Unmodified media' src='data:image/gif;base64,R0lGODlhAQABAAAAACw='><script type='module'>const appearance=await import('/lib/appearance.ts');const {client}=await import('/lib/matrix.ts');window.appearance=appearance;window.client=client;appearance.initializeAppearance(client);window.fixtureReady=true;</script></body></html>` }));
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' }); await page.goto('/appearance-component-test'); await page.waitForFunction(() => (window as any).fixtureReady);
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark'); await expect(page.locator('html')).toHaveAttribute('data-reduce-motion', 'true');
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'no-preference' }); await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.evaluate(() => (window as any).appearance.saveAppearance({ theme: 'dark', saturation: 0, memberList: false, chatScale: 1.3 }, (window as any).client));
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark'); await expect(page.locator('html')).toHaveAttribute('data-member-list', 'hidden');
  expect(await page.locator('html').evaluate(e => (e as HTMLElement).style.getPropertyValue('--primary'))).toMatch(/^rgba\((\d+), \1, \1, 1\)$/);
  expect(await page.locator('#photo').evaluate(e => getComputedStyle(e).filter)).toBe('none');
  await page.evaluate(() => { const w = window as any; w.appearance.resetAppearance(); w.appearance.initializeAppearance(w.client); });
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark'); expect(await page.locator('html').evaluate(e => (e as HTMLElement).style.getPropertyValue('--tavern-chat-scale'))).toBe('1.3');
});
