import { test, expect } from '@playwright/test';
test('bulk moderation requires exact typed confirmation and reports partial redaction results', async ({ page }) => {
  await page.route(url => url.pathname === '/lib/matrix.ts', route => route.fulfill({ contentType: 'text/javascript', body: 'export const getMatrixClient=()=>window.fixtureClient;export const onMatrixUpdate=()=>()=>{};' }));
  await page.route('**/bulk-moderation-test', route => route.fulfill({ contentType: 'text/html', body: `<!doctype html><html><body><div id="root"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;(await import('/tests/browser/fixtures/bulk-moderation.tsx')).mountFixture();</script></body></html>` }));
  await page.goto('/bulk-moderation-test'); await page.getByText('Bulk message moderation', { exact: true }).click(); await page.getByRole('checkbox').nth(0).check(); await page.getByRole('checkbox').nth(1).check(); await page.getByRole('button', { name: 'Review 2 selected messages…' }).click();
  const submit = page.getByRole('button', { name: 'Redact selected messages' }); await expect(submit).toBeDisabled(); await page.getByLabel('Moderation reason').fill('Repeated spam'); await page.getByLabel('Type DELETE 2 to confirm').fill('DELETE 1'); await expect(submit).toBeDisabled(); await page.getByLabel('Type DELETE 2 to confirm').fill('DELETE 2'); await submit.click();
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('region', { name: 'Bulk moderation results' })).toContainText('1 redacted · 1 unconfirmed or rejected'); await expect(page.getByRole('region', { name: 'Bulk moderation results' })).toContainText('The homeserver could not confirm this redaction.');
  expect(await page.evaluate(() => (window as any).redactions)).toEqual([{ id: '$good', reason: 'Repeated spam' }]); await expect(page.getByRole('button', { name: 'Review 1 selected messages…' })).toBeEnabled();
});
