import { expect, test } from '@playwright/test';
test('unread keys wrap, reference restores focus, alternate binding persists, and modal navigation is blocked', async ({ page }) => {
  await page.route('**/keyboard-test', route => route.fulfill({ contentType: 'text/html', body: `<!doctype html><html><body><div id="root"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;(await import('/tests/browser/fixtures/keyboard-shortcuts.tsx')).mountFixture();</script></body></html>` }));
  await page.goto('/keyboard-test'); await page.getByRole('textbox', { name: 'Composer' }).focus(); await page.keyboard.press('Alt+ArrowDown'); await expect(page.getByRole('status', { includeHidden: true })).toHaveText('Current: d'); await page.keyboard.press('Alt+ArrowDown'); await expect(page.getByRole('status', { includeHidden: true })).toHaveText('Current: a');
  await page.keyboard.press('Control+/'); await expect(page.getByRole('dialog', { name: 'Keyboard shortcuts' })).toBeVisible();
  await page.keyboard.press('Alt+ArrowDown'); await expect(page.getByRole('status', { includeHidden: true })).toHaveText('Current: a');
  await page.getByRole('combobox', { name: 'Unread navigation shortcut' }).selectOption('alt-shift'); await page.getByRole('button', { name: 'Close', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('textbox', { name: 'Composer' })).toBeFocused();
  await page.keyboard.press('Alt+ArrowDown'); await expect(page.getByRole('status', { includeHidden: true })).toHaveText('Current: a'); await page.keyboard.press('Alt+Shift+ArrowUp'); await expect(page.getByRole('status', { includeHidden: true })).toHaveText('Current: d');
  await page.reload(); await page.getByRole('textbox', { name: 'Composer' }).focus(); await page.keyboard.press('Control+/'); await expect(page.getByRole('combobox', { name: 'Unread navigation shortcut' })).toHaveValue('alt-shift');
  await page.getByRole('combobox', { name: 'Unread navigation shortcut' }).selectOption('disabled'); await page.getByRole('button', { name: 'Close', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await page.keyboard.press('Alt+Shift+ArrowDown'); await expect(page.getByRole('status', { includeHidden: true })).toHaveText('Current: a');
});
