import { expect, test } from '@playwright/test';
test('member role checkboxes enforce grants and preserve concurrent assignments and permissions', async ({ page }) => {
  await page.route(url => url.pathname === '/lib/matrix.ts', route => route.fulfill({ contentType: 'text/javascript', body: 'export const getMatrixClient=()=>window.fixtureClient;export const onMatrixUpdate=()=>()=>{};' }));
  await page.route('**/member-roles-test', route => route.fulfill({ contentType: 'text/html', body: `<!doctype html><html><body><div id="root"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;(await import('/tests/browser/fixtures/member-roles.tsx')).mountFixture();</script></body></html>` }));
  await page.goto('/member-roles-test'); await expect(page.getByRole('checkbox', { name: 'Privileged', exact: true })).toBeDisabled(); await expect(page.getByRole('checkbox', { name: 'Moderator', exact: true })).toBeDisabled(); await page.getByRole('checkbox', { name: 'Tag', exact: true }).check();
  await page.evaluate(() => { const w = window as any; w.policy.members['@target:local'] = ['other']; w.policy.members['@unrelated:local'] = ['tag']; w.policy.categoryOverrides.cat = { roles: { everyone: { send_messages: -1 } }, users: {} }; });
  await page.getByRole('button', { name: 'Save member roles' }).click(); await page.waitForFunction(() => (window as any).saves === 1); const policy = await page.evaluate(() => (window as any).policy);
  expect(policy.members['@target:local'].sort()).toEqual(['other', 'tag']); expect(policy.members['@unrelated:local']).toEqual(['tag']); expect(policy.categoryOverrides.cat.roles.everyone.send_messages).toBe(-1); expect(policy['io.tavern.previous_event']).toBe('$observed-policy'); await expect(page.getByRole('checkbox', { name: 'Other', exact: true })).toBeChecked();
});
