import {expect,test,type Page} from '@playwright/test';
async function fixture(page:Page){
  await page.route(url=>url.pathname==='/lib/matrix.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const getMatrixClient=()=>window.client;export const onMatrixUpdate=fn=>{window.listeners.push(fn);return()=>{window.listeners=window.listeners.filter(v=>v!==fn);};};'}));
  await page.route(url=>url.pathname==='/lib/api.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const accountArtworkOwner=()=>window.accountOwner;'}));
  await page.route(url=>url.pathname==='/lib/interactions.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const navigationPreferences=()=>({favorites:[]});export const setNavigationFlag=async()=>{};'}));
  await page.route(url=>url.pathname==='/lib/community.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const readServerBranding=()=>({icon:null});'}));
  await page.route(url=>url.pathname==='/app/community-settings.tsx',route=>route.fulfill({contentType:'text/javascript',body:'export const CommunityImage=()=>null;'}));
  await page.route('**/mobile-server-navigation-test',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;(await import("/tests/browser/fixtures/server-navigation.tsx")).mountFixture(true);</script></body></html>'}));
  await page.goto('/mobile-server-navigation-test');
}
for(const width of [320,390])test(`mobile server switcher is reachable and readable at${width}px with shared Move persistence`,async({page})=>{
  await page.setViewportSize({width,height:650});await fixture(page);
  await page.getByRole('button',{name:'Servers and folders',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Servers and folders',exact:true});await expect(dialog).toBeVisible();
  await expect(dialog.getByText('Alpha',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Games',exact:true})).toBeVisible();
  const widthInfo=await dialog.evaluate(element=>({width:element.clientWidth,scroll:element.scrollWidth,left:element.getBoundingClientRect().left,right:element.getBoundingClientRect().right}));expect(widthInfo.scroll).toBeLessThanOrEqual(widthInfo.width+1);expect(widthInfo.left).toBeGreaterThanOrEqual(8);expect(widthInfo.right).toBeLessThanOrEqual(width-8);
  await dialog.getByRole('button',{name:'Move Alpha',exact:true}).click();const move=page.getByRole('dialog',{name:'Move Alpha',exact:true});await expect(move).toBeVisible();
  await move.getByRole('combobox',{name:'Location'}).selectOption('games');await move.getByRole('combobox',{name:'Position'}).selectOption('!charlie:local');await move.getByRole('button',{name:'Move',exact:true}).click();await expect(move).toHaveCount(0);
  await expect(dialog).toBeVisible();await expect(dialog.locator('[data-folder-id="games"] [data-server-id]').first()).toHaveAttribute('data-server-id','!alpha:local');
  await page.reload();await page.getByRole('button',{name:'Servers and folders',exact:true}).click();await expect(page.locator('[data-folder-id="games"] [data-server-id]').first()).toHaveAttribute('data-server-id','!alpha:local');
});
test('mobile switcher supports keyboard selection and closes before server navigation',async({page})=>{await page.setViewportSize({width:390,height:700});await fixture(page);await page.getByRole('button',{name:'Servers and folders',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Alpha',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).selected)).toEqual(['!alpha:local']);});
test('parent management menus remain accessible and close the switcher before opening settings',async({page})=>{await page.setViewportSize({width:390,height:700});await fixture(page);await page.getByRole('button',{name:'Servers and folders',exact:true}).click();await page.getByRole('button',{name:'Alpha',exact:true}).focus();await page.keyboard.press('Shift+F10');await page.getByRole('menuitem',{name:'Server settings Alpha',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).selected)).toEqual(['settings:!alpha:local']);});
test('account replacement closes the mobile switcher and any pending nested Move dialog',async({page})=>{await page.setViewportSize({width:320,height:650});await fixture(page);await page.getByRole('button',{name:'Servers and folders',exact:true}).click();await page.getByRole('button',{name:'Move Alpha',exact:true}).click();await page.getByRole('combobox',{name:'Location'}).selectOption('games');await page.evaluate(()=>(window as any).holdRead=true);await page.getByRole('button',{name:'Move',exact:true}).click();await expect.poll(()=>page.evaluate(()=>!!(window as any).releaseRead)).toBe(true);await page.evaluate(()=>{const w=window as any;w.changeOwner();w.releaseRead();});await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).saved)).toEqual([]);});
test('desktop keeps the existing rail without a duplicate mobile entry',async({page})=>{await page.setViewportSize({width:1280,height:800});await fixture(page);await expect(page.getByRole('button',{name:'Servers and folders',exact:true})).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(0);});
