import { expect,test,type Page } from '@playwright/test';
async function fixture(page:Page){
  await page.route(url=>url.pathname==='/lib/matrix.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const getMatrixClient=()=>window.client;export const onMatrixUpdate=fn=>{window.listeners.push(fn);return()=>{window.listeners=window.listeners.filter(v=>v!==fn);};};'}));
  await page.route(url=>url.pathname==='/lib/api.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const accountArtworkOwner=()=>window.accountOwner;'}));
  await page.route(url=>url.pathname==='/lib/interactions.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const navigationPreferences=()=>({favorites:[],unread:window.manualUnread||[]});export const setNavigationFlag=async()=>{};'}));
  await page.route(url=>url.pathname==='/lib/community.ts',route=>route.fulfill({contentType:'text/javascript',body:'export const readServerBranding=()=>({icon:null});'}));
  await page.route(url=>url.pathname==='/app/community-settings.tsx',route=>route.fulfill({contentType:'text/javascript',body:'export const CommunityImage=()=>null;'}));
  await page.route('**/server-navigation-test',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;(await import("/tests/browser/fixtures/server-navigation.tsx")).mountFixture();</script></body></html>'}));
  await page.goto('/server-navigation-test');await expect(page.getByRole('button',{name:'Alpha',exact:true})).toBeVisible();
}
const rootOrder=(page:Page)=>page.locator('.server-rail-root [data-server-id]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-server-id')));
async function move(page:Page,name:string,location:string,before=''){await page.getByRole('button',{name:'Move '+name,exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('combobox',{name:'Location'}).selectOption(location);await page.getByRole('combobox',{name:'Position'}).selectOption(before);await page.getByRole('button',{name:'Move',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
async function drag(page:Page,name:string,target:string,edge:'before'|'after'|'inside'){
  const source=page.getByRole('button',{name,exact:true}),element=page.locator(target),transfer=await page.evaluateHandle(()=>new DataTransfer());
  await source.dispatchEvent('dragstart',{dataTransfer:transfer});const box=(await element.boundingBox())!;const y=edge==='before'?box.y+2:edge==='after'?box.y+box.height-2:box.y+box.height/2;
  await element.dispatchEvent('dragover',{dataTransfer:transfer,clientY:y});await expect(element).toHaveClass(new RegExp('drop-'+edge));
  await element.dispatchEvent('drop',{dataTransfer:transfer,clientY:y});await source.dispatchEvent('dragend',{dataTransfer:transfer});
}
test('keyboard move persists exact root and folder order after reload',async({page})=>{await fixture(page);await move(page,'Bravo','','!alpha:local');expect(await rootOrder(page)).toEqual(['!bravo:local','!alpha:local']);await move(page,'Alpha','games','!charlie:local');expect(await page.locator('[data-folder-id="games"] [data-server-id]').evaluateAll(elements=>elements.map(e=>e.getAttribute('data-server-id')))).toEqual(['!alpha:local','!charlie:local']);await page.reload();await expect(page.getByRole('button',{name:'Alpha',exact:true})).toBeVisible();expect(await rootOrder(page)).toEqual(['!bravo:local']);await expect(page.locator('[data-folder-id="games"] [data-server-id]').first()).toHaveAttribute('data-server-id','!alpha:local');});
test('dragging shows before/after cues, updates actual native account data and does not navigate',async({page})=>{await fixture(page);await drag(page,'Bravo','[data-server-id="!alpha:local"]','before');await expect.poll(()=>rootOrder(page)).toEqual(['!bravo:local','!alpha:local']);await expect.poll(()=>page.evaluate(()=>(window as any).saved.length)).toBe(1);await drag(page,'Bravo','[data-server-id="!alpha:local"]','after');await expect.poll(()=>rootOrder(page)).toEqual(['!alpha:local','!bravo:local']);expect(await page.evaluate(()=>(window as any).selected)).toEqual([]);});
test('folder drops and root fallback move real membership in the private navigation document',async({page})=>{await fixture(page);await drag(page,'Alpha','[data-folder-id="games"]','inside');await expect(page.locator('[data-folder-id="games"] [data-server-id="!alpha:local"]')).toBeVisible();await drag(page,'Alpha','.server-rail-root','inside');await expect(page.locator('.server-rail-root [data-server-id="!alpha:local"]')).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).saved.length)).toBe(2);expect(await page.evaluate(()=>(window as any).native.folders[0].serverIds)).toEqual(['!charlie:local']);});
test('folder create edit reorder and removal preserve its servers',async({page})=>{await fixture(page);await page.getByRole('button',{name:'Create server folder',exact:true}).click();await page.getByRole('textbox',{name:'Folder name'}).fill('Friends');await page.getByRole('checkbox',{name:'Alpha',exact:true}).check();await page.getByRole('button',{name:'Save folder',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Edit folder Friends',exact:true}).click();await page.getByRole('textbox',{name:'Folder name'}).fill('Friends nearby');await page.getByRole('button',{name:'Save folder',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Edit folder Friends nearby',exact:true}).click();await page.getByRole('button',{name:'Move folder…'}).click();await page.getByRole('combobox',{name:'Position'}).selectOption('games');await page.getByRole('button',{name:'Move',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('[data-folder-id]').first()).toContainText('A');await page.getByRole('button',{name:'Edit folder Friends nearby',exact:true}).click();await page.getByRole('button',{name:'Remove folder (keep servers)',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.server-rail-root [data-server-id="!alpha:local"]')).toBeVisible();});
test('optimistic failure restores the saved position and shows a nonblocking error',async({page})=>{await fixture(page);await page.evaluate(()=>{const w=window as any;w.holdWrite=true;w.failWrite=true;});await drag(page,'Bravo','[data-server-id="!alpha:local"]','before');expect(await rootOrder(page)).toEqual(['!bravo:local','!alpha:local']);await expect.poll(()=>page.evaluate(()=>!!(window as any).releaseWrite)).toBe(true);await page.evaluate(()=>(window as any).releaseWrite());await expect.poll(()=>rootOrder(page)).toEqual(['!alpha:local','!bravo:local']);await expect(page.getByText(/Fixture save denied/)).toBeVisible();});
test('server context menu keeps organization actions beside parent management actions',async({page})=>{await fixture(page);await page.getByRole('button',{name:'Alpha',exact:true}).click({button:'right'});await expect(page.getByRole('menuitem',{name:'Server settings Alpha'})).toBeVisible();await page.getByRole('menuitem',{name:'Move server…'}).click();await expect(page.getByRole('dialog',{name:'Move Alpha'})).toBeVisible();});
test('remote sync updates order without a reload',async({page})=>{await fixture(page);await page.evaluate(()=>{const w=window as any;w.sync({...w.native,order:['!bravo:local','!alpha:local','!charlie:local','!delta:local']});});await expect.poll(()=>rootOrder(page)).toEqual(['!bravo:local','!alpha:local']);});
test('account replacement retires the pending editor and prevents its native write',async({page})=>{await fixture(page);await page.getByRole('button',{name:'Move Alpha',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('combobox',{name:'Location'}).selectOption('games');await page.evaluate(()=>(window as any).holdRead=true);await page.getByRole('button',{name:'Move',exact:true}).click();await expect.poll(()=>page.evaluate(()=>!!(window as any).releaseRead)).toBe(true);await page.evaluate(()=>{const w=window as any;w.changeOwner();w.releaseRead();});await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).saved)).toEqual([]);});
test('touch-sized viewport exposes a usable Move control and fitting dialog',async({page})=>{await page.setViewportSize({width:320,height:650});await fixture(page);await page.getByRole('button',{name:'Move Alpha',exact:true}).focus();await page.keyboard.press('Enter');const box=await page.getByRole('dialog').boundingBox();expect(box!.x).toBeGreaterThanOrEqual(8);expect(box!.x+box!.width).toBeLessThanOrEqual(312);expect(await page.getByRole('dialog').evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true);await expect(page.getByRole('combobox',{name:'Location'})).toBeVisible();});

test('server rail uses current visible joined child counts and removes badges on mute, focus, membership and owner changes',async({page})=>{
  await fixture(page);const alpha=page.locator('[data-server-id="!alpha:local"]');
  await expect(alpha.getByRole('img',{name:'3 unread notifications'})).toBeVisible();await expect(alpha.getByRole('img',{name:'2 unread mentions and highlights'})).toBeVisible();
  await page.evaluate(()=>{const w=window as any;w.client.getRoom('!child:local').setUnreadNotificationCount('total',8);w.emit();});
  await expect(alpha.getByRole('img',{name:'8 unread notifications'})).toBeVisible();
  await page.evaluate(()=>{const w=window as any;w.readState.muted=['!muted:local','!child:local'];w.redraw();});await expect(alpha.getByRole('img')).toHaveCount(0);
  await page.evaluate(()=>{const w=window as any;w.manualUnread=['!manual:local'];w.emit();});await expect(alpha.getByRole('img',{name:'Manually marked unread'})).toBeVisible();
  await page.evaluate(()=>{const w=window as any;w.readState.focus=true;w.redraw();});await expect(alpha.getByRole('img')).toHaveCount(0);
  await page.evaluate(()=>{const w=window as any;w.readState.focus=false;w.readState.muted=['!muted:local'];w.client.getRoom('!child:local').updateMyMembership('leave');w.manualUnread=[];w.emit();w.redraw();});await expect(alpha.getByRole('img')).toHaveCount(0);
  await page.evaluate(()=>{const w=window as any;w.client.getRoom('!child:local').updateMyMembership('join');w.client.getRoom('!alpha:local').updateMyMembership('leave');w.emit();});await expect(alpha.getByRole('img')).toHaveCount(0);
  await page.evaluate(()=>{const w=window as any;w.client.getRoom('!alpha:local').updateMyMembership('join');w.emit();});await expect(alpha.getByRole('img',{name:'8 unread notifications'})).toBeVisible();
  await page.evaluate(()=>{const w=window as any;w.client=null;w.changeOwner();});await expect(page.locator('.server-read-state')).toHaveCount(0);
});
