import {expect,test,type Page} from '@playwright/test';
async function fixture(page:Page){
 let revoked=false,checks=0;const messages:string[]=[];page.on('console',message=>messages.push(message.text()));
 await page.route('**/api/admin/**',route=>route.fulfill({json:{users:1,rooms:1,checks:[{component:'TURN',status:'not_tested',detail:'Server HTTP cannot prove public UDP.'}],checkedAt:Date.now()}}));
 await page.route('**/api/auth/session',route=>{checks++;return route.fulfill({json:{userId:'@admin:local',deviceId:'TURN-DEVICE',baseUrl:'http://127.0.0.1:5173/api/matrix',admin:!revoked,passwordChangeRequired:false,mfaEnrollmentRequired:false}});});
 await page.route('**/api/matrix/**',route=>route.fulfill({json:{uris:['turn:turn.example.test:3478?transport=udp'],username:'short-lived-user',password:'TURN-TRAFFIC-SECRET',ttl:3600}}));
 await page.route('**/turn-traffic-test',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta charset="utf-8"></head><body><div id="root"></div><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;(await import("/tests/browser/fixtures/turn-traffic-diagnostics.tsx")).mountFixture();</script></body></html>'}));
 await page.goto('/turn-traffic-test');await page.getByRole('button',{name:'Diagnostics',exact:true}).click();const panel=page.getByRole('region',{name:'Browser TURN test'});await panel.getByRole('button',{name:'Test TURN relay traffic',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).trafficFixture.ready)).toBe(true);
 return{panel,messages,checks:()=>checks,revoke:()=>revoked=true};
}
const cleanup=async(page:Page)=>expect(await page.evaluate(()=>{const f=(window as any).trafficFixture;return{captures:f.captures,peers:f.peers.map((p:any)=>p.closed),channels:f.channels.map((c:any)=>c.closed),policy:f.peers.map((p:any)=>p.configuration.iceTransportPolicy)};})).toEqual({captures:0,peers:[true,true],channels:[true,true],policy:['relay','relay']});
test('mounted admin traffic test exchanges both nonces and verifies selected routes with fresh administrator access',async({page})=>{const f=await fixture(page);await expect(f.panel.getByRole('status')).toContainText('bidirectional');await expect(f.panel.getByRole('button',{name:'Test TURN allocation',exact:true})).toBeDisabled();await page.evaluate(()=>(window as any).trafficFixture.exchange());await expect(f.panel.getByRole('status')).toContainText('Bidirectional relay traffic confirmed');expect(await page.evaluate(()=>(window as any).trafficFixture.sent)).toBe(2);expect(f.checks()).toBe(2);await cleanup(page);await expect(page.locator('body')).not.toContainText('TURN-TRAFFIC-SECRET');await expect(page.locator('body')).not.toContainText('192.0.2.123');expect(f.messages.join('\n')).not.toContain('TURN-TRAFFIC-SECRET');await expect(page.getByText('not_tested',{exact:true})).toBeVisible();});
for(const outcome of ['missingStats','nonRelay','badReceipt'])test(`${outcome} never claims verified bidirectional relay traffic`,async({page})=>{const f=await fixture(page);await page.evaluate(key=>{const f=(window as any).trafficFixture;f[key]=true;f.exchange();},outcome);await expect(f.panel.getByRole('status')).toContainText(outcome==='missingStats'?'Data exchanged, but this browser could not verify':'could not be confirmed');await cleanup(page);});
for(const action of ['cancel','navigation','account'])test(`${action} closes both peers before late exchange can publish`,async({page})=>{const f=await fixture(page);if(action==='cancel')await f.panel.getByRole('button',{name:'Cancel TURN test'}).click();if(action==='navigation')await page.getByRole('button',{name:'Overview',exact:true}).click();if(action==='account')await page.evaluate(()=>(window as any).trafficFixture.replaceAccount());await expect.poll(()=>page.evaluate(()=>(window as any).trafficFixture.peers.every((p:any)=>p.closed))).toBe(true);await page.evaluate(()=>(window as any).trafficFixture.exchange());await expect(page.locator('body')).not.toContainText('Bidirectional relay traffic confirmed');await cleanup(page);});
test('final administrator revocation and the overall deadline prevent success',async({page})=>{let f=await fixture(page);f.revoke();await page.evaluate(()=>(window as any).trafficFixture.exchange());await expect(f.panel.getByRole('status')).toContainText('administrator access could not be verified');await cleanup(page);await page.clock.install();f=await fixture(page);await page.clock.runFor(15000);await expect(f.panel.getByRole('status')).toContainText('timed out after 15 seconds');await cleanup(page);});
