import test from 'node:test';
import assert from 'node:assert/strict';
import * as wasm from '@matrix-org/matrix-sdk-crypto-wasm';
import { loadTs } from './load-ts.mjs';
await wasm.initAsync();
const {discoverBackup,createOrResumeBackup}=loadTs('../lib/backup.ts',{'matrix-js-sdk/lib/http-api':{Method:{Get:'GET',Post:'POST'},ClientPrefix:{V3:'v3'}},'matrix-js-sdk/lib/base64':{decodeBase64:s=>new Uint8Array(Buffer.from(s,'base64'))},'@matrix-org/matrix-sdk-crypto-wasm':wasm});
function fixture(){let server=null,active=null;const requests=[],secrets=new Map();const crypto={storeSessionBackupPrivateKey:async(_key,version)=>active=version,checkKeyBackupAndEnable:async()=>{},getActiveSessionBackupVersion:async()=>active};const c={getDeviceId:()=>'TEST',getCrypto:()=>crypto,secretStorage:{get:async name=>secrets.get(name)||null,store:async(name,key)=>secrets.set(name,key)},http:{authedRequest:async(method,path,_query,body)=>{requests.push({method,path,body});if(method==='GET'){if(server)return server;throw{errcode:'M_NOT_FOUND'};}if(method==='POST'){server={...body,version:'1'};return{version:'1'};}throw new Error('Destructive HTTP method');}}};return{c,requests,secrets,setServer:x=>server=x};}
test('network failure is not interpreted as absence of backup',async()=>{const f=fixture();f.c.http.authedRequest=async()=>{throw new Error('offline');};await assert.rejects(discoverBackup(f.c),/offline/);await assert.rejects(createOrResumeBackup(f.c),/offline/);assert.equal(f.secrets.size,0);});
test('backup creation preserves pending key before POST and never deletes versions',async()=>{const f=fixture(),original=f.c.http.authedRequest;f.c.http.authedRequest=async(method,...args)=>{if(method==='POST')assert.ok(f.secrets.has('io.tavern.backup.pending.TEST'));return original(method,...args);};await createOrResumeBackup(f.c);assert.equal(f.requests.filter(r=>r.method==='POST').length,1);assert.ok(f.requests.every(r=>['GET','POST'].includes(r.method)));assert.equal(f.secrets.get('m.megolm_backup.v1'),f.secrets.get('io.tavern.backup.pending.TEST'));});
test('uncertain POST can resume from encrypted pending secret without creating another version',async()=>{const f=fixture(),original=f.c.http.authedRequest;let first=true;f.c.http.authedRequest=async(method,...args)=>{const result=await original(method,...args);if(method==='POST'&&first){first=false;throw new Error('connection lost after acceptance');}return result;};await assert.rejects(createOrResumeBackup(f.c));await createOrResumeBackup(f.c);assert.equal(f.requests.filter(r=>r.method==='POST').length,1);});
test('an unrelated existing backup is preserved',async()=>{const f=fixture();f.setServer({version:'existing',algorithm:'m.megolm_backup.v1.curve25519-aes-sha2',auth_data:{public_key:'different'}});await assert.rejects(createOrResumeBackup(f.c),/different key/);assert.equal(f.requests.filter(r=>r.method!=='GET').length,0);assert.equal(f.secrets.size,0);});
