import test from 'node:test';
import assert from 'node:assert/strict';
import { loadTs } from './load-ts.mjs';
const { projectServerAuditEvent: project, filterServerAudit } = loadTs('../lib/server-audit.ts', { 'matrix-js-sdk': {}, './matrix': {}, './roles': {} });
const event = (type, content, extra = {}) => ({ event_id: '$event', sender: '@mod:local', origin_server_ts: 1700000000000, state_key: '@member:local', type, content, ...extra });
test('audit differentiates bans, profile changes, redactions and preserves actual actors and targets', () => { const banned = project(event('m.room.member', { membership: 'ban', reason: 'Spam' }), '!room:local'); assert.equal(banned.kind, 'moderation'); assert.equal(banned.actor, '@mod:local'); assert.equal(banned.target, '@member:local'); assert.equal(banned.detail, 'Spam'); assert.equal(project(event('m.room.member', { membership: 'join' }, { unsigned: { prev_content: { membership: 'join' } } }), '!room:local').action, 'Updated member profile'); assert.equal(project(event('m.room.redaction', { redacts: '$target', reason: 'Removed duplicate' }), '!room:local').target, '$target'); assert.equal(project(event('m.room.encrypted', { ciphertext: 'secret' }), '!room:local'), null); });
test('audit never reconstructs redacted detail or invents role changes without previous state', () => { const raw = event('io.tavern.roles', { roles: [{ id: 'a', name: 'Admin' }], members: {} }); assert.equal(project(raw, '!server:local').detail, '1 roles; 0 explicit member assignments'); assert.match(project({ ...raw, unsigned: { prev_content: { roles: [] } } }, '!server:local').detail, /Added: Admin/); const redacted = project({ ...raw, unsigned: { redacted_because: {} } }, '!server:local'); assert.equal(redacted.action, 'Redacted audit event'); assert.equal(redacted.detail.includes('Admin'), false); });
test('audit filters use exact actor and bounded time metadata', () => { const entries = [project(event('m.room.member', { membership: 'ban' }), '!room:l'), project(event('m.room.name', { name: 'Chat' }, { sender: '@owner:l' }), '!room:l')]; assert.equal(filterServerAudit(entries, { actor: '@mod:local', target: 'member', kind: 'moderation', since: '2020-01-01', until: '2030-01-01' }).length, 1); assert.equal(filterServerAudit(entries, { actor: '@mod', target: '', kind: 'all', since: '', until: '' }).length, 0); });
test('malformed timeout timestamps do not break audit rendering', () => { assert.doesNotThrow(() => project(event('io.tavern.timeout', { until: Number.MAX_SAFE_INTEGER }), '!room:l')); });
