import test from 'node:test';
import assert from 'node:assert/strict';
import { loadTs } from './load-ts.mjs';
const load = matrix => loadTs('../lib/server-navigation.ts', { './matrix': matrix, './api': { accountArtworkOwner:()=>matrix.account } });
const api = load({});
const { normalizeServerNavigation, moveServerToFolder } = api;
const ids = ['!a:local','!b:local','!c:local','!d:local'];
const initial = () => normalizeServerNavigation({folders:[{id:'one',name:'Gaming',serverIds:[ids[2]]},{id:'two',name:'Work',serverIds:[ids[3]]}],order:ids});
function fixture() {
  const m={account:{},getMatrixClient:()=>client}, f={native:initial(),cache:initial(),writes:[],beforeRead:null,beforeWrite:null,actor:'@me:local',device:'D',base:'https://local/api/matrix'};
  const client={getUserId:()=>f.actor,getDeviceId:()=>f.device,getHomeserverUrl:()=>f.base,getAccountData:()=>({getContent:()=>structuredClone(f.cache)}),http:{authedRequest:async(method,path,_query,content)=>{assert.match(path,/^\/user\/%40me%3Alocal\/account_data\/io.tavern.server_folders$/);if(method==='GET'){await f.beforeRead?.();return structuredClone(f.native);}assert.equal(method,'PUT');await f.beforeWrite?.(content);f.writes.push(structuredClone(content));f.native=structuredClone(content);return {};}}};
  return {...f,m,client,api:load(m),state:f};
}
const gate=()=>{let release;const promise=new Promise(resolve=>release=resolve);return{promise,release};};
const turn=()=>new Promise(resolve=>setImmediate(resolve));
test('server folders reject duplicate assignments and unsafe colors',()=>{const state=normalizeServerNavigation({folders:[{id:'one',name:'Gaming',color:'url(https://tracker)',serverIds:[ids[0],ids[0]]},{id:'two',name:'Work',serverIds:[ids[0],ids[1]]}],collapsed:['one','missing'],order:[ids[0],ids[0],'javascript:bad']});assert.equal(state.folders[0].color,'');assert.deepEqual(state.folders[0].serverIds,[ids[0]]);assert.deepEqual(state.folders[1].serverIds,[ids[1]]);assert.deepEqual(state.collapsed,['one']);assert.deepEqual(state.order,[ids[0]]);});
test('moving a server preserves other folders and supports ungrouping',()=>{const old=initial(),moved=moveServerToFolder(old,ids[2],'two');assert.deepEqual(moved.folders[0].serverIds,[]);assert.deepEqual(moved.folders[1].serverIds,[ids[3],ids[2]]);assert.deepEqual(old.folders[0].serverIds,[ids[2]]);assert.deepEqual(moveServerToFolder(moved,ids[2],'').folders[1].serverIds,[ids[3]]);assert.throws(()=>moveServerToFolder(old,ids[2],'missing'));});
test('relative drops reorder before and after and move between folders and root',()=>{let state=api.moveServerRelative(initial(),ids[1],ids[0],'before',ids);assert.deepEqual(state.order,[ids[1],ids[0],ids[2],ids[3]]);state=api.moveServerRelative(state,ids[0],ids[2],'after',ids);assert.equal(api.serverFolderId(state,ids[0]),'one');assert.deepEqual(state.order,[ids[1],ids[2],ids[0],ids[3]]);state=api.positionServer(state,ids[0],'',ids[1],ids);assert.equal(api.serverFolderId(state,ids[0]),'');assert.deepEqual(state.order,[ids[0],ids[1],ids[2],ids[3]]);assert.deepEqual(api.positionFolder(state,'two','one').folders.map(f=>f.id),['two','one']);});
test('folder editor merges only changed fields and membership without stealing remotely moved servers',()=>{const old=initial(),original=structuredClone(old.folders[0]),draft={...original,name:'Games'};let remote=moveServerToFolder(old,ids[2],'two');remote.folders[0].color='#123456';remote=moveServerToFolder(remote,ids[1],'one');const next=api.saveServerFolder(remote,draft,original);assert.deepEqual(next.folders[0],{...remote.folders[0],name:'Games'});assert.deepEqual(next.folders[1].serverIds,[ids[3],ids[2]]);assert.throws(()=>api.saveServerFolder({...old,folders:[]},draft,original),/removed/);});
test('fresh native merge preserves other-device folder updates and unknown version1 extension fields',async()=>{const f=fixture();f.state.native={...f.state.native,extra:{retained:true},folders:[...f.state.native.folders,{id:'remote',name:'Elsewhere',serverIds:[]}]};await f.api.updateServerNavigation(p=>f.api.moveServerRelative(p,ids[1],ids[0],'before',ids));assert.equal(f.state.writes[0].folders.length,3);assert.deepEqual(f.state.writes[0].extra,{retained:true});assert.deepEqual(f.api.readServerNavigation().order,[ids[1],ids[0],ids[2],ids[3]]);});
test('failed first save rebases the pending move instead of erasing it',async()=>{const f=fixture(),wait=gate();let writes=0;f.state.beforeWrite=async()=>{if(++writes===1){await wait.promise;throw Error('First save failed');}};const first=f.api.updateServerNavigation(p=>f.api.moveServerRelative(p,ids[1],ids[0],'before',ids));const failure=assert.rejects(first,/First save failed/);await turn();const second=f.api.updateServerNavigation(p=>f.api.positionServer(p,ids[2],'','',ids));assert.equal(f.api.serverFolderId(f.api.readServerNavigation(),ids[2]),'');wait.release();await failure;await second;assert.equal(f.api.serverFolderId(f.api.readServerNavigation(),ids[2]),'');assert.deepEqual(f.state.native.order,ids);assert.equal(f.state.writes.length,1);});
test('a sync update while saving retains optimistic pending changes and merges fresh authority',async()=>{const f=fixture(),wait=gate();f.state.beforeRead=async()=>{await wait.promise;};const pending=f.api.updateServerNavigation(p=>f.api.moveServerRelative(p,ids[1],ids[0],'before',ids));f.state.cache=structuredClone(f.state.native);f.state.cache.folders[0].name='Remote name';f.state.native=structuredClone(f.state.cache);f.api.refreshServerNavigation();assert.deepEqual(f.api.readServerNavigation().order,[ids[1],ids[0],ids[2],ids[3]]);wait.release();await pending;assert.equal(f.state.native.folders[0].name,'Remote name');});
for(const drift of ['account','device','actor','base','client'])test(`${drift} replacement while native read waits prevents old queued writes`,async()=>{const f=fixture(),wait=gate();f.state.beforeRead=async()=>wait.promise;const task=f.api.updateServerNavigation(p=>({...p,order:[...ids].reverse()}));const rejection=assert.rejects(task,/account changed/);await turn();if(drift==='account')f.m.account={};if(drift==='device')f.state.device='OTHER';if(drift==='actor')f.state.actor='@other:local';if(drift==='base')f.state.base='https://other/api/matrix';if(drift==='client')f.m.getMatrixClient=()=>({...f.client});wait.release();await rejection;assert.equal(f.state.writes.length,0);});
test('unsupported future version is never overwritten',async()=>{const f=fixture();f.state.native.version=2;await assert.rejects(f.api.updateServerNavigation(p=>({...p,order:[]})),/unsupported format/);assert.equal(f.state.writes.length,0);});
test('an intervening native writer is reported and its actual state is shown',async()=>{const f=fixture();let reads=0;f.state.beforeRead=async()=>{if(++reads===2)f.state.native={...f.state.native,order:ids};};await assert.rejects(f.api.updateServerNavigation(p=>({...p,order:[...ids].reverse()})),/Another device/);assert.deepEqual(f.api.readServerNavigation().order,ids);assert.equal(f.state.writes.length,1);});
