import { useEffect, useState } from 'react';
import { requestApi } from '@/lib/api';
import { Field } from './auth-gateway';
import { toast } from 'sonner';
export { AdminRooms } from './admin-room-browser';
export function StoragePolicy() {
  const [value, setValue] = useState<any>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [operation, setOperation] = useState('');
  async function load() { setBusy(true); setError(''); try { setValue(await requestApi('/admin/storage')); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function reconcile() { setBusy(true); setOperation('reconcile'); setError(''); try { setValue(await requestApi('/admin/storage/reconcile', {})); toast.success('Storage usage checked against the homeserver'); } catch (e: any) { setError(e.message); } finally { setBusy(false); setOperation(''); } }
  const knownUsage = value?.usageInitialized === true && typeof value?.globalUsedBytes === 'number' && Number.isFinite(value.globalUsedBytes);
  return <section className="product-section"><div className='admin-toolbar'><h2>Storage limits and usage</h2><button className='secondary-button' disabled={busy} onClick={() => void load()}>Reload storage</button></div><p>Byte quotas include uploaded encrypted media. File contents remain encrypted, so server rules cannot classify their contents.</p>{error && <p className="connect-error" role="alert">{error}</p>}{busy && !value && <p role='status'>Checking storage…</p>}
    {value && <><div className='admin-metrics'><article className='admin-metric'><span>Recorded instance usage</span><strong>{knownUsage ? (value.globalUsedBytes / 1048576).toLocaleString(undefined, { maximumFractionDigits: 2 }) + ' MiB' : 'Unavailable'}</strong></article><article className='admin-metric'><span>Uncertain upload reservations</span><strong>{Number.isSafeInteger(value.uncertainReservations) ? value.uncertainReservations : 'Unavailable'}</strong></article></div><p>{value.scope || 'Storage scope is unavailable. Reload storage before relying on the usage count.'}</p><p>Last reconciled: {typeof value.reconciledAt === 'number' && Number.isFinite(value.reconciledAt) ? new Date(value.reconciledAt).toLocaleString() : 'Not yet reconciled'}</p>{!knownUsage && <p role='status'>Usage has not been verified. Uploads stay locked until the homeserver inventory can be checked.</p>}
      {typeof value.uncertainReservations === 'number' && value.uncertainReservations > 0 && <p>Some uploads lost their final response. Their reserved bytes remain counted until reconciliation confirms whether the files were stored.</p>}<button className='secondary-button' disabled={busy} onClick={() => void reconcile()}>{operation === 'reconcile' ? 'Reconciling usage…' : 'Reconcile storage usage'}</button><p className='login-help'>Reconciliation reads the homeserver’s current local media inventory and briefly pauses new uploads while updating the counts.</p>
      <form className="dialog-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { setValue(await requestApi('/admin/storage', { maxUploadBytes: value.maxUploadBytes, userQuotaBytes: value.userQuotaBytes, globalQuotaBytes: value.globalQuotaBytes }, 'PUT')); toast.success('Storage limits saved'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}><fieldset disabled={busy}>{[['maxUploadBytes', 'Maximum file size (MiB)'], ['userQuotaBytes', 'Per-user quota (MiB)'], ['globalQuotaBytes', 'Instance quota (MiB)']].map(([key, label]) => <Field label={label} key={key}><input type="number" required min={0.001} step={0.001} max={key === 'maxUploadBytes' ? 10 : undefined} value={value[key] / 1048576} onChange={e => setValue({ ...value, [key]: Math.round(Number(e.target.value) * 1048576) })}/></Field>)}<button className="primary-button">Save storage policy</button></fieldset></form></>}
  </section>;
}
