import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { onMatrixUpdate } from '@/lib/matrix';
import { bulkRedactMessages, canBulkRedact, type BulkRedactionResult } from '@/lib/bulk-moderation';
type ModerationMessage = { id: string; author_id: string; body: string };
export function BulkModeration({ roomId, messages, onChanged }: { roomId: string; messages: ModerationMessage[]; onChanged?: () => Promise<unknown> }) {
  const [selected, setSelected] = useState<string[]>([]), [author, setAuthor] = useState(''), [reason, setReason] = useState(''), [confirmation, setConfirmation] = useState(''), [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false), [progress, setProgress] = useState(0), [result, setResult] = useState<BulkRedactionResult | null>(null), [error, setError] = useState('');
  const abort = useRef<AbortController | null>(null), [, redraw] = useState(0);
  useEffect(() => onMatrixUpdate(() => redraw(value => value + 1)), []);
  useEffect(() => { setSelected([]); setOpen(false); setResult(null); setError(''); return () => abort.current?.abort(); }, [roomId]);
  if (!canBulkRedact(roomId)) return null;
  const candidates = messages.filter(message => !author.trim() || message.author_id === author.trim()).slice(-100), chosen = messages.filter(message => selected.includes(message.id)).slice(0, 50), expected = 'DELETE ' + chosen.length;
  async function submit() {
    if (!chosen.length || confirmation !== expected || busy) return;
    const controller = new AbortController(); abort.current = controller; setBusy(true); setError(''); setProgress(0);
    try { const outcome = await bulkRedactMessages(roomId, chosen.map(message => message.id), reason, { signal: controller.signal, onProgress: setProgress }); setResult(outcome); setSelected(ids => ids.filter(id => !outcome.redacted.includes(id))); setOpen(false); setConfirmation(''); if (outcome.redacted.length) toast.success(outcome.redacted.length + ' messages redacted'); if (outcome.failures.length || outcome.remaining.length) toast('Some selected messages remain. Review the results before retrying.'); await onChanged?.(); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); abort.current = null; }
  }
  return <section className='product-section'><details><summary>Bulk message moderation</summary><p>Select up to 50 messages from the latest 100 loaded matches. Redaction removes content from the live conversation; recipients and backups may retain copies.</p><label className='product-field'><span>Filter by exact sender ID</span><input maxLength={255} value={author} onChange={event => setAuthor(event.target.value)} disabled={busy}/></label><div style={{ maxHeight: 320, overflow: 'auto' }}>{candidates.map(message => <label className='check-label' key={message.id}><input type='checkbox' checked={selected.includes(message.id)} disabled={busy || !selected.includes(message.id) && selected.length >= 50} onChange={event => setSelected(ids => event.target.checked ? [...ids, message.id] : ids.filter(id => id !== message.id))}/><span><strong>{message.author_id}</strong><br/>{message.body.slice(0, 160) || 'Attachment or empty message'}<br/><small>{message.id}</small></span></label>)}</div>{!candidates.length && <p>No loaded messages match this sender.</p>}<div className='product-actions'><button className='secondary-button danger-text' disabled={busy || !chosen.length} onClick={() => { setOpen(true); setConfirmation(''); setError(''); }}>Review {chosen.length} selected messages…</button><button className='secondary-button' disabled={busy || !selected.length} onClick={() => setSelected([])}>Clear selection</button></div></details>
    {result && <section className='product-section' aria-label='Bulk moderation results'><p>{result.redacted.length} redacted · {result.failures.length} unconfirmed or rejected · {result.remaining.length} not submitted{result.cancelled ? ' · Cancelled after the last in-flight request' : ''}</p>{result.failures.map(failure => <p key={failure.id}><code>{failure.id}</code>: {failure.message}</p>)}</section>}
    <Dialog open={open} onOpenChange={next => { if (!busy) setOpen(next); }}><DialogContent className='tavern-dialog'><DialogHeader><DialogTitle>Redact {chosen.length} messages?</DialogTitle><DialogDescription>This action cannot restore deleted content. Each event is checked by your authenticated homeserver before redaction. Your moderation reason will be room metadata visible to members.</DialogDescription></DialogHeader><form className='dialog-form' onSubmit={event => { event.preventDefault(); void submit(); }}><details><summary>Review selected messages</summary>{chosen.map(message => <p key={message.id}><strong>{message.author_id}</strong>: {message.body.slice(0, 160) || 'Attachment or empty message'}<br/><code>{message.id}</code></p>)}</details><label>Moderation reason<textarea required maxLength={500} value={reason} disabled={busy} onChange={event => setReason(event.target.value)}/></label><label>Type {expected} to confirm<input required autoComplete='off' value={confirmation} disabled={busy} onChange={event => setConfirmation(event.target.value)}/></label>{busy && <p role='status'>Processed {progress} of {chosen.length} messages.</p>}{error && <p role='alert' className='connect-error'>{error}</p>}<div className='product-actions'><button className='primary-button delete-confirm' disabled={busy || !reason.trim() || confirmation !== expected}>Redact selected messages</button>{busy ? <button type='button' className='secondary-button' onClick={() => abort.current?.abort()}>Stop after current message</button> : <button type='button' className='secondary-button' onClick={() => setOpen(false)}>Cancel</button>}</div></form></DialogContent></Dialog>
  </section>;
}
