import { useState, type ReactNode } from 'react';
import { toast } from 'sonner';
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuSeparator, ContextMenuTrigger } from '@/components/ui/context-menu';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { getMatrixClient, matrixApi } from '@/lib/matrix';
import { canEditCommunity, readServerLayout, saveServerLayout } from '@/lib/community';
import { setRoomNotifications } from '@/lib/notifications';
export function CategoryMenu({ serverId, categoryId, collapsed, onToggle, children, editor }: { serverId: string; categoryId: string; collapsed: boolean; onToggle: () => void; children: ReactNode; editor: ReactNode }) {
  const [open, setOpen] = useState(false), [remove, setRemove] = useState(false), [busy, setBusy] = useState(false);
  const ids = () => readServerLayout(serverId).channels.filter(c => c.category === categoryId).map(c => c.id).filter(id => getMatrixClient()?.getRoom(id)?.getMyMembership() === 'join');
  async function act(operation: 'read' | 'mute' | 'all' | 'delete') { setBusy(true); try { const c = getMatrixClient(); if (!c) return; if (operation === 'delete') { const p = readServerLayout(serverId); await saveServerLayout(serverId, { ...p, categories: p.categories.filter(c => c.id !== categoryId), channels: p.channels.map(c => c.category === categoryId ? { ...c, category: '' } : c) }); setRemove(false); } else { const channels = ids(); for (let i = 0; i < channels.length; i += 4) await Promise.all(channels.slice(i, i + 4).map(async id => { if (operation === 'read') { const event = c.getRoom(id)?.getLiveTimeline().getEvents().filter(e => !e.status).at(-1); if (event?.getId()) await matrixApi('read', { conversation: id, id: event.getId() }); } else await setRoomNotifications(c, id, operation); })); } toast.success(operation === 'read' ? 'Category marked read' : operation === 'delete' ? 'Category removed; channels retained' : 'Category notifications updated'); } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); } }
  return <><ContextMenu><ContextMenuTrigger asChild>{children}</ContextMenuTrigger><ContextMenuContent><ContextMenuItem onSelect={onToggle}>{collapsed ? 'Expand' : 'Collapse'}</ContextMenuItem><ContextMenuItem disabled={busy} onSelect={() => void act('read')}>Mark category read</ContextMenuItem><ContextMenuItem disabled={busy} onSelect={() => void act('mute')}>Mute category notifications</ContextMenuItem><ContextMenuItem disabled={busy} onSelect={() => void act('all')}>All category notifications</ContextMenuItem>{canEditCommunity(serverId, 'layout') && <><ContextMenuSeparator /><ContextMenuItem onSelect={() => setOpen(true)}>Edit categories and order</ContextMenuItem><ContextMenuItem className="danger-text" onSelect={() => setRemove(true)}>Delete category</ContextMenuItem></>}</ContextMenuContent></ContextMenu><Dialog open={open} onOpenChange={setOpen}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Categories and server settings</DialogTitle><DialogDescription>Organize channels and customize this server.</DialogDescription></DialogHeader>{open && editor}</DialogContent></Dialog><AlertDialog open={remove} onOpenChange={value => { if (!busy) setRemove(value); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this category?</AlertDialogTitle><AlertDialogDescription>Its channels will move to Uncategorized. Messages and channel permissions are retained.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e => { e.preventDefault(); void act('delete'); }}>Delete category</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
