import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
import { canEditChannelPolicy, canModerateMember, channelKinds, memberTimeout, moderateMember, readChannelPolicy, saveChannelPolicy, timeoutMember, type ChannelKind } from '@/lib/channel-policy';

export function ChannelPolicySettings({ roomId, enabled, onChanged }: { roomId: string; enabled: boolean; onChanged?: () => Promise<unknown> }) {
  const [value, setValue] = useState(() => readChannelPolicy(roomId)), [busy, setBusy] = useState(false), [error, setError] = useState(''), [confirm, setConfirm] = useState(false);
  useEffect(() => { setValue(readChannelPolicy(roomId)); }, [roomId]);
  if (!enabled || !canEditChannelPolicy(roomId)) return null;
  async function save() { setBusy(true); setError(''); try { await saveChannelPolicy(roomId, value); setConfirm(false); await onChanged?.(); toast.success('Channel restrictions saved'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section className="settings-section"><h3>Channel behavior</h3><form className="dialog-form" onSubmit={event => { event.preventDefault(); if (value.archived && !readChannelPolicy(roomId).archived) setConfirm(true); else void save(); }}><fieldset disabled={busy}>
    <label>Channel kind<select value={value.kind} onChange={e => setValue({ ...value, kind: e.target.value as ChannelKind })}>{Object.entries(channelKinds).map(([kind, name]) => <option value={kind} key={kind}>{name}</option>)}</select></label>
    <p className="login-help">Announcement, rules and read-only channels allow moderators to post. Voice, video, forum and media channels retain their conversation history.</p>
    <label>Slow mode<select value={value.slowModeSeconds} onChange={e => setValue({ ...value, slowModeSeconds: Number(e.target.value) })}>{[0, 5, 10, 30, 60, 300, 900, 3600, 21600].map(seconds => <option value={seconds} key={seconds}>{seconds ? seconds < 60 ? `${seconds} seconds` : `${seconds / 60} minutes` : 'Off'}</option>)}</select></label>
    <p className="login-help">Slow mode limits how often members can send messages. Moderators are exempt.</p><label className="check-label"><input type="checkbox" checked={value.archived} onChange={e => setValue({ ...value, archived: e.target.checked })}/>Archive this channel</label><p className="login-help">Archiving preserves history and stops new messages, reactions and call joins until the channel is restored.</p><button className="primary-button">Save channel behavior</button></fieldset></form>
    {error && <p className="connect-error" role="alert">{error}</p>}<Dialog open={confirm} onOpenChange={open => { if (!busy) setConfirm(open); }}><DialogContent><DialogHeader><DialogTitle>Archive this channel?</DialogTitle><DialogDescription>Everyone can still read the history. New messages, reactions and call joins will stop until an authorized member restores the channel.</DialogDescription></DialogHeader><div className="inline-actions"><button className="primary-button" disabled={busy} onClick={() => void save()}>Archive channel</button><button className="secondary-button" disabled={busy} onClick={() => setConfirm(false)}>Cancel</button></div></DialogContent></Dialog></section>;
}

export function ModerationActions({ roomId, userId, enabled, onChanged }: { roomId: string; userId?: string; enabled: boolean; onChanged?: () => Promise<unknown> }) {
  const [target, setTarget] = useState(userId || ''), [action, setAction] = useState(''), [reason, setReason] = useState(''), [seconds, setSeconds] = useState(3600), [busy, setBusy] = useState(false), [error, setError] = useState(''), [, refresh] = useState(0);
  useEffect(() => onMatrixUpdate(() => refresh(value => value + 1)), []);
  useEffect(() => { setTarget(userId || ''); setAction(''); }, [roomId, userId]);
  const client = getMatrixClient(), room = client?.getRoom(roomId);
  const available = room?.getMembers().filter(member => ['join', 'invite', 'ban'].includes(member.membership || '') && ['timeout', 'kick', 'ban'].some(op => canModerateMember(roomId, member.userId, op as 'timeout' | 'kick' | 'ban'))) || [];
  if (!enabled || !room || !available.length || (userId && !available.some(member => member.userId === userId))) return null;
  const timeout = memberTimeout(roomId, target), member = room.getMember(target), banned = member?.membership === 'ban';
  async function submit() { setBusy(true); setError(''); try { if (action === 'timeout' || action === 'clear-timeout') await timeoutMember(roomId, target, action === 'timeout' ? seconds : 0, reason); else await moderateMember(roomId, target, action as 'kick' | 'ban' | 'unban', reason); setAction(''); setReason(''); await onChanged?.(); toast.success('Member moderation updated'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section className="settings-section"><h3>Member moderation</h3>{!userId && <label>Member<select value={target} onChange={e => { setTarget(e.target.value); setAction(''); }}><option value="">Select a member</option>{available.map(member => <option key={member.userId} value={member.userId}>{member.name}</option>)}</select></label>}
    {target && <><p>{member?.name || target}{timeout.until > Date.now() ? ' · Timed out until ' + new Date(timeout.until).toLocaleString() : ''}</p><div className="inline-actions">{!banned && canModerateMember(roomId, target, 'timeout') && <><button className="secondary-button" onClick={() => setAction('timeout')}>Timeout</button>{timeout.until > Date.now() && <button className="secondary-button" onClick={() => setAction('clear-timeout')}>Remove timeout</button>}</>}{!banned && canModerateMember(roomId, target, 'kick') && <button className="secondary-button" onClick={() => setAction('kick')}>Remove member</button>}{canModerateMember(roomId, target, 'ban') && <button className="secondary-button" onClick={() => setAction(banned ? 'unban' : 'ban')}>{banned ? 'Lift ban' : 'Ban member'}</button>}</div></>}
    <Dialog open={!!action} onOpenChange={open => { if (!open && !busy) { setAction(''); setReason(''); setError(''); } }}><DialogContent><DialogHeader><DialogTitle>{action === 'timeout' ? 'Timeout member?' : action === 'clear-timeout' ? 'Remove timeout?' : action === 'kick' ? 'Remove member?' : action === 'unban' ? 'Lift this ban?' : 'Ban member?'}</DialogTitle><DialogDescription>{action === 'timeout' ? 'This member cannot send messages, react or join calls until the timeout expires. They can still read the conversation.' : action === 'kick' ? 'The member will leave this conversation and may need a new invitation to return.' : action === 'ban' ? 'The member will leave and cannot rejoin until an authorized member lifts the ban.' : 'This removes the selected restriction. Existing messages and downloaded copies remain unchanged.'}</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={event => { event.preventDefault(); void submit(); }}>{action === 'timeout' && <label>Duration<select value={seconds} onChange={e => setSeconds(Number(e.target.value))}>{[[300, '5 minutes'], [3600, '1 hour'], [86400, '1 day'], [604800, '7 days'], [2419200, '28 days']].map(([seconds, label]) => <option key={seconds} value={seconds}>{label}</option>)}</select></label>}<label>Reason<input value={reason} maxLength={500} onChange={e => setReason(e.target.value)}/></label><p className="login-help">Moderation reasons are visible as room metadata to your homeserver and room members.</p><div className="inline-actions"><button className="primary-button" disabled={busy}>Confirm</button><button type="button" className="secondary-button" disabled={busy} onClick={() => setAction('')}>Cancel</button></div>{error && <p className="connect-error" role="alert">{error}</p>}</form></DialogContent></Dialog>
  </section>;
}
