import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { calendarDownload, createWork, getWork, loadWorkHistory, updateWork, type WorkItem, type WorkKind } from '@/lib/collaboration';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
export function CollaborationBoard({ roomId }: { roomId: string }) {
  const [kind,setKind]=useState<WorkKind>('task'),[items,setItems]=useState<WorkItem[]>([]),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false);
  const [title,setTitle]=useState(''),[text,setText]=useState(''),[assignee,setAssignee]=useState(''),[due,setDue]=useState(''),[options,setOptions]=useState(''),[editing,setEditing]=useState<WorkItem|null>(null),[error,setError]=useState('');
  const client=getMatrixClient(),me=client?.getUserId(),members=client?.getRoom(roomId)?.getJoinedMembers()||[];
  useEffect(()=>{let active=true;let pending=false;const refresh=async()=>{if(pending)return;pending=true;try{const r=await getWork(roomId);if(active){setItems(r.items);setMore(r.hasMore);}}catch(e){if(active)setError((e as Error).message);}finally{pending=false;}};void refresh();const off=onMatrixUpdate(()=>void refresh());return()=>{active=false;off();};},[roomId]);
  async function run(task:()=>Promise<unknown>){setBusy(true);setError('');try{await task();const r=await getWork(roomId);setItems(r.items);setMore(r.hasMore);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="collaboration-board"><header><div><h2>Work together</h2><p>Encrypted tasks, notes, events, and polls in this conversation.</p></div><button className="primary-button" disabled={!client} onClick={()=>{setCreating(!creating);setEditing(null);setTitle('');setText('');}}>New {kind}</button></header>
    <div className="work-tabs" role="group" aria-label="Collaboration type">{(['task','note','event','poll'] as WorkKind[]).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setCreating(false);setEditing(null);}}>{k==='event'?'Calendar':k[0].toUpperCase()+k.slice(1)+'s'}</button>)}</div>
    {(creating||editing)&&<form className="dialog-form work-form" onSubmit={e=>{e.preventDefault();void run(async()=>{if(editing)await updateWork(roomId,editing,'edit',{title,text});else await createWork(roomId,{kind,title,text,assignee:kind==='task'?assignee:'',due:due?new Date(due).toISOString():'',options:options.split('\n').map(x=>x.trim()).filter(Boolean)});setCreating(false);setEditing(null);setTitle('');setText('');setOptions('');});}}><label>Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{kind==='poll'?'Context':'Content'}<textarea rows={5} maxLength={16000} value={text} onChange={e=>setText(e.target.value)}/></label>{!editing&&kind==='task'&&<label>Assignee<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.userId} value={m.userId}>{m.name}</option>)}</select></label>}{!editing&&(kind==='event'||kind==='task')&&<label>{kind==='event'?'Event start (your local time)':'Due date (your local time)'}<input type="datetime-local" required={kind==='event'} value={due} onChange={e=>setDue(e.target.value)}/></label>}{kind==='poll'&&<><label>Answers, one per line<textarea rows={4} required value={options} onChange={e=>setOptions(e.target.value)}/></label><p>Votes are visible to room members. Members can change their vote until the author closes the poll.</p></>}<div className="inline-actions"><button className="primary-button" disabled={busy}>{busy?'Saving…':editing?'Save revision':'Create'}</button><button className="secondary-button" type="button" onClick={()=>{setCreating(false);setEditing(null);}}>Cancel</button></div></form>}
    {error&&<p className="connect-error" role="alert">{error}</p>}
    <div className={'work-grid '+(kind==='task'?'task-grid':'')}>{items.filter(i=>i.kind===kind).map(item=><article className="work-card" key={item.id}><small>{item.kind==='task'?item.status.toUpperCase():new Date(item.at).toLocaleDateString()} · {members.find(m=>m.userId===item.author)?.name||item.author}</small><h3>{item.title}</h3><p className="work-text">{item.text}</p>{item.assignee&&<p className="work-meta">Assigned to {members.find(m=>m.userId===item.assignee)?.name||item.assignee}</p>}{item.due&&<p className="work-meta">{new Date(item.due).toLocaleString()}</p>}
      {item.kind==='task'&&(item.author===me||item.assignee===me)&&<label>Status<select aria-label={'Status for '+item.title} disabled={busy} value={item.status} onChange={e=>void run(()=>updateWork(roomId,item,'status',{status:e.target.value}))}><option value="todo">To do</option><option value="doing">In progress</option><option value="done">Done</option></select></label>}
      {item.kind==='poll'&&<><div className="poll-options">{item.options.map((option,index)=><button key={index} disabled={busy||item.closed} aria-pressed={item.votes[me||'']===index} onClick={()=>void run(()=>updateWork(roomId,item,'vote',{choice:index}))}><span>{option}</span><strong>{Object.values(item.votes).filter(v=>v===index).length}</strong></button>)}</div><p className="work-meta">{Object.keys(item.votes).length} votes · {item.closed?'Closed':'Open'}</p>{item.author===me&&!item.closed&&<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>updateWork(roomId,item,'close'))}>Close poll</button>}</>}
      <div className="inline-actions">{item.kind==='event'&&<button className="secondary-button" onClick={()=>{try{calendarDownload(item);}catch(e){toast.error((e as Error).message);}}}>Add to calendar</button>}{item.author===me&&item.kind!=='poll'&&<button className="secondary-button" onClick={()=>{setEditing(item);setCreating(false);setTitle(item.title);setText(item.text);}}>Edit</button>}{item.author===me&&<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>updateWork(roomId,item,'archive'))}>Archive</button>}</div>
    </article>)}</div>{!items.some(i=>i.kind===kind)&&<p className="work-empty">No {kind}s in loaded history. Create one to get started.</p>}
    {more&&<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>loadWorkHistory(roomId))}>{busy?'Loading…':'Load 100 older events'}</button>}<p className="work-footnote">Based on decrypted history loaded on this device. Load older events for earlier items and votes. Content edits preserve revisions; authors control their items. Event times export to your calendar.</p>
  </section>;
}
