import {accountArtworkOwner} from '@/lib/api';
import {experienceError} from '@/lib/experience-errors';
import { TimeTogether } from './time-together';
import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { calendarDownload, pollClosed, pollSelections, createWork, getWork, loadWorkHistory, updateWork, type WorkItem, type WorkKind } from '@/lib/collaboration';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
export function CollaborationBoard({ roomId, onRemind }: { roomId: string; onRemind?: (eventId:string)=>void }) {
  const [kind,setKind]=useState<WorkKind>('task'),[items,setItems]=useState<WorkItem[]>([]),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false);
  const [title,setTitle]=useState(''),[text,setText]=useState(''),[assignee,setAssignee]=useState(''),[due,setDue]=useState(''),[options,setOptions]=useState(''),[editing,setEditing]=useState<WorkItem|null>(null),[error,setError]=useState('');
  const [multiple,setMultiple]=useState(false),[expires,setExpires]=useState(''),[,tick]=useState(0);
  useEffect(()=>{const timer=setInterval(()=>tick(value=>value+1),30000);return()=>clearInterval(timer);},[]);
  const generation=useRef(0),lock=useRef(false),owner=accountArtworkOwner();
  const client=getMatrixClient(),me=client?.getUserId(),members=client?.getRoom(roomId)?.getJoinedMembers()||[];
  useEffect(()=>{generation.current++;lock.current=false;setItems([]);setMore(false);setBusy(false);setCreating(false);setEditing(null);setError('');let active=true;let pending=false;const refresh=async()=>{if(pending)return;pending=true;try{const r=await getWork(roomId);if(active&&client===getMatrixClient()&&owner===accountArtworkOwner()){setItems(r.items);setMore(r.hasMore);}}catch(e){if(active)setError((e as Error).message);}finally{pending=false;}};void refresh();const off=onMatrixUpdate(()=>void refresh());return()=>{active=false;generation.current++;off();};},[roomId,client,owner]);
  async function run(task:(current:()=>boolean)=>Promise<unknown>){if(lock.current)return;lock.current=true;const operation=generation.current,current=()=>operation===generation.current&&client===getMatrixClient()&&owner===accountArtworkOwner();setBusy(true);setError('');try{await task(current);if(!current())return;const r=await getWork(roomId);if(current()){setItems(r.items);setMore(r.hasMore);}}catch(e){if(current())setError(experienceError(e).message);}finally{if(current()){lock.current=false;setBusy(false);}}}
  return <section className="collaboration-board"><header><div><h2>Work together</h2><p>Encrypted tasks, notes, events, and polls in this conversation.</p></div><button className="primary-button" disabled={!client} onClick={()=>{setCreating(!creating);setEditing(null);setTitle('');setText('');setDue('');setAssignee('');setOptions('');setMultiple(false);setExpires('');}}>New {kind}</button></header>
    <div className="work-tabs" role="group" aria-label="Collaboration type">{(['task','note','event','poll'] as WorkKind[]).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setCreating(false);setEditing(null);}}>{k==='event'?'Calendar':k[0].toUpperCase()+k.slice(1)+'s'}</button>)}</div>
    {(creating||editing)&&<form className="dialog-form work-form" onSubmit={e=>{e.preventDefault();void run(async(current)=>{if(editing)await updateWork(roomId,editing,'edit',{title,text});else await createWork(roomId,{kind,title,text,multiple:kind==='poll'&&multiple,closesAt:kind==='poll'&&expires?new Date(expires).getTime():0,assignee:kind==='task'?assignee:'',due:due?new Date(due).toISOString():'',options:options.split('\n').map(x=>x.trim()).filter(Boolean)});if(!current())return;setCreating(false);setEditing(null);setTitle('');setText('');setOptions('');});}}><label>Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{kind==='poll'?'Context':'Content'}<textarea rows={5} maxLength={16000} value={text} onChange={e=>setText(e.target.value)}/></label>{!editing&&kind==='task'&&<label>Assignee<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.userId} value={m.userId}>{m.name}</option>)}</select></label>}{!editing&&(kind==='event'||kind==='task')&&<label>{kind==='event'?'Event start (your local time)':'Due date (your local time)'}<input type="datetime-local" required={kind==='event'} value={due} onChange={e=>setDue(e.target.value)}/></label>}{!editing&&kind==='event'&&<TimeTogether roomId={roomId} value={due} onChange={setDue}/>}{kind==='poll'&&<><label>Answers, one per line<textarea rows={4} required value={options} onChange={e=>setOptions(e.target.value)}/></label><label className='check-label'><input type='checkbox' checked={multiple} onChange={e=>setMultiple(e.target.checked)}/>Allow multiple answers</label><label>Close poll at (optional, local time)<input type='datetime-local' value={expires} onChange={e=>setExpires(e.target.value)}/></label><p>Votes are visible to room members. Members can change their vote until the author closes the poll.</p></>}<div className="inline-actions"><button className="primary-button" disabled={busy}>{busy?'Saving…':editing?'Save revision':'Create'}</button><button className="secondary-button" type="button" onClick={()=>{setCreating(false);setEditing(null);}}>Cancel</button></div></form>}
    {error&&<p className="connect-error" role="alert">{error}</p>}
    <div className={'work-grid '+(kind==='task'?'task-grid':'')}>{items.filter(i=>i.kind===kind).map(item=><article className="work-card" key={item.id}><small>{item.kind==='task'?item.status.toUpperCase():new Date(item.at).toLocaleDateString()} · {members.find(m=>m.userId===item.author)?.name||item.author}</small><h3>{item.title}</h3><p className="work-text">{item.text}</p>{item.assignee&&<p className="work-meta">Assigned to {members.find(m=>m.userId===item.assignee)?.name||item.assignee}</p>}{item.due&&<p className="work-meta">{new Date(item.due).toLocaleString()}</p>}
      {item.kind==='task'&&(item.author===me||item.assignee===me)&&<label>Status<select aria-label={'Status for '+item.title} disabled={busy} value={item.status} onChange={e=>void run(()=>updateWork(roomId,item,'status',{status:e.target.value}))}><option value="todo">To do</option><option value="doing">In progress</option><option value="done">Done</option></select></label>}
      {item.kind==='poll'&&<><div className="poll-options">{item.options.map((option,index)=><button key={index} disabled={busy||pollClosed(item)} aria-pressed={pollSelections(item,me||'').includes(index)} onClick={()=>void run(()=>updateWork(roomId,item,'vote',item.multiple?{choices:pollSelections(item,me||'').includes(index)?pollSelections(item,me||'').filter(choice=>choice!==index):[...pollSelections(item,me||''),index]}:{choice:index}))}><span>{option}</span><strong>{Object.keys(item.votes).filter(user=>pollSelections(item,user).includes(index)).length}</strong></button>)}</div><p className="work-meta">{Object.keys(item.votes).length} votes · {pollClosed(item)?'Closed':item.multiple?'Open · Select all that apply':'Open · Choose one'}{item.closesAt?' · Closes '+new Date(item.closesAt).toLocaleString():''}</p>{item.author===me&&!pollClosed(item)&&<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>updateWork(roomId,item,'close'))}>Close poll</button>}</>}
      {item.kind==='event'&&<div className="event-rsvp" aria-label={'Respond to '+item.title}><div className="product-actions">{(['going','maybe','declined'] as const).map(response=><button key={response} className="secondary-button" disabled={busy} aria-pressed={item.rsvps?.[me||'']===response} onClick={()=>void run(()=>updateWork(roomId,item,'rsvp',{response}))}>{response==='going'?'Going':response==='maybe'?'Maybe':'Cannot go'} ({Object.values(item.rsvps||{}).filter(value=>value===response).length})</button>)}</div><p className="login-help">Responses are visible to this conversation. You can change yours.</p>{onRemind&&<button className="secondary-button" onClick={()=>onRemind(item.id)}>Remind me</button>}</div>}
      <div className="inline-actions">{item.kind==='event'&&<button className="secondary-button" onClick={()=>{try{calendarDownload(item);}catch(e){toast.error((e as Error).message);}}}>Add to calendar</button>}{item.author===me&&item.kind!=='poll'&&<button className="secondary-button" onClick={()=>{setEditing(item);setCreating(false);setTitle(item.title);setText(item.text);}}>Edit</button>}{item.author===me&&<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>updateWork(roomId,item,'archive'))}>Archive</button>}</div>
    </article>)}</div>{!items.some(i=>i.kind===kind)&&<p className="work-empty">No {kind}s in loaded history. Create one to get started.</p>}
    {more&&<button className="secondary-button" disabled={busy} onClick={()=>void run(()=>loadWorkHistory(roomId))}>{busy?'Loading…':'Load 100 older events'}</button>}<p className="work-footnote">Based on decrypted history loaded on this device. Load older events for earlier items and votes. Content edits preserve revisions; authors control their items. Event times export to your calendar.</p>
  </section>;
}
