import { useEffect, useRef, useState } from 'react';
import { Hash, MessageCircle, Plus, Search, Settings, Users } from 'lucide-react';
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator } from '@/components/ui/command';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { getMatrixClient } from '@/lib/matrix';
const eventName = 'tavern:command-palette';
export function openCommandPalette(mode: 'switcher' | 'commands' = 'switcher') { window.dispatchEvent(new CustomEvent(eventName, { detail: mode })); }
export function CommandPalette({ onSelectRoom, onSelectServer, onSettings, onSearch, onCreate, onContacts }: { onSelectRoom: (id: string) => void; onSelectServer: (id: string) => void; onSettings: (tab?: string) => void; onSearch: () => void; onCreate?: () => void; onContacts?: () => void }) {
  const [open, setOpen] = useState(false), [mode, setMode] = useState('switcher'), [query, setQuery] = useState(''), returnFocus = useRef<HTMLElement | null>(null);
  useEffect(() => { const show = (mode: string) => { if (!document.querySelector('[data-slot="command-input"]')) returnFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setMode(mode); setQuery(''); setOpen(true); }; const event = (event: Event) => show((event as CustomEvent).detail || 'switcher'); const key = (event: KeyboardEvent) => { if (!(event.ctrlKey || event.metaKey) || event.altKey) return; if (event.key.toLowerCase() === 'k') { event.preventDefault(); event.stopPropagation(); show('switcher'); } else if (event.shiftKey && event.key.toLowerCase() === 'p') { event.preventDefault(); event.stopPropagation(); show('commands'); } }; window.addEventListener(eventName, event); window.addEventListener('keydown', key, true); return () => { window.removeEventListener(eventName, event); window.removeEventListener('keydown', key, true); }; }, []);
  const run = (fn: () => void) => { setOpen(false); fn(); }, client = getMatrixClient(), rooms = open ? client?.getRooms().filter(r => r.getMyMembership() === 'join') || [] : [], search = query.toLocaleLowerCase().replace(/^[#@]/, ''), matches = rooms.filter(r => (r.name + ' ' + r.roomId).toLocaleLowerCase().includes(search)).slice(0, 60);
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="tavern-command-dialog" onCloseAutoFocus={event => { event.preventDefault(); if (returnFocus.current?.isConnected) returnFocus.current.focus(); }}><DialogHeader className="sr-only"><DialogTitle>{mode === 'switcher' ? 'Switch conversation' : 'Tavern commands'}</DialogTitle><DialogDescription>Type to search. Use arrow keys to choose and Enter to open. Escape closes this menu.</DialogDescription></DialogHeader><Command shouldFilter={false}><CommandInput value={query} onValueChange={setQuery} placeholder={mode === 'switcher' ? 'Find a channel, server, or conversation…' : 'Find a command…'} aria-label="Search Tavern commands and conversations" /><CommandList><CommandEmpty>No matching conversations or commands.</CommandEmpty>{mode === 'switcher' && <><CommandGroup heading="Conversations">{matches.filter(r => !r.isSpaceRoom()).map(r => <CommandItem key={r.roomId} value={r.roomId} onSelect={() => run(() => onSelectRoom(r.roomId))}><Hash size={17} /><span>{r.name}</span></CommandItem>)}</CommandGroup><CommandGroup heading="Servers">{matches.filter(r => r.isSpaceRoom()).map(r => <CommandItem key={r.roomId} value={r.roomId} onSelect={() => run(() => onSelectServer(r.roomId))}><Users size={17} /><span>{r.name}</span></CommandItem>)}</CommandGroup><CommandSeparator /></>}<CommandGroup heading="Commands">{[{ id: 'search', name: 'Search messages', icon: <Search size={17} />, run: onSearch }, { id: 'profile', name: 'Edit your profile', icon: <MessageCircle size={17} />, run: () => onSettings('profile') }, { id: 'security', name: 'Security and devices', icon: <Settings size={17} />, run: () => onSettings('privacy') }, { id: 'appearance', name: 'Appearance and theme', icon: <Settings size={17} />, run: () => onSettings('appearance') }, ...(onCreate ? [{ id: 'create', name: 'Create a channel', icon: <Plus size={17} />, run: onCreate }] : []), ...(onContacts ? [{ id: 'contacts', name: 'Open contacts', icon: <Users size={17} />, run: onContacts }] : [])].filter(item => !query || item.name.toLocaleLowerCase().includes(search)).map(item => <CommandItem key={item.id} value={item.id} onSelect={() => run(item.run)}>{item.icon}<span>{item.name}</span></CommandItem>)}</CommandGroup></CommandList></Command><div className="community-command-hint"><span>↑ ↓ Navigate · Enter Open · Esc Close</span><span>{mode === 'switcher' ? 'Ctrl K' : 'Ctrl Shift P'}</span></div></DialogContent></Dialog>;
}
