import { useEffect, useMemo, useState } from 'react';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
import { readServerEmoji, type ServerEmoji } from '@/lib/server-emoji';
import { applyEmojiTone, emojiTones, readEmojiPreferences, recordEmojiUse, saveEmojiPreferences, toggleFavoriteEmoji, type EmojiPreferences } from '@/lib/emoji-preferences';
import { ActionMenu } from './action-menu';
import { CommunityImage } from './community-settings';
const groups: Record<string, string> = { Smileys: '😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉 😌 😍 🥰 😘 😋 😛 😎 🤩 🥳 😏 😒 😔 😢 😭 😤 😡 🤯 🥺 😴 🤔 🤫 🤗 🫡', People: '👋 🤚 ✋ 🖖 👌 🤌 ✌️ 🤞 🤟 🤘 🤙 👈 👉 👆 👇 👍 👎 ✊ 👊 👏 🙌 👐 🤝 🙏 💪 👀 🧠', Nature: '🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐸 🐷 🦁 🐯 🐨 🐵 🦄 🐝 🦋 🌸 🌹 🌻 🌲 🌴 🌵 🍀 🌎 ☀️ 🌙 ⭐ 🌈 🔥 ❄️ 🌊', Food: '🍎 🍌 🍇 🍓 🍒 🍉 🥑 🥦 🍔 🍕 🍟 🌮 🍜 🍣 🍪 🍰 🍫 🍿 ☕ 🍵 🧋 🍺 🍻 🥂', Activities: '⚽ 🏀 🏈 ⚾ 🎾 🎱 🏓 🥊 🏆 🥇 🎮 🎲 🎯 🎸 🎹 🎤 🎨 🎬 🎧', Travel: '🚗 🚕 🚌 🚎 🚲 🏍️ ✈️ 🚀 🚁 🚢 🚂 🏠 🏡 🏰 🏕️ 🏖️ 🏔️ 🌋 🗺️', Objects: '💡 🔦 🔧 🔨 🛠️ ⚙️ 💻 📱 ⌨️ 🖥️ 📷 📺 💰 💎 📚 📖 📝 📌 📎 🔑 🔒 🎁 🎉 🎊', Symbols: '❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 💕 💯 ✅ ❌ ⚠️ ⛔ ❓ ❗ ♻️ ➕ ➖ ➡️ ⬅️ ⬆️ ⬇️ 🔔 🔕', Flags: '🏳️ 🏴 🏁 🚩 🏳️‍🌈 🏳️‍⚧️ 🇺🇸 🇨🇦 🇬🇧 🇫🇷 🇩🇪 🇯🇵 🇦🇺 🇧🇷 🇮🇳 🇺🇦' };
const names: Record<string, string> = { '👍': 'thumbs up like yes', '👎': 'thumbs down dislike no', '❤️': 'heart love', '😂': 'laugh tears joy', '🎉': 'party celebration', '🔥': 'fire hot', '✅': 'check done yes', '👀': 'eyes looking', '🚀': 'rocket launch', '👋': 'wave hello', '🤔': 'thinking', '🙏': 'pray thanks', '💡': 'idea light', '🍺': 'beer tavern', '🎮': 'game controller' };
type Choice = { value: string; label: string; category: string; custom?: ServerEmoji };
export function EmojiPicker({ onSelect, serverId, onSelectCustom }: { onSelect: (emoji: string) => void; serverId?: string; onSelectCustom?: (emoji: ServerEmoji) => void }) {
  const user = getMatrixClient()?.getUserId() || '', [preferences, setPreferences] = useState(() => readEmojiPreferences(user)), [query, setQuery] = useState(''), [category, setCategory] = useState(() => readEmojiPreferences(user).recent.length ? 'Frequently Used' : 'Smileys'), [managing, setManaging] = useState(false), [, redraw] = useState(0);
  useEffect(() => { setPreferences(readEmojiPreferences(user)); return onMatrixUpdate(() => redraw(v => v + 1)); }, [user]);
  const custom = readServerEmoji(serverId), customKey = custom.map(emoji => emoji.name + emoji.uri).join(' ');
  const inventory = useMemo(() => { const choices: Choice[] = Object.entries(groups).flatMap(([group, values]) => values.split(' ').map(emoji => ({ value: emoji, label: names[emoji] || emoji, category: group }))); return [...choices, ...custom.map(emoji => ({ value: emoji.uri, label: ':' + emoji.name + ':', category: 'Server', custom: emoji }))]; }, [customKey]);
  const byValue = useMemo(() => { const result = new Map<string, Choice>(); for (const choice of inventory) { result.set(choice.value, choice); if (!choice.custom) for (const tone of emojiTones) { const value = applyEmojiTone(choice.value, tone); result.set(value, { ...choice, value }); } } return result; }, [inventory]);
  const options = useMemo(() => { if (query.trim()) { const term = query.trim().toLocaleLowerCase(); return inventory.filter(choice => (choice.label + ' ' + choice.category + ' ' + choice.value).toLocaleLowerCase().includes(term)); } if (category === 'Recent' || category === 'Favorites' || category === 'Frequently Used') { const ids = category === 'Recent' ? preferences.recent : category === 'Favorites' ? preferences.favorites : [...new Set([...Object.keys(preferences.counts).sort((a, b) => preferences.counts[b] - preferences.counts[a]), ...preferences.recent])].slice(0, 32); return ids.map(id => byValue.get(id)).filter((choice): choice is Choice => !!choice); } return inventory.filter(choice => choice.category === category); }, [query, category, inventory, byValue, preferences]);
  function persist(next: EmojiPreferences) { setPreferences(saveEmojiPreferences(next, user)); }
  function valueFor(choice: Choice) { return choice.custom || ['Recent', 'Favorites', 'Frequently Used'].includes(category) && !query ? choice.value : applyEmojiTone(choice.value, preferences.tone); }
  function favorite(choice: Choice) { persist(toggleFavoriteEmoji(preferences, valueFor(choice))); }
  function choose(choice: Choice) { if (managing) { favorite(choice); return; } const value = valueFor(choice); persist(recordEmojiUse(preferences, value)); if (choice.custom) { if (onSelectCustom) onSelectCustom(choice.custom); else onSelect(':' + choice.custom.name + ':'); } else onSelect(value); }
  const categories = ['Frequently Used', 'Recent', 'Favorites', ...(serverId ? ['Server'] : []), ...Object.keys(groups)];
  return <section className="tavern-emoji-picker" aria-label="Emoji picker"><input autoFocus type="search" placeholder="Search emoji or category" value={query} onChange={e => setQuery(e.target.value)} aria-label="Search emoji" /><div className="emoji-categories">{categories.map(group => <button key={group} type="button" aria-pressed={category === group} onClick={() => { setCategory(group); setQuery(''); }}>{group}</button>)}</div><div className="emoji-picker-tools"><label>Skin tone<select aria-label="Emoji skin tone" value={preferences.tone} onChange={e => persist({ ...preferences, tone: e.target.value })}>{emojiTones.map((tone, i) => <option key={tone} value={tone}>{['Default', 'Light', 'Medium light', 'Medium', 'Medium dark', 'Dark'][i]} {tone}</option>)}</select></label><button type="button" aria-pressed={managing} onClick={() => setManaging(value => !value)}>{managing ? 'Done with favorites' : 'Edit favorites'}</button></div>{managing && <p className="emoji-picker-help">Choose emoji to add or remove favorites.</p>}<div className="emoji-grid" onKeyDown={e => { const offset = ({ ArrowRight: 1, ArrowLeft: -1, ArrowDown: 8, ArrowUp: -8 } as Record<string, number>)[e.key]; if (offset) { const buttons = Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('[data-emoji-choice]')); const current = buttons.indexOf(document.activeElement as HTMLButtonElement); e.preventDefault(); buttons[Math.max(0, Math.min(buttons.length - 1, current + offset))]?.focus(); } }}>{options.map(choice => { const value = valueFor(choice), starred = preferences.favorites.includes(value); return <ActionMenu key={choice.value} actions={[{ label: starred ? 'Remove emoji favorite' : 'Favorite emoji', run: () => favorite(choice) }]}><button data-emoji-choice type="button" className={starred ? 'emoji-is-favorite' : ''} title={choice.label} aria-label={choice.label + (managing ? starred ? ' — remove favorite' : ' — add favorite' : '')} aria-pressed={managing ? starred : undefined} onClick={() => choose(choice)}>{choice.custom ? <CommunityImage mxc={choice.custom.uri} name={choice.label} size={24} /> : value}</button></ActionMenu>; })}</div>{!options.length && <p>{query ? 'No matching emoji.' : category === 'Server' ? 'This server has no custom emoji yet.' : category === 'Favorites' ? 'Use Edit favorites to choose your favorites.' : 'Emoji you use will appear here.'}</p>}<small className="emoji-picker-help">Recent emoji and favorites are saved on this device.</small></section>;
}