import { useMemo, useState } from 'react';
const groups: Record<string, string> = { Smileys: '😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉 😌 😍 🥰 😘 😋 😛 😎 🤩 🥳 😏 😒 😔 😢 😭 😤 😡 🤯 🥺 😴 🤔 🤫 🤗 🫡', People: '👋 🤚 ✋ 🖖 👌 🤌 ✌️ 🤞 🤟 🤘 🤙 👈 👉 👆 👇 👍 👎 ✊ 👊 👏 🙌 👐 🤝 🙏 💪 👀 🧠', Nature: '🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐸 🐷 🦁 🐯 🐨 🐵 🦄 🐝 🦋 🌸 🌹 🌻 🌲 🌴 🌵 🍀 🌎 ☀️ 🌙 ⭐ 🌈 🔥 ❄️ 🌊', Food: '🍎 🍌 🍇 🍓 🍒 🍉 🥑 🥦 🍔 🍕 🍟 🌮 🍜 🍣 🍪 🍰 🍫 🍿 ☕ 🍵 🧋 🍺 🍻 🥂', Activities: '⚽ 🏀 🏈 ⚾ 🎾 🎱 🏓 🥊 🏆 🥇 🎮 🎲 🎯 🎸 🎹 🎤 🎨 🎬 🎧', Travel: '🚗 🚕 🚌 🚎 🚲 🏍️ ✈️ 🚀 🚁 🚢 🚂 🏠 🏡 🏰 🏕️ 🏖️ 🏔️ 🌋 🗺️', Objects: '💡 🔦 🔧 🔨 🛠️ ⚙️ 💻 📱 ⌨️ 🖥️ 📷 📺 💰 💎 📚 📖 📝 📌 📎 🔑 🔒 🎁 🎉 🎊', Symbols: '❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 💕 💯 ✅ ❌ ⚠️ ⛔ ❓ ❗ ♻️ ➕ ➖ ➡️ ⬅️ ⬆️ ⬇️ 🔔 🔕', Flags: '🏳️ 🏴 🏁 🚩 🏳️‍🌈 🏳️‍⚧️ 🇺🇸 🇨🇦 🇬🇧 🇫🇷 🇩🇪 🇯🇵 🇦🇺 🇧🇷 🇮🇳 🇺🇦' };
const names: Record<string, string> = { '👍': 'thumbs up like yes', '👎': 'thumbs down dislike no', '❤️': 'heart love', '😂': 'laugh tears joy', '🎉': 'party celebration', '🔥': 'fire hot', '✅': 'check done yes', '👀': 'eyes looking', '🚀': 'rocket launch', '👋': 'wave hello', '🤔': 'thinking', '🙏': 'pray thanks', '💡': 'idea light', '🍺': 'beer tavern', '🎮': 'game controller' };
function recent(): string[] { try { return JSON.parse(localStorage.getItem('tavern.emoji.recent') || '[]').filter((v: any) => typeof v === 'string').slice(0, 24); } catch { return []; } }
export function EmojiPicker({ onSelect }: { onSelect: (emoji: string) => void }) {
  const [query, setQuery] = useState(''), [category, setCategory] = useState('Recent');
  const options = useMemo(() => query ? Object.entries(groups).flatMap(([g, s]) => s.split(' ').filter(e => (g + ' ' + (names[e] || '') + ' ' + e).toLowerCase().includes(query.toLowerCase()))) : category === 'Recent' ? recent() : groups[category].split(' '), [query, category]);
  function choose(e: string) { try { localStorage.setItem('tavern.emoji.recent', JSON.stringify([e, ...recent().filter(v => v !== e)].slice(0, 24))); } catch {} onSelect(e); }
  return <section className="tavern-emoji-picker" aria-label="Emoji picker"><input autoFocus type="search" placeholder="Search emoji or category" value={query} onChange={e => setQuery(e.target.value)} aria-label="Search emoji"/><div className="emoji-categories">{['Recent', ...Object.keys(groups)].map(g => <button key={g} type="button" aria-pressed={category === g} onClick={() => { setCategory(g); setQuery(''); }}>{g}</button>)}</div><div className="emoji-grid" onKeyDown={e => { const offset = ({ ArrowRight: 1, ArrowLeft: -1, ArrowDown: 8, ArrowUp: -8 } as Record<string, number>)[e.key]; if (offset) { const buttons = Array.from(e.currentTarget.querySelectorAll('button')); const current = buttons.indexOf(document.activeElement as HTMLButtonElement); e.preventDefault(); buttons[Math.max(0, Math.min(buttons.length - 1, current + offset))]?.focus(); } }}>{options.map(e => <button key={e} type="button" title={names[e] || e} aria-label={names[e] || e} onClick={() => choose(e)}>{e}</button>)}</div>{!options.length && <p>{query ? 'No matching emoji.' : 'Emoji you use will appear here.'}</p>}</section>;
}
