import { useEffect, useState } from 'react';
import { accountSignedOut, requestApi } from '@/lib/api';
import { Field } from './auth-gateway';
export function ForcedPasswordChange({ onComplete }: { onComplete: () => Promise<unknown> }) {
  const [security, setSecurity] = useState<any>(null), [currentPassword, setCurrentPassword] = useState(''), [newPassword, setNewPassword] = useState(''), [confirmation, setConfirmation] = useState('');
  const [method, setMethod] = useState('totp'), [code, setCode] = useState(''), [challengeId, setChallengeId] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  async function load() { setError(''); try { const value = await requestApi('/account/security'); setSecurity(value); setMethod(value.totpEnabled ? 'totp' : 'email'); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); }, []);
  async function change() { setBusy(true); setError(''); try { await requestApi('/account/password', { currentPassword, newPassword, confirmation, logoutOtherDevices: true, method, code, challengeId }); setCurrentPassword(''); setNewPassword(''); setConfirmation(''); setCode(''); await onComplete(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function emailCode() { setBusy(true); setError(''); try { const value = await requestApi('/account/security/email-code', { password: currentPassword }); setChallengeId(value.challengeId); setNotice('Check your email for the security code.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function signOut() { setBusy(true); setError(''); try { await requestApi('/auth/logout', {}); accountSignedOut(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <main className='auth-shell'><section className='auth-card'><h1>Choose a new password</h1><p>Your administrator requires a password change before you can continue.</p>{!security ? <button className='secondary-button' onClick={() => void load()}>Load security settings</button> : <form className='dialog-form' onSubmit={event => { event.preventDefault(); void change(); }}><fieldset disabled={busy}>
    <Field label='Current password'><input type='password' autoComplete='current-password' required value={currentPassword} onChange={e => setCurrentPassword(e.target.value)}/></Field>
    <Field label='New password'><input type='password' autoComplete='new-password' required minLength={12} value={newPassword} onChange={e => setNewPassword(e.target.value)}/></Field>
    <Field label='Confirm new password'><input type='password' autoComplete='new-password' required minLength={12} value={confirmation} onChange={e => setConfirmation(e.target.value)}/></Field>
    {(security.totpEnabled || security.emailMfaEnabled) && <><Field label='Verification method'><select value={method} onChange={e => { setMethod(e.target.value); setCode(''); }}>{security.totpEnabled && <option value='totp'>Authenticator app</option>}{security.emailMfaEnabled && <option value='email'>Email code</option>}<option value='recovery'>Recovery code</option></select></Field>{method === 'email' && <button type='button' className='secondary-button' onClick={() => void emailCode()}>Send verification code</button>}<Field label='Verification code'><input autoComplete='one-time-code' required value={code} onChange={e => setCode(e.target.value)}/></Field></>}
    <button className='primary-button'>Change password and continue</button></fieldset><p>Your encryption recovery key stays the same. Other devices will be signed out.</p></form>}<button className='text-button' disabled={busy} onClick={() => void signOut()}>Sign out</button>{error && <p className='connect-error' role='alert'>{error}</p>}{notice && <p role='status'>{notice}</p>}</section></main>;
}
