import { useState } from 'react';
import { matrixApi, getMatrixClient } from '@/lib/matrix';
import { postingRestriction } from '@/lib/channel-policy';
import { messagePermissions } from '@/lib/interactions';
import { readThreadPolicy, threadReplyRestriction } from '@/lib/thread-policy';
import { Field } from './auth-gateway';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { toast } from 'sonner';
export function ForumChannel({ roomId, messages, onOpen, onSent }: { roomId: string; messages: any[]; onOpen: (m: any) => void; onSent: () => Promise<unknown> }) {
  const [query, setQuery] = useState(''), [sort, setSort] = useState('activity'), [tag, setTag] = useState(''), [status, setStatus] = useState('all'), [creating, setCreating] = useState(false), [title, setTitle] = useState(''), [body, setBody] = useState(''), [tags, setTags] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const posts = messages.filter(m => !m.parent_id).map(m=>{const policy=readThreadPolicy(roomId,m.id);return {...m,forum:{title:policy.title||m.forum?.title,tags:policy.updatedAt?policy.tags:m.forum?.tags},restriction:threadReplyRestriction(roomId,m.id,m.lastActivity)};}), allTags = [...new Set(posts.flatMap(m => m.forum?.tags || []))] as string[];
  const filtered = posts.filter(m => (status==='all'||(status==='open'?!m.restriction:!!m.restriction)) && (!tag || m.forum?.tags?.includes(tag)) && (!query || (m.body + ' ' + (m.forum?.title || '')).toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a, b) => b.pinned - a.pinned || (sort === 'replies' ? b.replies - a.replies : sort === 'oldest' ? a.created_at - b.created_at : (b.lastActivity || b.created_at) - (a.lastActivity || a.created_at)));
  const restriction = postingRestriction(roomId), canPost = messagePermissions(roomId, getMatrixClient()?.getUserId() || '').send && !restriction;
  return <section className="forum-channel"><div className="product-actions"><input type="search" aria-label="Search forum posts" placeholder="Find a discussion" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="Filter forum tag" value={tag} onChange={e => setTag(e.target.value)}><option value="">All tags</option>{allTags.map(t => <option key={t}>{t}</option>)}</select><select aria-label="Discussion status" value={status} onChange={e=>setStatus(e.target.value)}><option value='all'>All discussions</option><option value='open'>Open</option><option value='closed'>Closed or archived</option></select><select aria-label="Sort forum posts" value={sort} onChange={e => setSort(e.target.value)}><option value="activity">Latest activity</option><option value="replies">Most replies</option><option value="oldest">Oldest first</option></select>{canPost && <button className="primary-button" onClick={() => setCreating(true)}>New discussion</button>}</div>{restriction && <p>{restriction}</p>}{filtered.map(m => <button className="forum-post" key={m.id} onClick={() => onOpen(m)}><h3>{m.pinned ? '📌 ' : ''}{m.forum?.title || m.body.split('\n')[0].slice(0, 120)}</h3><p>{m.body.slice(0, 220)}</p><div>{m.forum?.tags?.map((t: string) => <span className="forum-tag" key={t}>{t}</span>)}</div>{m.restriction&&<p className='composer-restriction'>{m.restriction}</p>}<small>{m.author_name} · {m.replies} replies · {new Date(m.created_at).toLocaleDateString()}</small></button>)}{!filtered.length && <p>No discussions match this view. {canPost ? 'Start a discussion to get things going.' : ''}</p>}<Dialog open={creating} onOpenChange={open => { if (!busy) setCreating(open); }}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Start a discussion</DialogTitle><DialogDescription>Replies stay together in a thread.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await matrixApi('send', { conversation: roomId, body, forum: { title: title.trim(), tags: [...new Set(tags.split(',').map(t => t.trim()).filter(Boolean))].slice(0, 10) }, nonce: crypto.randomUUID() }); setCreating(false); setTitle(''); setBody(''); setTags(''); await onSent(); toast.success('Discussion posted'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}><Field label="Title"><input required maxLength={120} value={title} onChange={e => setTitle(e.target.value)}/></Field><Field label="Post"><textarea required maxLength={8000} value={body} onChange={e => setBody(e.target.value)}/></Field><Field label="Tags (comma separated)"><input maxLength={300} value={tags} onChange={e => setTags(e.target.value)}/></Field>{error && <p className="connect-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>Post discussion</button></form></DialogContent></Dialog></section>;
}
