import { useEffect, useState } from 'react';
import { requestApi, type AccountSession } from '@/lib/api';
import { Field } from './auth-gateway';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

export type InstanceBrand = { name?: string; description?: string; contact?: string; termsUrl?: string; privacyUrl?: string; icon?: string; logo?: string; background?: string; revision?: string; unusedAssets?: string[] };
import { brandingAsset } from '@/lib/branding';
export { brandingAsset } from '@/lib/branding';

export function InstanceBranding({ session }: { session: AccountSession }) {
  const [value, setValue] = useState<InstanceBrand | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [cleanup, setCleanup] = useState(false), [confirmation, setConfirmation] = useState('');
  const unused = (value?.unusedAssets || []).filter(asset => ![value?.icon, value?.logo, value?.background].includes(asset));
  async function load() { setBusy(true); setError(''); try { setValue(await requestApi('/admin/branding')); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function upload(slot: 'icon' | 'logo' | 'background', file?: File) {
    if (!file) return; setBusy(true); setError(''); setNotice('');
    try {
      if (file.size > 2 * 1024 * 1024) throw new Error('Choose an image smaller than 2 MiB.');
      const response = await fetch('/api/admin/branding/assets/' + slot, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': file.type || 'application/octet-stream', 'X-Tavern-Device': session.deviceId }, body: file, signal: AbortSignal.timeout(45000) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error || 'The image could not be uploaded.');
      setValue(previous => ({ ...previous, [slot]: result.url, unusedAssets: [...new Set([...(previous?.unusedAssets || []), result.url])] })); setNotice('Image uploaded. Save branding to publish this selection.');
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <section className='product-section'><h2>Instance branding</h2><p>Give your community its own identity. Tavern remains the product name.</p>
    {!value ? <button className='secondary-button' disabled={busy} onClick={() => void load()}>Load branding</button> : <form className='dialog-form' onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); setNotice(''); try { setValue(await requestApi('/admin/branding', value, 'PUT')); setNotice('Branding saved. Reload Tavern to apply it to the login screen and favicon.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><fieldset disabled={busy}>
      {(['name', 'description', 'contact', 'termsUrl', 'privacyUrl'] as const).map(key => <Field key={key} label={{ name: 'Instance name', description: 'Description', contact: 'Administrator contact', termsUrl: 'Terms URL', privacyUrl: 'Privacy URL' }[key]}><input required={key === 'name'} type={key.endsWith('Url') ? 'url' : 'text'} maxLength={key === 'name' ? 80 : key === 'description' ? 500 : key.endsWith('Url') ? 2048 : 254} value={value[key] || ''} onChange={event => setValue({ ...value, [key]: event.target.value })}/></Field>)}
      {(['icon', 'logo', 'background'] as const).map(slot => <fieldset key={slot}><legend>{slot === 'icon' ? 'Icon and favicon' : slot === 'logo' ? 'Login logo' : 'Login background'}</legend>{brandingAsset(value[slot]) && <img src={brandingAsset(value[slot])} alt={slot + ' preview'} style={{ maxWidth: '240px', maxHeight: '120px', objectFit: 'contain' }}/>}<label className='auth-field'>Upload {slot}<input type='file' accept='image/png,image/jpeg,image/webp' onChange={event => { void upload(slot, event.target.files?.[0]); event.target.value = ''; }}/></label>{value[slot] && <button type='button' className='text-button' onClick={() => setValue({ ...value, [slot]: '' })}>Remove {slot}</button>}</fieldset>)}
      <p>Use still PNG, JPEG, or WebP images under 2 MiB. Uploaded images are resized and metadata is removed. Branding assets are public.</p><div className='product-actions'><button className='primary-button'>Save branding</button><button type='button' className='secondary-button' onClick={() => void load()}>Reload saved branding</button></div>
    </fieldset></form>}{!!unused.length && <button className='secondary-button' disabled={busy} onClick={() => { setConfirmation(''); setCleanup(true); }}>Remove unused branding images ({unused.length})</button>}{error && <p className='connect-error' role='alert'>{error}</p>}{notice && <p role='status'>{notice}</p>}
    <Dialog open={cleanup} onOpenChange={open => { if (!busy) setCleanup(open); }}><DialogContent><DialogHeader><DialogTitle>Remove unused branding images?</DialogTitle><DialogDescription>Remove {unused.length} images that are neither published nor selected in this form. Other administrators may have unsaved selections using these images.</DialogDescription></DialogHeader><Field label='Type DELETE UNUSED to confirm'><input value={confirmation} onChange={event => setConfirmation(event.target.value)} autoComplete='off'/></Field><button className='primary-button' disabled={busy || confirmation !== 'DELETE UNUSED'} onClick={() => { setBusy(true); setError(''); void requestApi<InstanceBrand>('/admin/branding/cleanup', { assets: unused, confirmation }).then(result => { setValue(previous => ({ ...previous, unusedAssets: result.unusedAssets })); setCleanup(false); setNotice('Unused branding images removed. Your form entries are preserved.'); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }}>Remove images</button>{error && <p role='alert'>{error}</p>}</DialogContent></Dialog>
  </section>;
}

type SecurityPolicy = { revision: string; minimumPasswordLength: number; sessionHours: number; persistentDays: number; loginPerIpPerMinute: number; loginPerAccountPerFiveMinutes: number; mfaRequirement: string; registrationMode: string; emailVerificationRequired: boolean; deployment: { allowedOrigin: string; trustedProxyCidrs: string; uploadValidation: string } };
export function AdminSecurityPolicy() {
  const [value, setValue] = useState<SecurityPolicy | null>(null), [methods, setMethods] = useState<any>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [password, setPassword] = useState(''), [method, setMethod] = useState('totp'), [code, setCode] = useState(''), [challengeId, setChallengeId] = useState('');
  async function load() { setBusy(true); setError(''); try { const [settings, security] = await Promise.all([requestApi<SecurityPolicy>('/admin/security-policy'), requestApi('/account/security')]); setValue(settings); setMethods(security); setMethod(security.totpEnabled ? 'totp' : security.emailMfaEnabled ? 'email' : 'totp'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  const mfa = methods?.totpEnabled || methods?.emailMfaEnabled;
  return <section className='product-section'><h2>Account security policy</h2>{!value ? <button className='secondary-button' disabled={busy} onClick={() => void load()}>Load security policy</button> : <form className='dialog-form' onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await requestApi('/admin/security-policy', { revision: value.revision, settings: value, password, method, code, challengeId }, 'PUT'); setPassword(''); setCode(''); window.location.reload(); } catch (e) { setError((e as Error).message); setBusy(false); } }}><fieldset disabled={busy}>
    <Field label='Account registration'><select value={value.registrationMode} onChange={event => setValue({ ...value, registrationMode: event.target.value })}><option value='admin'>Administrator-created accounts</option><option value='invite'>Invitation required</option><option value='open'>Open registration</option><option value='disabled'>Account creation disabled</option></select></Field><p>People creating their own accounts must verify their email address. Working email delivery is required.</p>
    <Field label='Require two-step verification'><select value={value.mfaRequirement} onChange={event => setValue({ ...value, mfaRequirement: event.target.value })}><option value='off'>Optional</option><option value='admins'>Instance administrators</option><option value='everyone'>Everyone</option></select></Field><p>People who need to enroll can only use account setup until they enable a verification method. Your session will reload after saving.</p>
    {([['minimumPasswordLength', 'Minimum password length', 12, 128], ['sessionHours', 'Session duration (hours)', 1, 72], ['persistentDays', 'Remembered login duration (days)', 1, 90], ['loginPerIpPerMinute', 'Login attempts per IP per minute', 5, 100], ['loginPerAccountPerFiveMinutes', 'Login attempts per account per five minutes', 3, 30]] as const).map(([field, label, min, max]) => <Field key={field} label={label}><input required type='number' min={min} max={max} value={value[field]} onChange={event => setValue({ ...value, [field]: Number(event.target.value) })}/></Field>)}
    <p>Password rules apply to new and changed passwords. Shorter session limits also expire older sessions; longer limits apply to new sessions.</p><Field label='Current administrator password'><input required type='password' autoComplete='current-password' value={password} onChange={event => setPassword(event.target.value)}/></Field>
    {mfa && <><Field label='Verification method'><select value={method} onChange={event => { setMethod(event.target.value); setCode(''); }}>{methods.totpEnabled && <option value='totp'>Authenticator</option>}{methods.emailMfaEnabled && <option value='email'>Email</option>}<option value='recovery'>Recovery code</option></select></Field>{method === 'email' && <button type='button' className='secondary-button' onClick={() => { setBusy(true); void requestApi('/account/security/email-code', { password }).then(result => setChallengeId(result.challengeId)).catch(e => setError(e.message)).finally(() => setBusy(false)); }}>Send administrator verification code</button>}<Field label='Verification code'><input required autoComplete='one-time-code' value={code} onChange={event => setCode(event.target.value)}/></Field></>}
    <div className='product-actions'><button className='primary-button'>Save security policy</button><button type='button' className='secondary-button' onClick={() => void load()}>Reload saved security policy</button></div>
    </fieldset><h3>Deployment trust and upload controls</h3><p>Allowed origin: <code>{value.deployment.allowedOrigin}</code><br/>Trusted proxy networks: <code>{value.deployment.trustedProxyCidrs || 'None'}</code></p><p>These trust settings are controlled by TAVERN_PUBLIC_URL and TRUSTED_PROXY_CIDRS in the deployment configuration. Changing them requires redeploying the account gateway.</p><p>{value.deployment.uploadValidation} Configure byte limits in Storage.</p></form>}{error && <p className='connect-error' role='alert'>{error}</p>}
  </section>;
}
