import { canInviteToRoom } from '@/lib/interactions';
import { canManageServerRoles, effectiveRolePermissions, memberRoleRank, readRolePolicy } from '@/lib/roles';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { requestApi } from '@/lib/api';
import { Field } from './auth-gateway';
import { copyText } from './action-menu';
import { getMatrixClient } from '@/lib/matrix';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
export function InviteManager({roomId}:{roomId:string}) {
  const [invites,setInvites]=useState<any[]>([]),[hours,setHours]=useState(24),[uses,setUses]=useState(1),[email,setEmail]=useState(''),[domain,setDomain]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sendEmail,setSendEmail]=useState(false),[mailReady,setMailReady]=useState(false),[roles,setRoles]=useState<string[]>([]),[revoking,setRevoking]=useState<any>(null);
  const c=getMatrixClient(),room=c?.getRoom(roomId),me=c?.getUserId(),allowed=canInviteToRoom(roomId),policy=room?.isSpaceRoom()?readRolePolicy(roomId):null;
  const grants=policy&&me?effectiveRolePermissions(policy,me):new Set(),rank=policy&&me?memberRoleRank(policy,me):0;
  const choices=policy&&canManageServerRoles(roomId)?policy.roles.filter(role=>role.id!=='everyone'&&role.position<rank&&role.permissions.every(permission=>grants.has(permission))):[];
  async function load(){const result=await requestApi('/invitations?roomId='+encodeURIComponent(roomId));setInvites(result.invitations||[]);}
  useEffect(()=>{setInvites([]);setLink('');setError('');setRoles([]);if(allowed){void load().catch(e=>setError(e.message));void requestApi('/auth/config').then(value=>setMailReady(value.smtpConfigured===true)).catch(()=>setMailReady(false));}},[roomId,allowed]);
  if(!c||!room||!me||!allowed)return null;
  return <section className="product-section"><h3>Invitation links</h3><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await requestApi('/invitations',{roomId,expiresInHours:hours,maxUses:uses,email:email||undefined,domain:domain||undefined,defaultRoleIds:roles,sendEmail});setLink(result.url);if(result.warning)setError(result.warning);await load();if(!result.warning)toast.success(result.emailSent?'Invitation created and emailed':'Invitation created');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><fieldset disabled={busy}>
    <Field label="Expires after (hours)"><input type="number" min={1} max={720} value={hours} onChange={e=>setHours(Number(e.target.value))} required/></Field><Field label="Maximum uses"><input type="number" min={1} max={1000} value={uses} onChange={e=>setUses(Number(e.target.value))} required/></Field><Field label="Restrict to verified email (optional)"><input type="email" value={email} onChange={e=>{setEmail(e.target.value);if(!e.target.value)setSendEmail(false);}}/></Field><Field label="Restrict email domain (optional)"><input placeholder="example.com" value={domain} onChange={e=>setDomain(e.target.value)}/></Field>
    {mailReady&&<label className="check-label"><input type="checkbox" checked={sendEmail} disabled={!email} onChange={e=>setSendEmail(e.target.checked)}/>Email this invitation to the restricted address</label>}
    {!!choices.length&&<fieldset><legend>Assign roles after joining</legend>{choices.map(role=><label className="check-label" key={role.id}><input type="checkbox" checked={roles.includes(role.id)} disabled={!roles.includes(role.id)&&roles.length>=20} onChange={e=>setRoles(old=>e.target.checked?[...old,role.id]:old.filter(id=>id!==role.id))}/>{role.icon} {role.name}</label>)}<p>Only roles you can currently assign are offered. Your authority and the role permissions are checked again when the invitation is accepted.</p></fieldset>}
    <button className="primary-button">Create invitation</button></fieldset></form>
    {link&&<div className="notice"><div><p>Copy this link now. It will not be displayed again.</p><code style={{overflowWrap:'anywhere'}}>{link}</code><button className="secondary-button" onClick={()=>copyText(link)}>Copy invite</button></div></div>}
    <h4>Existing invitations</h4>{!invites.length&&<p>No invitation links for this conversation.</p>}{invites.map(invitation=>{const state=invitation.revoked?'Revoked':invitation.expiresAt<=Date.now()?'Expired':invitation.uses>=invitation.maxUses?'Used up':'Active';return <div className="device-row" key={invitation.id}><span><strong>{invitation.uses||0} / {invitation.maxUses} uses · {state}</strong><small>Created by {invitation.creator} on {new Date(invitation.createdAt).toLocaleString()}</small><small>Expires {new Date(invitation.expiresAt).toLocaleString()}</small>{(invitation.email||invitation.domain)&&<small>Restricted to {invitation.email||'@'+invitation.domain}</small>}{invitation.defaultRoleIds?.length>0&&<small>Roles: {invitation.defaultRoleIds.map((id:string)=>policy?.roles.find(role=>role.id===id)?.name||id).join(', ')}</small>}</span>{!invitation.revoked&&<button className="secondary-button" disabled={busy} onClick={()=>setRevoking(invitation)}>Revoke</button>}</div>;})}
    {error&&<p className="connect-error" role="alert">{error}</p>}
    <Dialog open={!!revoking} onOpenChange={open=>{if(!open&&!busy)setRevoking(null);}}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Revoke this invitation?</DialogTitle><DialogDescription>The shared link will stop working. Members who already joined keep their membership and assigned roles.</DialogDescription></DialogHeader><div className="inline-actions"><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await requestApi('/invitations/'+encodeURIComponent(revoking.id),undefined,'DELETE');setRevoking(null);await load();toast.success('Invitation revoked');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Revoke invitation</button><button className="secondary-button" disabled={busy} onClick={()=>setRevoking(null)}>Cancel</button></div></DialogContent></Dialog>
  </section>;
}
export function RedeemInvite({onJoined}:{onJoined:(roomId:string)=>void}){
  const [token,setToken]=useState(()=>new URLSearchParams(location.search).get('invite')||''),[preview,setPreview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(token)requestApi('/invitations/preview/'+encodeURIComponent(token)).then(setPreview).catch(e=>setError(e.message));},[token]);
  function close(){setToken('');const url=new URL(location.href);url.searchParams.delete('invite');history.replaceState(null,'',url);}
  return <Dialog open={!!token} onOpenChange={open=>{if(!open&&!busy)close();}}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Join {preview?.roomName||'a conversation'}</DialogTitle><DialogDescription>{preview?.requiresEmail?'This invitation requires a verified email matching its restrictions.':'Accept this invitation to join the conversation.'}</DialogDescription></DialogHeader>{error&&<p className="connect-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy||!preview} onClick={async()=>{setBusy(true);setError('');try{const r=await requestApi('/invitations/redeem',{token});close();onJoined(r.roomId);toast.success('Invitation accepted');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Joining…':'Accept invitation'}</button></DialogContent></Dialog>;
}
