import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { requestApi } from '@/lib/api';
import { Field } from './auth-gateway';
import { copyText } from './action-menu';
import { getMatrixClient } from '@/lib/matrix';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
export function InviteManager({roomId}:{roomId:string}){
  const [invites,setInvites]=useState<any[]>([]),[hours,setHours]=useState(24),[uses,setUses]=useState(1),[email,setEmail]=useState(''),[domain,setDomain]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function load(){const r=await requestApi('/invitations?roomId='+encodeURIComponent(roomId));setInvites(r.invitations||[]);}
  useEffect(()=>{void load().catch(e=>setError(e.message));},[roomId]);
  const c=getMatrixClient(),room=c?.getRoom(roomId),me=c?.getUserId();if(!c||!room||!me||!room.currentState.hasSufficientPowerLevelFor('invite',room.getMember(me)?.powerLevel||0))return null;
  return <section className="product-section"><h3>Invitation links</h3><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await requestApi('/invitations',{roomId,expiresInHours:hours,maxUses:uses,email:email||undefined,domain:domain||undefined});setLink(r.url);await load();toast.success('Invitation created');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><Field label="Expires after (hours)"><input type="number" min={1} max={720} value={hours} onChange={e=>setHours(Number(e.target.value))} required/></Field><Field label="Maximum uses"><input type="number" min={1} max={1000} value={uses} onChange={e=>setUses(Number(e.target.value))} required/></Field><Field label="Restrict to verified email (optional)"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Restrict email domain (optional)"><input placeholder="example.com" value={domain} onChange={e=>setDomain(e.target.value)}/></Field><button className="primary-button" disabled={busy}>Create invitation</button></form>{link&&<div className="notice"><div><p>Copy this link now. It will not be displayed again.</p><code style={{overflowWrap:'anywhere'}}>{link}</code><button className="secondary-button" onClick={()=>copyText(link)}>Copy invite</button></div></div>}{invites.map(i=><div className="device-row" key={i.id}><span><strong>{i.uses||0} / {i.maxUses} uses</strong><small>Expires {new Date(i.expiresAt*(i.expiresAt<1e12?1000:1)).toLocaleString()} · {i.revoked?'Revoked':'Active'}</small></span>{!i.revoked&&<button className="secondary-button" disabled={busy} onClick={async()=>{setBusy(true);try{await requestApi('/invitations/'+encodeURIComponent(i.id),undefined,'DELETE');await load();toast.success('Invitation revoked');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Revoke</button>}</div>)}{error&&<p className="connect-error" role="alert">{error}</p>}</section>;
}
export function RedeemInvite({onJoined}:{onJoined:(roomId:string)=>void}){
  const [token,setToken]=useState(()=>new URLSearchParams(location.search).get('invite')||''),[preview,setPreview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(token)requestApi('/invitations/preview/'+encodeURIComponent(token)).then(setPreview).catch(e=>setError(e.message));},[token]);
  function close(){setToken('');const url=new URL(location.href);url.searchParams.delete('invite');history.replaceState(null,'',url);}
  return <Dialog open={!!token} onOpenChange={open=>{if(!open&&!busy)close();}}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Join {preview?.roomName||'a conversation'}</DialogTitle><DialogDescription>{preview?.requiresEmail?'This invitation requires a verified email matching its restrictions.':'Accept this invitation to join the conversation.'}</DialogDescription></DialogHeader>{error&&<p className="connect-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy||!preview} onClick={async()=>{setBusy(true);setError('');try{const r=await requestApi('/invitations/redeem',{token});close();onJoined(r.roomId);toast.success('Invitation accepted');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Joining…':'Accept invitation'}</button></DialogContent></Dialog>;
}
