import { useEffect, useState } from 'react';
import { Download, ZoomIn, ZoomOut, ChevronLeft, ChevronRight } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { downloadMatrixFile, matrixFileBlob } from '@/lib/matrix';
import { toast } from 'sonner';
export type MediaAttachment={id:string;name:string;size:number;url?:string;file?:any;type?:string};
export function MediaViewer({items,index,onChange,onClose}:{items:MediaAttachment[];index:number;onChange:(index:number)=>void;onClose:()=>void}){
  const item=items[index],[source,setSource]=useState(''),[mime,setMime]=useState(''),[error,setError]=useState(''),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
  useEffect(()=>{if(!item)return;let url='',live=true;const controller=new AbortController();setSource('');setError('');setZoom(1);setPan({x:0,y:0});matrixFileBlob(item,controller.signal).then(blob=>{if(live){url=URL.createObjectURL(blob);setMime(blob.type);setSource(url);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;controller.abort();if(url)URL.revokeObjectURL(url);};},[item]);
  return <Dialog open={!!item} onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="media-dialog"><DialogHeader><DialogTitle>{item?.name}</DialogTitle><DialogDescription>Decrypted on this device. Use the download button to save a copy.</DialogDescription></DialogHeader><div className="media-viewport" onPointerDown={e=>{if(zoom>1)e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(e.buttons&&zoom>1)setPan(p=>({x:p.x+e.movementX,y:p.y+e.movementY}));}} onWheel={e=>{setZoom(z=>Math.max(1,Math.min(5,z+(e.deltaY<0?.25:-.25))));}}>{error?<p role="alert">{error}</p>:!source?<p role="status">Opening attachment…</p>:mime.startsWith('image/')?<img draggable={false} src={source} alt={item.name} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}/>:mime.startsWith('video/')?<video src={source} controls playsInline/>:mime.startsWith('audio/')?<audio src={source} controls/>:<p>A preview is not available for this file. Download it to open with a compatible application.</p>}</div><div className="product-actions"><button className="secondary-button" aria-label="Previous attachment" disabled={index<=0} onClick={()=>onChange(index-1)}><ChevronLeft/></button><button className="secondary-button" aria-label="Next attachment" disabled={index>=items.length-1} onClick={()=>onChange(index+1)}><ChevronRight/></button>{mime.startsWith('image/')&&<><button className="secondary-button" aria-label="Zoom out" onClick={()=>{setZoom(z=>Math.max(1,z-.5));setPan({x:0,y:0});}}><ZoomOut/></button><button className="secondary-button" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(5,z+.5))}><ZoomIn/></button></>}<button className="secondary-button" onClick={()=>downloadMatrixFile(item).catch(e=>toast.error(e.message))}><Download/>Download</button></div></DialogContent></Dialog>;
}
