import { useEffect, useState } from 'react';
import { Download, ZoomIn, ZoomOut, ChevronLeft, ChevronRight } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { downloadMatrixFile, matrixFileBlob } from '@/lib/matrix';
import { toast } from 'sonner';
import { MediaPlayer } from './media-player';
export type MediaAttachment={id:string;name:string;size:number;url?:string;file?:any;type?:string;messageUrl?:string};
export function MediaViewer({items,index,onChange,onClose,isCurrent}:{items:MediaAttachment[];index:number;onChange:(index:number)=>void;onClose:()=>void;isCurrent?:()=>boolean}){
  const item=items[index],[opened,setOpened]=useState<{item:MediaAttachment;source:string;mime:string;error:string}|null>(null),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
  const source=opened?.item===item?opened.source:'',mime=opened?.item===item?opened.mime:'',error=opened?.item===item?opened.error:'';
  useEffect(()=>{if(!item)return;let url='',live=true;const controller=new AbortController();setOpened(null);setZoom(1);setPan({x:0,y:0});
    const current=()=>!isCurrent||isCurrent(), revoke=()=>{if(url){URL.revokeObjectURL(url);url='';}}, check=()=>{if(current())return true;live=false;controller.abort();revoke();setOpened(null);onClose();return false;};
    if(!check())return;const timer=isCurrent?setInterval(check,250):undefined;
    matrixFileBlob(item,controller.signal).then(blob=>{if(live&&check()){url=URL.createObjectURL(blob);setOpened({item,source:url,mime:blob.type,error:''});}}).catch(e=>{if(live&&check())setOpened({item,source:'',mime:'',error:e.message});});
    return()=>{live=false;controller.abort();if(timer)clearInterval(timer);revoke();};},[item,isCurrent]);
  if(isCurrent&&!isCurrent())return null;
  return <Dialog open={!!item} onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="media-dialog" onKeyDown={event=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.altKey||event.ctrlKey||event.metaKey)return;if(event.key==='ArrowLeft'&&index>0){event.preventDefault();onChange(index-1);}if(event.key==='ArrowRight'&&index<items.length-1){event.preventDefault();onChange(index+1);}}}><DialogHeader><DialogTitle>{item?.name}</DialogTitle><DialogDescription>Decrypted on this device. Use the download button to save a copy.</DialogDescription></DialogHeader><div className="media-viewport" onPointerDown={e=>{if(mime.startsWith('image/')&&zoom>1)e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(mime.startsWith('image/')&&e.buttons&&zoom>1)setPan(p=>({x:p.x+e.movementX,y:p.y+e.movementY}));}} onWheel={e=>{if(!mime.startsWith('image/'))return;setZoom(z=>Math.max(1,Math.min(5,z+(e.deltaY<0?.25:-.25))));}}>{error?<p role="alert">{error}</p>:!source?<p role="status">Opening attachment…</p>:mime.startsWith('image/')?<img draggable={false} src={source} alt={item.name} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}/>:mime.startsWith('video/')?<MediaPlayer key={source} source={source} name={item.name}/>:mime.startsWith('audio/')?<audio src={source} controls/>:<p>A preview is not available for this file. Download it to open with a compatible application.</p>}</div><div className="product-actions"><button className="secondary-button" aria-label="Previous attachment" disabled={index<=0} onClick={()=>onChange(index-1)}><ChevronLeft/></button><button className="secondary-button" aria-label="Next attachment" disabled={index>=items.length-1} onClick={()=>onChange(index+1)}><ChevronRight/></button>{mime.startsWith('image/')&&<><button className="secondary-button" aria-label="Zoom out" onClick={()=>{setZoom(z=>Math.max(1,z-.5));setPan({x:0,y:0});}}><ZoomOut/></button><button className="secondary-button" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(5,z+.5))}><ZoomIn/></button></>}{source?<a className="secondary-button" href={source} download={item.name}><Download/>Download</a>:<button className="secondary-button" onClick={()=>downloadMatrixFile(item).catch(e=>toast.error(e.message))}><Download/>Download</button>}{source&&<a className='secondary-button' href={source} target='_blank' rel='noopener noreferrer' referrerPolicy='no-referrer'>Open original</a>}{item?.messageUrl&&<button className='secondary-button' onClick={()=>void navigator.clipboard.writeText(item.messageUrl!).then(()=>toast.success('Message link copied')).catch(()=>toast.error('Clipboard access is unavailable.'))}>Copy message link</button>}</div></DialogContent></Dialog>;
}
