import { QuickProfile } from './quick-profile';
import { ActionMenu, type ContextAction } from './action-menu';
import { useEffect, useState } from 'react';
import { MessageCircle, Search, UserPlus } from 'lucide-react';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
import { readMemberProfile } from '@/lib/community';
import { effectiveRolePermissions, readRolePolicy } from '@/lib/roles';
import { groupDirectoryMembers } from '@/lib/member-directory';
import { CommunityImage } from './community-settings';
import { ServerRoleBadges } from './server-roles';
export function MemberDirectory({ roomId, serverId, onProfile, onMessage, onInvite, userActions }: { roomId: string; serverId?: string; onProfile: (id: string) => void; onMessage: (id: string) => void; onInvite?: () => void; userActions?: (id:string)=>ContextAction[] }) {
  const [query, setQuery] = useState(''), [limit, setLimit] = useState(50), [busy, setBusy] = useState(false), [error, setError] = useState(''), [, redraw] = useState(0);
  useEffect(() => { setQuery(''); setLimit(50); setError(''); return onMatrixUpdate(() => redraw(v => v + 1)); }, [roomId]);
  const client = getMatrixClient(), room = client?.getRoom(roomId), me = client?.getUserId(), policy = serverId ? readRolePolicy(serverId) : null;
  if (!room || !me) return <p>Join this conversation to see its members.</p>;
  const groups = groupDirectoryMembers(room.getJoinedMembers().map(member => { const profile = readMemberProfile(roomId, member.userId, serverId); return { member, profile, userId: member.userId, name: profile.name, powerLevel: member.powerLevel, presence: client?.getUser(member.userId)?.presence || 'offline' }; }), policy, query), members = groups.flatMap(group => group.members), shown = new Set(members.slice(0, limit).map(member => member.userId));
  const canInvite = onInvite && room.currentState.hasSufficientPowerLevelFor('invite', room.getMember(me)?.powerLevel || 0) && (!policy || effectiveRolePermissions(policy, me, roomId).has('invite'));
  return <section className="community-member-directory"><div className="inline-actions"><h3>Members ({room.getJoinedMemberCount()})</h3>{canInvite && <button className="secondary-button" onClick={onInvite}><UserPlus size={16} />Invite</button>}</div><label className="community-contact-search"><Search size={16} /><input aria-label="Search members" type="search" placeholder="Search name, nickname, or role" value={query} onChange={e => { setQuery(e.target.value); setLimit(50); }} /></label>{groups.filter(group => group.members.some(member => shown.has(member.userId))).map(group => <section key={group.id} aria-label={group.name}><h4 className="community-directory-group">{group.name} <span>{group.members.length}</span></h4>{group.members.filter(member => shown.has(member.userId)).map(({ member, profile }) => <ActionMenu key={member.userId} actions={userActions?.(member.userId)||[{label:'View profile',run:()=>onProfile(member.userId)}]}><div className="community-directory-row"><QuickProfile roomId={roomId} userId={member.userId} serverId={serverId} onOpenFull={()=>onProfile(member.userId)} onMessage={()=>onMessage(member.userId)}><button className="community-member-profile"><CommunityImage mxc={profile.avatar} name={profile.name} size={40} /><span><strong>{profile.name}{member.userId === me ? ' (you)' : ''}</strong><small>{profile.statusEmoji} {profile.status || (client?.getUser(member.userId)?.presence === 'online' ? 'Online' : client?.getUser(member.userId)?.presence === 'unavailable' ? 'Away' : 'Offline')}</small></span></button></QuickProfile><button className="icon-button" aria-label={'Message ' + profile.name} onClick={() => onMessage(member.userId)}><MessageCircle size={18} /></button>{serverId && <div className="community-directory-roles"><ServerRoleBadges serverId={serverId} userId={member.userId} /></div>}</div></ActionMenu>)}</section>)}{members.length > limit && <button className="secondary-button" onClick={() => setLimit(n => n + 50)}>Show more members</button>}{room.getJoinedMembers().length < room.getJoinedMemberCount() && <button className="secondary-button" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await room.loadMembersIfNeeded(); redraw(v => v + 1); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{busy ? 'Loading members…' : 'Load remaining members for search'}</button>}{!members.length && <p>No matching members in the loaded list.</p>}{error && <p role="alert" className="connect-error">{error}</p>}</section>;
}
