import { useEffect, useState } from 'react';
import { MessageCircle, Search, UserPlus } from 'lucide-react';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
import { readMemberProfile } from '@/lib/community';
import { effectiveRolePermissions, memberRoleRank, readRolePolicy } from '@/lib/roles';
import { CommunityImage } from './community-settings';
import { ServerRoleBadges } from './server-roles';
export function MemberDirectory({ roomId, serverId, onProfile, onMessage, onInvite }: { roomId: string; serverId?: string; onProfile: (id: string) => void; onMessage: (id: string) => void; onInvite?: () => void }) {
  const [query, setQuery] = useState(''), [limit, setLimit] = useState(50), [busy, setBusy] = useState(false), [error, setError] = useState(''), [, redraw] = useState(0);
  useEffect(() => { setQuery(''); setLimit(50); setError(''); return onMatrixUpdate(() => redraw(v => v + 1)); }, [roomId]);
  const client = getMatrixClient(), room = client?.getRoom(roomId), me = client?.getUserId(), policy = serverId ? readRolePolicy(serverId) : null;
  if (!room || !me) return <p>Join this conversation to see its members.</p>;
  const members = room.getJoinedMembers().map(member => ({ member, profile: readMemberProfile(roomId, member.userId, serverId) })).filter(({ member, profile }) => (profile.name + ' ' + member.userId).toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a, b) => (policy ? memberRoleRank(policy, b.member.userId) - memberRoleRank(policy, a.member.userId) : b.member.powerLevel - a.member.powerLevel) || a.profile.name.localeCompare(b.profile.name));
  const canInvite = onInvite && room.currentState.hasSufficientPowerLevelFor('invite', room.getMember(me)?.powerLevel || 0) && (!policy || effectiveRolePermissions(policy, me, roomId).has('invite'));
  return <section className="community-member-directory"><div className="inline-actions"><h3>Members ({room.getJoinedMemberCount()})</h3>{canInvite && <button className="secondary-button" onClick={onInvite}><UserPlus size={16} />Invite</button>}</div><label className="community-contact-search"><Search size={16} /><input aria-label="Search members" type="search" placeholder="Search members" value={query} onChange={e => { setQuery(e.target.value); setLimit(50); }} /></label>{members.slice(0, limit).map(({ member, profile }) => <div key={member.userId} className="community-directory-row"><button className="community-member-profile" onClick={() => onProfile(member.userId)}><CommunityImage mxc={profile.avatar} name={profile.name} size={40} /><span><strong>{profile.name}{member.userId === me ? ' (you)' : ''}</strong><small>{profile.statusEmoji} {profile.status || (client?.getUser(member.userId)?.presence === 'online' ? 'Online' : client?.getUser(member.userId)?.presence === 'unavailable' ? 'Away' : 'Offline')}</small></span></button><button className="icon-button" aria-label={'Message ' + profile.name} onClick={() => onMessage(member.userId)}><MessageCircle size={18} /></button>{serverId && <div className="community-directory-roles"><ServerRoleBadges serverId={serverId} userId={member.userId} /></div>}</div>)}{members.length > limit && <button className="secondary-button" onClick={() => setLimit(n => n + 50)}>Show more members</button>}{room.getJoinedMembers().length < room.getJoinedMemberCount() && <button className="secondary-button" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await room.loadMembersIfNeeded(); redraw(v => v + 1); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{busy ? 'Loading members…' : 'Load remaining members for search'}</button>}{!members.length && <p>No matching members in the loaded list.</p>}{error && <p role="alert" className="connect-error">{error}</p>}</section>;
}
