import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
import { canAssignMemberRoles, effectiveRolePermissions, memberRoleRank, readRolePolicy, saveMemberRoles } from '@/lib/roles';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
const eventName = 'tavern:member-roles';
export function openMemberRoles(serverId: string, userId: string) { window.dispatchEvent(new CustomEvent(eventName, { detail: { serverId, userId } })); }
export function MemberRolesDialog({ onChanged }: { onChanged?: () => Promise<unknown> }) {
  const [target, setTarget] = useState<{ serverId: string; userId: string } | null>(null);
  useEffect(() => { const show = (event: Event) => { const detail = (event as CustomEvent).detail; if (typeof detail?.serverId === 'string' && typeof detail?.userId === 'string' && canAssignMemberRoles(detail.serverId, detail.userId)) setTarget(detail); }; window.addEventListener(eventName, show); return () => window.removeEventListener(eventName, show); }, []);
  return <Dialog open={!!target} onOpenChange={open => { if (!open) setTarget(null); }}><DialogContent className='tavern-dialog'><DialogHeader><DialogTitle>Member roles</DialogTitle><DialogDescription>{target ? getMatrixClient()?.getRoom(target.serverId)?.getMember(target.userId)?.name || target.userId : 'Manage server roles for this member.'}</DialogDescription></DialogHeader>{target && <MemberRoleEditor key={target.serverId + target.userId} {...target} onChanged={onChanged}/>}</DialogContent></Dialog>;
}
export function MemberRoleEditor({ serverId, userId, onChanged }: { serverId: string; userId: string; onChanged?: () => Promise<unknown> }) {
  const initial = readRolePolicy(serverId)?.members[userId] || [], [selected, setSelected] = useState(initial), [previous, setPrevious] = useState(initial), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [, redraw] = useState(0); useEffect(() => onMatrixUpdate(() => redraw(value => value + 1)), []);
  const policy = readRolePolicy(serverId), me = getMatrixClient()?.getUserId();
  if (!policy || !me || !canAssignMemberRoles(serverId, userId)) return <p>You can manage only members and roles below your authority.</p>;
  const grants = effectiveRolePermissions(policy, me), rank = memberRoleRank(policy, me);
  return <form className='dialog-form' onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { const saved = await saveMemberRoles(serverId, userId, selected, previous), ids = saved.members[userId] || []; setSelected(ids); setPrevious(ids); toast.success('Member roles saved'); await onChanged?.(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><p>Every member keeps the default Member role. You can grant only permissions you have, and only roles below your highest role.</p><fieldset disabled={busy}>{[...policy.roles].sort((a, b) => b.position - a.position).map(role => { const checked = role.id === 'everyone' || selected.includes(role.id), allowed = role.id !== 'everyone' && role.position < rank && (checked || role.permissions.every(permission => grants.has(permission))); return <label className='check-label' key={role.id}><input type='checkbox' checked={checked} disabled={!allowed} onChange={event => setSelected(ids => event.target.checked ? [...ids, role.id] : ids.filter(id => id !== role.id))}/><span style={{ color: role.color || undefined }}>{role.icon} {role.name}</span></label>; })}</fieldset><div className='product-actions'><button className='primary-button' disabled={busy}>Save member roles</button><button className='secondary-button' type='button' disabled={busy} onClick={() => { const ids = readRolePolicy(serverId)?.members[userId] || []; setSelected(ids); setPrevious(ids); setError(''); }}>Reload assignments</button></div>{error && <p role='alert' className='connect-error'>{error}</p>}</form>;
}
