import { useEffect, useRef, useState } from 'react';
import { searchMessages, indexRoomHistory, searchIndexStatus, clearSearchIndex, type SearchDocument } from '@/lib/search-index';
import { getMatrixClient, resolveMatrixMessage } from '@/lib/matrix';
import { RichMessage } from './rich-message';

export function MessageSearch({ initialQuery = '', roomId, onSelect }: { initialQuery?: string; roomId: string; onSelect: (message: any) => void }) {
  const [query, setQuery] = useState(initialQuery), [scope, setScope] = useState('all'), [hits, setHits] = useState<SearchDocument[]>([]), [cursor, setCursor] = useState<string | null>(null), [count, setCount] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(''), [progress, setProgress] = useState('');
  const generation = useRef(0), indexing = useRef<AbortController | null>(null);
  async function search(next?: string) { const run = ++generation.current; setBusy(true); setError(''); try { const result = await searchMessages(query, { cursor: next, ...(scope === 'room' ? { roomIds: [roomId] } : {}) }); if (run !== generation.current) return; setHits(old => next ? [...old, ...result.hits] : result.hits); setCursor(result.nextCursor); setCount(result.indexedCount); } catch (e: any) { if (run === generation.current) setError(e.message); } finally { if (run === generation.current) setBusy(false); } }
  useEffect(() => { setHits([]); setCursor(null); const timer = setTimeout(() => { if (query.trim()) void search(); else void searchIndexStatus().then(s => { setCount(s.indexedCount); if (s.error) setError(s.error); }).catch(e => setError(e.message)); }, 250); return () => { clearTimeout(timer); generation.current++; }; }, [query, scope, roomId]);
  useEffect(() => () => { indexing.current?.abort(); }, []);
  async function indexHistory() { const controller = new AbortController(); indexing.current = controller; setError(''); const rooms = scope === 'room' ? [roomId] : getMatrixClient()?.getRooms().filter(r => !r.isSpaceRoom() && r.getMyMembership() === 'join').map(r => r.roomId) || []; try { for (let i = 0; i < rooms.length; i++) await indexRoomHistory(rooms[i], p => setProgress(`Conversation ${i + 1}/${rooms.length}: ${p.indexed} messages processed`), controller.signal); setProgress('History indexing complete.'); if (query.trim()) await search(); else setCount((await searchIndexStatus()).indexedCount); } catch (e: any) { setError(e.message); } finally { indexing.current = null; } }
  return <><div className="input-with-icon search-input"><input autoFocus aria-label="Search messages" placeholder='Search messages or "an exact phrase"' value={query} maxLength={1000} onChange={e => setQuery(e.target.value)}/></div><div className="product-actions"><select aria-label="Search scope" value={scope} onChange={e => setScope(e.target.value)}><option value="all">All conversations</option><option value="room">Current conversation</option></select><button className="secondary-button" disabled={!!indexing.current} onClick={() => void indexHistory()}>Index older history</button>{indexing.current && <button className="secondary-button" onClick={() => indexing.current?.abort()}>Cancel indexing</button>}</div><small>Filters: from:username in:channel before:2026-09-01 after:2026-08-01 has:image has:file has:link mentions:me</small><p role="status">{busy ? 'Searching…' : count.toLocaleString() + ' messages indexed on this device.'} {progress}</p>{error && <p className="connect-error" role="alert">{error}</p>}<div className="search-results">{hits.map(m => <button key={m.id} onClick={() => { void resolveMatrixMessage(m.roomId, m.id).then(onSelect).catch(e => setError(e.message)); }}><div><strong>{m.roomName}</strong><span>{new Date(m.timestamp).toLocaleString()}</span></div><RichMessage text={m.body}/><small>{m.authorName}</small></button>)}{query && !busy && !hits.length && !error && <p>No matching messages in the indexed history.</p>}{cursor && <button className="secondary-button" disabled={busy} onClick={() => void search(cursor)}>More results</button>}</div><details><summary>Search privacy</summary><p>Messages are decrypted and indexed in your browser. Search records are encrypted with keys stored on this device. Index older history to include messages outside the current timeline.</p><button className="secondary-button" onClick={() => void clearSearchIndex().then(() => { setHits([]); setCount(0); setProgress('Local index cleared. New messages will be indexed as they arrive.'); }).catch(e => setError(e.message))}>Clear local search index</button></details></>;
}
