import { useEffect, useState } from 'react';
import { Bell, Volume2 } from 'lucide-react';
import { toast } from 'sonner';
import { onMatrixUpdate } from '@/lib/matrix';
import { browserNotificationsEnabled, disableBrowserNotifications, enableBrowserNotifications, playNotificationSound, synchronizeNotificationRules } from '@/lib/notifications';
import { readNotificationPreferences, resolveNotificationPreference, updateNotificationPreferences, type NotificationMode, type NotificationPreferences, type NotificationScope } from '@/lib/notification-preferences';
export function NotificationSettings({ roomId, serverId }: { roomId?: string; serverId?: string }) {
  const [preferences, setPreferences] = useState(readNotificationPreferences), [busy, setBusy] = useState(false), [error, setError] = useState(''), [desktop, setDesktop] = useState(browserNotificationsEnabled), [, tick] = useState(0);
  useEffect(() => { const off = onMatrixUpdate(() => setPreferences(readNotificationPreferences())), timer = setInterval(() => tick(v => v + 1), 30_000); return () => { off(); clearInterval(timer); }; }, []);
  const effective = resolveNotificationPreference(preferences, roomId, serverId), own = roomId ? preferences.rooms[roomId] : serverId ? preferences.servers[serverId] : preferences.global;
  async function run(fn: () => Promise<unknown>) { setBusy(true); setError(''); try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function update(change: Partial<NotificationScope> & { sound?: boolean }) { await run(async () => { const next = await updateNotificationPreferences(p => roomId ? { ...p, rooms: { ...p.rooms, [roomId]: { ...(p.rooms[roomId] || { mode: 'inherit', mutedUntil: 0 }), ...change } } } : serverId ? { ...p, servers: { ...p.servers, [serverId]: { ...(p.servers[serverId] || { mode: 'inherit', mutedUntil: 0 }), ...change } } } : { ...p, global: { ...p.global, ...change, mode: change.mode === 'inherit' ? 'all' : change.mode || p.global.mode } }); setPreferences(next); try { if (change.mode !== undefined || change.mutedUntil !== undefined) await synchronizeNotificationRules(next, { roomId, serverId: roomId ? undefined : serverId }); } catch { throw new Error('Tavern preferences were saved, but native push rules could not be updated. Save again to retry.'); } toast.success('Notification preferences saved'); }); }
  return <section className="channel-admin"><h3>{roomId ? 'Channel notifications' : serverId ? 'Server notifications' : 'Notification preferences'}</h3><div className="dialog-form"><label>Notify me about<select disabled={busy} value={own?.mode || 'inherit'} onChange={e => void update({ mode: e.target.value as NotificationMode | 'inherit' })}>{(roomId || serverId) && <option value="inherit">Inherit ({effective.source.toLowerCase()})</option>}<option value="all">All messages</option><option value="mentions">Mentions only</option><option value="nothing">Nothing</option></select></label><p className="login-help">Current behavior: {effective.muted ? 'Muted' : effective.mode === 'all' ? 'All messages' : effective.mode === 'mentions' ? 'Mentions only' : 'No notifications'} · {effective.source.toLowerCase()} preference.</p><label>Mute duration<select value="" disabled={busy} onChange={e => { const duration = Number(e.target.value); if (e.target.value) void update({ mutedUntil: duration === -1 ? -1 : duration === 0 ? 0 : Date.now() + duration }); }}><option value="">Choose a duration</option><option value="0">Unmute this level</option><option value="900000">15 minutes</option><option value="3600000">1 hour</option><option value="10800000">3 hours</option><option value="28800000">8 hours</option><option value="86400000">24 hours</option><option value="-1">Until I turn it back on</option></select></label>{effective.muted && <p className="login-help">{effective.mutedUntil === -1 ? 'Muted until you turn it back on.' : 'Muted until ' + new Date(effective.mutedUntil).toLocaleString()}. Temporary mutes expire automatically in Tavern.</p>}{!roomId && !serverId && <><button type="button" className="secondary-button" disabled={busy} onClick={() => void run(async () => { if (desktop) disableBrowserNotifications(); else await enableBrowserNotifications(); setDesktop(browserNotificationsEnabled()); })}><Bell size={16} />{desktop ? 'Disable browser alerts' : 'Enable browser alerts'}</button><label className="check-label"><input type="checkbox" disabled={busy} checked={preferences.global.sound} onChange={e => void update({ sound: e.target.checked })} />Play notification sounds</label><button type="button" className="secondary-button" onClick={() => void run(playNotificationSound)}><Volume2 size={16} />Test sound</button><p className="login-help">Browser alerts use a generic message, keeping names and message text off your desktop. Do not disturb and ignored users are always respected. Browser alerts work while Tavern is open.</p></>}{error && <p className="connect-error" role="alert">{error}</p>}</div></section>;
}
