import { useEffect, useState } from 'react';
import { requestApi } from '@/lib/api';
import { Field } from './auth-gateway';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { toast } from 'sonner';

const time = (n: number) => new Date(n < 1e12 ? n * 1000 : n).toLocaleString();
export function OperationsPanel({ mode, releases }: { mode: 'backups' | 'updates'; releases?: any }) {
  const [data, setData] = useState<any>(null), [settings, setSettings] = useState<any>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [confirm, setConfirm] = useState<{ kind: string; id?: string } | null>(null), [typed, setTyped] = useState(''), [version, setVersion] = useState('');
  const [job, setJob] = useState<any>(null), [jobId, setJobId] = useState(() => sessionStorage.getItem('tavern.operation') || '');
  async function refresh() { const result = await requestApi('/admin/backups'); setData(result); if (result.available) setSettings(result.settings); }
  useEffect(() => { void refresh().catch(e => setError(e.message)); }, []);
  useEffect(() => {
    if (!jobId) return; let live = true, timer: ReturnType<typeof setTimeout>;
    const poll = async () => { try { const result = await requestApi('/admin/operations/jobs/' + jobId); if (!live) return; setJob(result); if (['complete', 'failed'].includes(result.state)) { sessionStorage.removeItem('tavern.operation'); setJobId(''); void refresh().catch(() => {}); return; } } catch { if (live) setJob((old: any) => ({ ...old, state: 'reconnecting' })); } if (live) timer = setTimeout(poll, 3000); };
    void poll(); return () => { live = false; clearTimeout(timer); };
  }, [jobId]);
  async function run(task: () => Promise<any>, message?: string) { setBusy(true); setError(''); try { const result = await task(); if (result.jobId) { sessionStorage.setItem('tavern.operation', result.jobId); setJobId(result.jobId); setJob({ state: 'queued' }); } if (message) toast.success(message); return result; } catch (e: any) { setError(e.message); return null; } finally { setBusy(false); } }
  const update = (key: string, value: any) => setSettings((old: any) => ({ ...old, [key]: value }));
  const phrase = confirm?.kind === 'restore' ? 'RESTORE TO ISOLATED COPY' : confirm?.kind === 'update' ? 'UPDATE TAVERN' : 'DELETE BACKUP';
  return <div className="product-section">
    {error && <p className="connect-error" role="alert">{error}</p>}
    {!data ? <p role="status">Checking operations service…</p> : !data.available ? <p>{data.reason || 'Enable the operations profile to manage backups and application updates here.'}</p> : <>
      {mode === 'backups' ? <><p>Backups contain account secrets, encrypted messages, uploads, and server configuration. Store downloaded copies privately.</p><button className="primary-button" disabled={busy || !!jobId} onClick={() => void run(() => requestApi('/admin/backups', {}))}>Create backup</button><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Created</th><th>Size</th><th>Actions</th></tr></thead><tbody>{data.backups?.map((b: any) => <tr key={b.id}><td>{time(b.createdAt)}</td><td>{(b.sizeBytes / 1048576).toFixed(1)} MB</td><td><div className="product-actions"><a className="secondary-button" href={'/api/admin/backups/' + b.id + '/download'} download>Download</a><button className="secondary-button" disabled={busy || !!jobId} onClick={() => { setConfirm({ kind: 'restore', id: b.id }); setTyped(''); }}>Restore a copy</button><button className="secondary-button danger-text" disabled={busy || !!jobId} onClick={() => { setConfirm({ kind: 'delete', id: b.id }); setTyped(''); }}>Delete</button></div></td></tr>)}</tbody></table>{!data.backups?.length && <p>No backups yet.</p>}</div></> : <><Field label="Release version"><input value={version} placeholder={releases?.latestStable?.version || '0.4.1'} onChange={e => setVersion(e.target.value)} maxLength={80}/></Field><p>Updates within the installed major and minor version include a backup, a health check, and rollback on failure. Other migrations require the documented deployment procedure.</p><button className="primary-button" disabled={busy || !!jobId || !version.trim()} onClick={() => { setConfirm({ kind: 'update' }); setTyped(''); }}>Review update</button></>}
      {settings && <form className="dialog-form" onSubmit={e => { e.preventDefault(); void run(() => requestApi('/admin/operations/settings', settings, 'PUT'), 'Schedule saved'); }}><h3>{mode === 'backups' ? 'Backup schedule' : 'Automatic updates'}</h3><label className="check-label"><input type="checkbox" checked={!!settings[mode === 'backups' ? 'backupEnabled' : 'autoUpdateEnabled']} onChange={e => update(mode === 'backups' ? 'backupEnabled' : 'autoUpdateEnabled', e.target.checked)}/>Enable scheduled {mode}</label><Field label="Daily time (UTC)"><input type="time" required value={settings[mode === 'backups' ? 'backupTime' : 'updateTime']} onChange={e => update(mode === 'backups' ? 'backupTime' : 'updateTime', e.target.value)}/></Field>{mode === 'backups' ? <Field label="Backups to retain"><input type="number" min={1} max={100} required value={settings.retention} onChange={e => update('retention', Number(e.target.value))}/></Field> : <Field label="Release channel"><select value={settings.channel} onChange={e => update('channel', e.target.value)}><option value="stable">Stable</option><option value="prerelease">Prerelease</option></select></Field>}<button className="secondary-button" disabled={busy}>Save schedule</button></form>}
    </>}
    {job && <div className="notice" role="status"><div><strong>Operation: {job.state}</strong>{job.state === 'reconnecting' && <p>Waiting for the application to return. Backups briefly pause account services.</p>}{job.result?.error && <p>{job.result.error}</p>}{job.result?.message && <p>{job.result.message}</p>}{job.result?.volumes && <pre>{JSON.stringify(job.result.volumes, null, 2)}</pre>}</div></div>}
    {data?.jobs?.length > 0 && <details><summary>Recent operations</summary>{data.jobs.map((j: any) => <p key={j.id}>{time(j.created)} · {j.kind} · {j.state}{j.result?.error ? ' · ' + j.result.error : ''}</p>)}</details>}
    <Dialog open={!!confirm} onOpenChange={open => { if (!open && !busy) setConfirm(null); }}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>{confirm?.kind === 'restore' ? 'Restore an isolated copy?' : confirm?.kind === 'update' ? 'Update to ' + version + '?' : 'Delete this backup?'}</DialogTitle><DialogDescription>{confirm?.kind === 'restore' ? 'Create separate restored volumes for validation. Switching production to restored data requires the documented deployment procedure.' : confirm?.kind === 'update' ? 'The application will briefly disconnect. The worker creates a backup before updating Tavern and checks health before completing.' : 'This removes the saved archive permanently. Download a copy first if you need to keep it.'}</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e => { e.preventDefault(); const result = await run(() => confirm?.kind === 'restore' ? requestApi('/admin/backups/' + confirm.id + '/restore', { confirmation: typed }) : confirm?.kind === 'update' ? requestApi('/admin/updates/apply', { version: version.trim(), confirmation: typed }) : requestApi('/admin/backups/' + confirm?.id, undefined, 'DELETE')); if (result) { setConfirm(null); if (!result.jobId) await refresh().catch(e => setError(e.message)); } }}><Field label={'Type ' + phrase}><input value={typed} onChange={e => setTyped(e.target.value)} autoComplete="off" required/></Field>{error && <p role="alert" className="connect-error">{error}</p>}<button className="primary-button" disabled={busy || typed !== phrase}>Confirm</button></form></DialogContent></Dialog>
  </div>;
}
