import { useEffect, useState } from 'react';
import { cancelOutbox, editOutbox, enqueueOutbox, readOutbox, retryOutbox, watchOutbox, type OutboxItem } from '@/lib/outbox';
import { getMatrixClient } from '@/lib/matrix';
import { Field } from './auth-gateway';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { toast } from 'sonner';
const localTime = (n: number) => new Date(n - new Date(n).getTimezoneOffset() * 60000).toISOString().slice(0, 16);
export function ScheduleMessage({ roomId, parent, serverId, body, onScheduled, disabled }: { roomId: string; parent?: string; serverId?: string; body: string; onScheduled: () => void; disabled?: boolean }) {
  const [open, setOpen] = useState(false), [due, setDue] = useState(localTime(Date.now() + 3600000)), [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <><button className="icon-button" aria-label="Schedule this message" disabled={disabled || !body.trim()} onClick={() => setOpen(true)}>◷</button><Dialog open={open} onOpenChange={value => { if (!busy) setOpen(value); }}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Schedule message</DialogTitle><DialogDescription>The encrypted outbox delivers while Tavern is open and connected on this device. If closed, it sends when you next open this device's session.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await enqueueOutbox({ kind: 'scheduled', roomId, parent, serverId, body, due: new Date(due).getTime() }); onScheduled(); setOpen(false); toast.success('Message scheduled on this device'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}><Field label="Send at (local time)"><input type="datetime-local" required min={localTime(Date.now())} value={due} onChange={e => setDue(e.target.value)}/></Field><p>{body.slice(0, 300)}</p>{error && <p role="alert" className="connect-error">{error}</p>}<button className="primary-button" disabled={busy}>Schedule</button></form></DialogContent></Dialog></>;
}
export function ReminderDialog({ roomId, eventId, onClose }: { roomId: string; eventId: string; onClose: () => void }) {
  const [due, setDue] = useState(localTime(Date.now() + 1200000)), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  return <Dialog open onOpenChange={value => { if (!value && !busy) onClose(); }}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Remind me about this message</DialogTitle><DialogDescription>Reminders appear while this device's Tavern session is open. Missed reminders appear when you return.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await enqueueOutbox({ kind: 'reminder', roomId, eventId, body: '', due: new Date(due).getTime() }); onClose(); toast.success('Reminder saved'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}><div className="product-actions">{[[1200000, '20 minutes'], [3600000, '1 hour'], [86400000, 'Tomorrow'], [604800000, 'Next week']].map(([delay, label]) => <button className="secondary-button" type="button" key={delay} onClick={() => setDue(localTime(Date.now() + Number(delay)))}>{label}</button>)}</div><Field label="Remind me at"><input type="datetime-local" required min={localTime(Date.now())} value={due} onChange={e => setDue(e.target.value)}/></Field>{error && <p role="alert" className="connect-error">{error}</p>}<button className="primary-button" disabled={busy}>Save reminder</button></form></DialogContent></Dialog>;
}
export function OutboxPanel({ onOpen }: { onOpen: (roomId: string, eventId?: string) => void }) {
  const [items, setItems] = useState<OutboxItem[]>([]), [error, setError] = useState(''), [editing, setEditing] = useState<OutboxItem | null>(null), [busy, setBusy] = useState(false);
  useEffect(() => { let live = true; const refresh = () => void readOutbox().then(value => { if (live){setItems(value);setError('');} }).catch(e => { if (live) setError(e.message); }); refresh(); const off = watchOutbox(refresh); return () => { live = false; off(); }; }, []);
  async function run(fn: () => Promise<unknown>) { setBusy(true); setError(''); try { await fn(); return true; } catch (e: any) { setError(e.message); return false; } finally { setBusy(false); } }
  return <section className="product-section"><h3>Scheduled messages & reminders</h3><p>This device's encrypted outbox sends when Tavern is open and connected. Pending items stay on this device.</p>{error && <p role="alert" className="connect-error">{error}</p>}{items.map(item => <article className="product-section" key={item.id}><h3>{item.kind === 'reminder' ? 'Reminder' : item.error ? 'Waiting to retry' : 'Scheduled message'} · {getMatrixClient()?.getRoom(item.roomId)?.name || item.roomId}</h3><small>{new Date(item.due).toLocaleString()}</small>{item.body && <p>{item.body}</p>}{item.error && <p role="status">{item.error}</p>}<div className="product-actions"><button className="secondary-button" onClick={() => onOpen(item.roomId, item.eventId)}>Open conversation</button>{!item.attempts && <button className="secondary-button" disabled={busy} onClick={() => setEditing({ ...item })}>Edit</button>}{item.kind !== 'reminder' && item.error && <button className="secondary-button" disabled={busy} onClick={() => void run(() => retryOutbox(item.id))}>Retry delivery</button>}<button className="secondary-button" disabled={busy} onClick={() => void run(() => cancelOutbox(item.id))}>{item.kind === 'reminder' ? 'Dismiss reminder' : 'Cancel delivery'}</button></div></article>)}{!items.length && !error && <p>No pending messages or reminders.</p>}<Dialog open={!!editing} onOpenChange={value => { if (!value && !busy) setEditing(null); }}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Edit pending item</DialogTitle><DialogDescription>Changes apply before delivery starts.</DialogDescription></DialogHeader>{editing && <form className="dialog-form" onSubmit={async e => { e.preventDefault(); if (await run(() => editOutbox(editing.id, editing.body, editing.due))) setEditing(null); }}><Field label="Time"><input type="datetime-local" required value={localTime(editing.due)} onChange={e => setEditing({ ...editing, due: new Date(e.target.value).getTime() })}/></Field>{editing.kind !== 'reminder' && <Field label="Message"><textarea required maxLength={8000} value={editing.body} onChange={e => setEditing({ ...editing, body: e.target.value })}/></Field>}<button className="primary-button" disabled={busy}>Save changes</button></form>}</DialogContent></Dialog></section>;
}
