import { useEffect, useRef, useState, type ReactNode } from 'react';
import { getMatrixClient, matrixApi, onMatrixUpdate, resolveMatrixMessage } from '@/lib/matrix';
import { readNotificationPreferences, resolveNotificationPreference } from '@/lib/notification-preferences';
import { setRoomNotifications } from '@/lib/notifications';
import { canCreatePrivateThread, canEditPrivateThread, canInvitePrivateThread, canModeratePrivateThreadMember, canPostPrivateThread, createPrivateThread, invitePrivateThreadMember, loadPrivateThreadSettings, moderatePrivateThreadMember, privateArchiveIntervals, privateThreadArchived, privateThreadBinding, privateThreadCandidates, privateThreadMembers, privateThreadsForSource, readPrivateThreadSettings, savePrivateThreadSettings, sendPrivateThreadMessage, type PrivateThreadSettings } from '@/lib/private-threads';
import { MessageList } from './message-list';
import './private-thread.css';

const intervalName = (seconds: number) => ({ 0: 'Never', 3600: 'After 1 hour', 86400: 'After 1 day', 259200: 'After 3 days', 604800: 'After 1 week' }[seconds]);
function useMatrixRevision() { const [revision, refresh] = useState(0); useEffect(() => onMatrixUpdate(() => refresh(value => value + 1)), []); return revision; }

export function PrivateThreadLauncher({ sourceRoomId, sourceEventId = '', onOpen }: { sourceRoomId: string; sourceEventId?: string; onOpen: (roomId: string) => void }) {
  useMatrixRevision();
  const [expanded, setExpanded] = useState(false), [title, setTitle] = useState(''), [selected, setSelected] = useState<string[]>([]), [interval, setInterval] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [page, setPage] = useState(0), [query, setQuery] = useState(''), [, refresh] = useState(0);
  useEffect(() => { let active = true; setSelected([]); setTitle(''); setExpanded(false); setPage(0); setError(''); const room = getMatrixClient()?.getRoom(sourceRoomId); void room?.loadMembersIfNeeded().then(() => { if (active) refresh(value => value + 1); }).catch(() => {}); return () => { active = false; }; }, [sourceRoomId]);
  const discussions = privateThreadsForSource(sourceRoomId), candidates = privateThreadCandidates(sourceRoomId).filter(member => (member.name + member.userId).toLocaleLowerCase().includes(query.toLocaleLowerCase())), canCreate = canCreatePrivateThread(sourceRoomId);
  if (!canCreate && !discussions.length) return null;
  return <section className='private-thread-launcher' aria-label='Private discussions'>
    <details><summary>Private discussions ({discussions.length})</summary>
      <p className='login-help'>Separate encrypted conversations visible to their invited members. The source channel has no public discussion list.</p>
      <ul>{discussions.slice(page * 10, page * 10 + 10).map(discussion => <li key={discussion.roomId}><button type='button' className='link-button' onClick={() => onOpen(discussion.roomId)}>{discussion.title}{discussion.membership === 'invite' ? ' · Invitation' : discussion.archived ? ' · Archived' : ''}</button></li>)}</ul>
      {discussions.length > 10 && <div className='product-actions'><button type='button' disabled={page === 0} onClick={() => setPage(value => value - 1)}>Previous discussions</button><button type='button' disabled={(page + 1) * 10 >= discussions.length} onClick={() => setPage(value => value + 1)}>Next discussions</button></div>}
      {canCreate && <button className='secondary-button' type='button' onClick={() => setExpanded(value => !value)}>Create private discussion</button>}
      {expanded && <form className='dialog-form' onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { const id = await createPrivateThread(sourceRoomId, title, selected, sourceEventId, interval); setExpanded(false); setSelected([]); setTitle(''); onOpen(id); } catch (failure) { setError((failure as Error).message); } finally { setBusy(false); } }}>
        <fieldset disabled={busy}><label>Discussion title<input required maxLength={120} value={title} onChange={event => setTitle(event.target.value)}/></label>
          <p className='login-help'>Messages stay in the new encrypted room. The source message is linked without copying it. Titles, membership and source identifiers are room metadata visible to invitees and the homeserver. New members receive messages from when they join.</p>
          <label>Find source members<input value={query} onChange={event => setQuery(event.target.value)}/></label>
          <fieldset className='private-member-options'><legend>Invite current source members ({selected.length}/50)</legend>{candidates.slice(0, 100).map(member => <label key={member.userId} className='check-label'><input type='checkbox' checked={selected.includes(member.userId)} disabled={!selected.includes(member.userId) && selected.length >= 50} onChange={event => setSelected(value => event.target.checked ? [...value, member.userId] : value.filter(id => id !== member.userId))}/>{member.name} <small>{member.userId}</small></label>)}{candidates.length > 100 && <p>Refine the member search to see more results.</p>}</fieldset>
          <label>Auto archive after inactivity<select value={interval} onChange={event => setInterval(Number(event.target.value))}>{privateArchiveIntervals.map(seconds => <option key={seconds} value={seconds}>{intervalName(seconds)}</option>)}</select></label>
          <p className='login-help'>Source membership and permissions govern new invitations and posting. Leaving the source does not remove private room membership or erase messages already received. Remove members in this discussion separately.</p>
          <button className='primary-button' disabled={!title.trim()}>{busy ? 'Creating…' : 'Create encrypted discussion'}</button>
        </fieldset>
      </form>}{error && <p className='connect-error' role='alert'>{error}</p>}
    </details>
  </section>;
}

export function PrivateThreadPanel({ roomId, focusId, onClose, onOpenSource, onMember, renderMessage, renderComposer }: { roomId: string; focusId?: {id:string;request:number}|null; onClose: () => void; onOpenSource?: (sourceRoomId: string, sourceEventId: string) => void; onMember?: (userId: string, roomId: string) => void; renderMessage?: (message: any) => ReactNode; renderComposer?: (onSent: () => Promise<void>, disabled: boolean) => ReactNode }) {
  const revision = useMatrixRevision(), room = getMatrixClient()?.getRoom(roomId), binding = privateThreadBinding(room), membership = room?.getMyMembership();
  const [messages, setMessages] = useState<any[]>([]), [hasMore, setHasMore] = useState(false), [body, setBody] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [status, setStatus] = useState(''), [invite, setInvite] = useState(''), [memberQuery, setMemberQuery] = useState('');
  const [settings, setSettings] = useState<PrivateThreadSettings>(() => readPrivateThreadSettings(room)), [membersPage, setMembersPage] = useState(0);
  const scroll = useRef<HTMLDivElement>(null), [pending, setPending] = useState<{ kind: 'remove' | 'leave'; target: string } | null>(null), [confirmation, setConfirmation] = useState('');
  const sequence = useRef(0), activeRoom = useRef(roomId); activeRoom.current = roomId;
  const focusRequest=useRef<{owner:unknown;id:string;request:number;promise:Promise<any>}|null>(null),[loadedFocus,setLoadedFocus]=useState<{id:string;request:number}|null>(null);
  async function load(before = false) {
    const token=++sequence.current,owner=getMatrixClient(),target=focusId;
    const result=await matrixApi('messages',undefined,{conversation:roomId,...(before?{before:'older'}:{})});
    let linked:any=null,focusError='';
    if(target&&!result.messages.some((message:any)=>message.id===target.id)) {
      try {
        if(focusRequest.current?.owner!==owner||focusRequest.current.id!==target.id||focusRequest.current.request!==target.request)focusRequest.current={owner,id:target.id,request:target.request,promise:resolveMatrixMessage(roomId,target.id)};
        linked=await focusRequest.current.promise;if(linked?.conversation_id!==roomId)throw new Error('Wrong conversation');
      }
      catch { linked=null;focusError='The linked private message is unavailable. You can still read the messages below.'; }
    }
    if(token!==sequence.current||activeRoom.current!==roomId||getMatrixClient()!==owner||owner?.getRoom(roomId)?.getMyMembership()!=='join')return;
    const rows=linked?[linked,...result.messages].sort((a,b)=>a.created_at-b.created_at):result.messages;
    setMessages(rows);setHasMore(result.hasMore);if(focusError)setError(focusError);
    if(target&&rows.some((message:any)=>message.id===target.id))setLoadedFocus(previous=>previous?.id===target.id&&previous.request===target.request?previous:target);
    const last=result.messages.at(-1);if(last&&document.hasFocus())void matrixApi('read',{conversation:roomId,id:last.id}).catch(()=>{});
  }
  useEffect(() => { focusRequest.current=null;setLoadedFocus(null);setMessages([]); setBody(''); setError(''); setStatus(''); setSettings(readPrivateThreadSettings(getMatrixClient()?.getRoom(roomId))); setMembersPage(0); return () => { sequence.current++; }; }, [roomId]);
  useEffect(()=>{setLoadedFocus(null);setError('');},[focusId?.id,focusId?.request]);
  useEffect(() => { if (membership === 'join') { void load().catch(failure => { if (activeRoom.current === roomId) setError((failure as Error).message); }); void room?.loadMembersIfNeeded().catch(() => {}); } }, [roomId, revision, membership, focusId?.id, focusId?.request]);
  async function run(action: () => Promise<unknown>, message = '') { setBusy(true); setError(''); setStatus(''); try { await action(); if (activeRoom.current === roomId) setStatus(message); } catch (failure) { if (activeRoom.current === roomId) setError((failure as Error).message); } finally { if (activeRoom.current === roomId) setBusy(false); } }
  const members = privateThreadMembers(roomId), candidates = binding ? privateThreadCandidates(binding.source_room_id, roomId).filter(member => (member.name + member.userId).toLocaleLowerCase().includes(memberQuery.toLocaleLowerCase())) : [], archived = privateThreadArchived(room), client = getMatrixClient(), me = client?.getUserId();
  const mode = resolveNotificationPreference(readNotificationPreferences(), roomId).mode;
  return <aside className='private-thread-panel' aria-label='Private discussion'>
    <header><div><small>Private · Encrypted</small><h2>{readPrivateThreadSettings(room).title}</h2></div><button type='button' className='secondary-button' onClick={onClose} aria-label='Close private discussion'>Close</button></header>
    {!room ? <p role='status'>Waiting for the new discussion to sync…</p> : !binding ? <p role='alert'>This room’s private discussion information is unavailable.</p> : <>
      <p className='login-help'>Only invited members can join. Source channel moderators do not automatically receive these messages. Previously received messages and keys cannot be recalled.</p>
      {onOpenSource && <button type='button' className='link-button' onClick={() => onOpenSource(binding.source_room_id, binding.source_event_id)}>View source conversation</button>}
      {membership === 'invite' ? <div><p>You are invited to this separate encrypted discussion. You receive messages from when you join.</p><button className='primary-button' disabled={busy} onClick={() => void run(async () => { await getMatrixClient()?.joinRoom(roomId); }, 'Invitation accepted. Waiting for messages to sync.')}>Accept private discussion</button><button className='secondary-button' disabled={busy} onClick={() => void run(async () => { await getMatrixClient()?.leave(roomId); onClose(); })}>Decline invitation</button></div> : membership !== 'join' ? <p>You are no longer a member of this private discussion.</p> : <>
        <details><summary>Discussion settings and {members.length} members</summary>
          <p className='login-help'>Removing someone from the source channel stops new private posts and invitations. To stop future private-room access, an authorized member must remove them here too. They retain messages and keys already received.</p>
          <label>Discussion notifications<select value={mode} disabled={busy} onChange={event => void run(() => setRoomNotifications(getMatrixClient()!, roomId, event.target.value === 'nothing' ? 'mute' : event.target.value as 'all' | 'mentions'), 'Notification settings saved.')}><option value='all'>All messages</option><option value='mentions'>Mentions only</option><option value='nothing'>Mute discussion</option></select></label>
          <ul>{members.slice(membersPage * 20, membersPage * 20 + 20).map(member => <li key={member.userId}><button type='button' className='link-button' onClick={() => onMember?.(member.userId, roomId)}>{member.name}</button> <small>{member.userId} · {member.membership === 'invite' ? 'Invited' : 'Joined'}</small>{canModeratePrivateThreadMember(roomId, member.userId) && <button type='button' disabled={busy} className='secondary-button' onClick={() => { setPending({ kind: 'remove', target: member.userId }); setConfirmation(''); }}>Remove {member.name}</button>}</li>)}</ul>
          {members.length > 20 && <div className='product-actions'><button disabled={membersPage === 0} onClick={() => setMembersPage(value => value - 1)}>Previous members</button><button disabled={(membersPage + 1) * 20 >= members.length} onClick={() => setMembersPage(value => value + 1)}>Next members</button></div>}
          {canInvitePrivateThread(roomId) && <form className='dialog-form' onSubmit={event => { event.preventDefault(); void run(async () => { await invitePrivateThreadMember(roomId, invite); setInvite(''); }, 'Invitation sent.'); }}><fieldset disabled={busy}><label>Find members to invite<input value={memberQuery} onChange={event => setMemberQuery(event.target.value)}/></label><label>Invite source member<select value={invite} onChange={event => setInvite(event.target.value)}><option value=''>Choose a current source member</option>{candidates.slice(0, 100).map(member => <option key={member.userId} value={member.userId}>{member.name} ({member.userId})</option>)}</select></label>{candidates.length > 100 && <p>Refine the member search to see more results.</p>}<button className='secondary-button' disabled={!invite}>Send private invitation</button></fieldset></form>}
          {canEditPrivateThread(roomId) && <form className='dialog-form' onSubmit={event => { event.preventDefault(); void run(async () => { await savePrivateThreadSettings(roomId, settings); setSettings(await loadPrivateThreadSettings(roomId)); }, 'Discussion settings saved.'); }}><fieldset disabled={busy}><label>Discussion title<input required maxLength={120} value={settings.title} onChange={event => setSettings(value => ({ ...value, title: event.target.value }))}/></label><label>Auto archive after inactivity<select value={settings.autoArchiveSeconds} onChange={event => setSettings(value => ({ ...value, autoArchiveSeconds: Number(event.target.value) }))}>{privateArchiveIntervals.map(seconds => <option key={seconds} value={seconds}>{intervalName(seconds)}</option>)}</select></label><label className='check-label'><input type='checkbox' checked={settings.archived} onChange={event => setSettings(value => ({ ...value, archived: event.target.checked }))}/>Archive discussion</label><button className='primary-button'>Save discussion settings</button><button type='button' className='secondary-button' onClick={() => void run(async () => { setSettings(await loadPrivateThreadSettings(roomId)); }, 'Current settings loaded.')}>Reload discussion settings</button>{archived && <button type='button' className='secondary-button' onClick={() => void run(async () => { await savePrivateThreadSettings(roomId, { ...settings, archived: false }, true); setSettings(await loadPrivateThreadSettings(roomId)); }, 'Discussion reopened.')}>Reopen discussion</button>}</fieldset></form>}
          <button className='secondary-button' disabled={busy} onClick={() => { setPending({ kind: 'leave', target: roomId }); setConfirmation(''); }}>Leave private discussion</button>
        </details>
        {archived && <p role='status'>This discussion is archived. An authorized member can reopen it in discussion settings.</p>}
        <div className='private-thread-messages' ref={scroll} aria-label='Private messages'>{hasMore && <button className='secondary-button' disabled={busy} onClick={() => void run(() => load(true))}>Load earlier private messages</button>}{renderMessage ? <MessageList items={messages} focusId={loadedFocus} scroll={scroll} render={message => renderMessage(message)}/> : messages.map(message => <article key={message.id}><button className='link-button' onClick={() => onMember?.(message.author_id, roomId)}>{message.author_name}</button><time dateTime={new Date(message.created_at).toISOString()}>{new Date(message.created_at).toLocaleString()}</time><p>{message.body}</p>{message.attachments?.length > 0 && <p>{message.attachments.length} encrypted attachment(s)</p>}</article>)}</div>
        {renderComposer ? renderComposer(() => load(), busy || !canPostPrivateThread(roomId)) : <form className='dialog-form' onSubmit={event => { event.preventDefault(); const draft = body; void run(async () => { await sendPrivateThreadMessage(roomId, draft, crypto.randomUUID()); setBody(value => value === draft ? '' : value); await load(); }); }}><label>Private message<textarea required maxLength={16000} value={body} disabled={busy || !canPostPrivateThread(roomId)} onChange={event => setBody(event.target.value)}/></label><button className='primary-button' disabled={busy || !canPostPrivateThread(roomId) || !body.trim()}>Send private message</button></form>}
      </>}
    </>}
    {pending && <form className='dialog-form private-membership-confirm' onSubmit={event => { event.preventDefault(); if (confirmation !== pending.target) return; const action = pending; void run(async () => { if (action.kind === 'remove') await moderatePrivateThreadMember(roomId, action.target, 'kick'); else { await getMatrixClient()?.leave(roomId); onClose(); } setPending(null); }, action.kind === 'remove' ? 'Member removed from this discussion.' : 'You left this discussion.'); }}><h3>{pending.kind === 'remove' ? 'Remove member from this discussion?' : 'Leave this private discussion?'}</h3><p>{pending.kind === 'remove' ? 'This stops future access after removal. Messages and encryption keys already received cannot be recalled.' : 'You will need another invitation to return. Messages and keys already received remain on your devices.'}</p><label>Type {pending.target} to confirm<input required autoComplete='off' value={confirmation} onChange={event => setConfirmation(event.target.value)}/></label><button className='primary-button' disabled={busy || confirmation !== pending.target}>Confirm {pending.kind === 'remove' ? 'removal' : 'leaving'}</button><button type='button' disabled={busy} onClick={() => setPending(null)}>Cancel</button></form>}
    {status && <p role='status'>{status}</p>}{error && <p role='alert' className='connect-error'>{error}</p>}
  </aside>;
}
