import { useEffect, useState } from 'react';
import { requestApi } from '@/lib/api';
import { Field } from './auth-gateway';
import { toast } from 'sonner';

export function ReportReview() {
  const [status, setStatus] = useState('open'), [before, setBefore] = useState<number | null>(null), [data, setData] = useState<any>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [selected, setSelected] = useState<any>(null);
  async function load() { setError(''); setBusy(true); try { setData(await requestApi('/admin/reports?status=' + status + (before ? '&before=' + before : ''))); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, [status, before]);
  return <div className="product-section"><p>Review submitted reasons and evidence. Encrypted messages remain readable only to their participants.</p><Field label="Report status"><select value={status} onChange={e => { setStatus(e.target.value); setBefore(null); }}>{['open', 'reviewing', 'resolved', 'dismissed', 'all'].map(s => <option key={s}>{s}</option>)}</select></Field>{error && <p className="connect-error" role="alert">{error}</p>}{busy && <p role="status">Loading reports…</p>}{data?.reports?.map((r: any) => <article className="product-section" key={r.id}><button className="secondary-button" onClick={() => setSelected({ ...r })}>#{r.id} · {r.kind} · {r.status}</button><p>{r.reason}</p><small>Reported by {r.reporter} · {new Date(r.createdAt).toLocaleString()}</small></article>)}{data && !data.reports?.length && <p>No reports match this status.</p>}{data?.next && <button className="secondary-button" disabled={busy} onClick={() => setBefore(data.next)}>Older reports</button>}{before && <button className="secondary-button" onClick={() => setBefore(null)}>Newest reports</button>}{selected && <form className="dialog-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await requestApi('/admin/reports/' + selected.id, { status: selected.status, note: selected.note }, 'PUT'); setSelected(null); toast.success('Report updated'); await load(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}><h3>Review #{selected.id}</h3><p>{selected.reason}</p>{selected.evidence && <blockquote>{selected.evidence}</blockquote>}<p>Room: {selected.roomId || '—'}<br/>Event: {selected.eventId || '—'}<br/>User: {selected.targetId || '—'}</p><Field label="Status"><select value={selected.status} onChange={e => setSelected({ ...selected, status: e.target.value })}>{['open', 'reviewing', 'resolved', 'dismissed'].map(s => <option key={s}>{s}</option>)}</select></Field><Field label="Private review note"><textarea maxLength={2000} value={selected.note || ''} onChange={e => setSelected({ ...selected, note: e.target.value })}/></Field><div className="product-actions"><button className="primary-button" disabled={busy}>Save review</button><button type="button" className="secondary-button" onClick={() => setSelected(null)}>Cancel</button></div></form>}</div>;
}
