import { useState } from 'react';
import { getMatrixClient } from '@/lib/matrix';
import { browserNotificationsEnabled, disableBrowserNotifications, enableBrowserNotifications, setRoomNotifications } from '@/lib/notifications';
export function RoomPermissions({roomId}:{roomId:string}){
  const c=getMatrixClient(),room=c?.getRoom(roomId),me=c?.getUserId();
  const power=room?.currentState.getStateEvents('m.room.power_levels','')?.getContent()||{};
  const [post,setPost]=useState(String(power.events?.['m.room.encrypted']??power.events_default??0)),[invite,setInvite]=useState(String(power.invite??0)),[pin,setPin]=useState(String(power.events?.['m.room.pinned_events']??power.state_default??50)),[conference,setConference]=useState(String(power.events?.['org.matrix.msc3401.call.member']??power.state_default??50));
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[desktop,setDesktop]=useState(browserNotificationsEnabled);
  if(!c||!room||!me)return null;
  async function run(fn:()=>Promise<unknown>){setBusy(true);setMessage('');try{await fn();setMessage('Saved.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  const select=(label:string,value:string,set:(v:string)=>void)=><label>{label}<select value={value} onChange={e=>set(e.target.value)}><option value="0">Members (0)</option><option value="50">Moderators (50)</option><option value="100">Administrators (100)</option>{!['0','50','100'].includes(value)&&<option value={value}>Custom ({value})</option>}</select></label>;
  return <section className="channel-admin"><h3>Notifications</h3><p className="login-help">Message previews stay off your desktop. Browser alerts work while Tavern is open in a background tab.</p><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{if(desktop)disableBrowserNotifications();else await enableBrowserNotifications();setDesktop(browserNotificationsEnabled());})}>{desktop?'Disable desktop alerts':'Enable desktop alerts'}</button><div className="inline-actions">{(['all','mentions','mute'] as const).map(mode=><button className="secondary-button" disabled={busy} key={mode} onClick={()=>void run(()=>setRoomNotifications(c,roomId,mode))}>{mode==='all'?'All messages':mode==='mentions'?'Mentions only':'Mute alerts'}</button>)}</div>
    {room.currentState.maySendStateEvent('m.room.power_levels',me)&&<><h3>Channel permissions</h3><form className="dialog-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const current=await c.getStateEvent(roomId,'m.room.power_levels' as any,'');await c.sendStateEvent(roomId,'m.room.power_levels' as any,{...current,invite:Number(invite),events:{...current.events,'m.room.message':Number(post),'m.room.encrypted':Number(post),'m.room.pinned_events':Number(pin),'org.matrix.msc3401.call.member':Number(conference)}},'');});}}>{select('Send messages and encrypted events',post,setPost)}{select('Invite people',invite,setInvite)}{select('Pin messages',pin,setPin)}{select('Join conferences',conference,setConference)}<p className="login-help">The homeserver enforces numeric Matrix roles. Encrypted message permissions cover all encrypted content. Server spaces do not automatically inherit these channel permissions.</p><button className="secondary-button" disabled={busy}>Save permissions</button></form></>}{message&&<p role="status">{message}</p>}
  </section>;
}
