import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { getMatrixClient, matrixApi } from '@/lib/matrix';
import { serverChannelIds } from '@/lib/community';
import { canManageOnboarding, onboardingEvent, readServerOnboarding, recommendedChannels, saveServerOnboarding } from '@/lib/server-onboarding';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ServerWelcome } from './community-settings';
import { ConversationNotificationDefaults } from './server-defaults';
export const openServerWelcome = (serverId: string) => window.dispatchEvent(new CustomEvent('tavern:server-welcome', { detail: serverId }));
export function ServerOnboardingSettings({ serverId }: { serverId: string }) {
  const [value, setValue] = useState(() => readServerOnboarding(serverId)), [previous, setPrevious] = useState(value), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const client = getMatrixClient(), rooms = serverChannelIds(serverId).map(id => ({ id, name: client?.getRoom(id)?.name || id }));
  if (!canManageOnboarding(serverId)) return <><ConversationNotificationDefaults roomId={serverId} server/>{error && <p className='connect-error' role='alert'>{error}</p>}</>;
  const chooseChannels = (selected: string[], update: (ids: string[]) => void) => <div className='onboarding-channel-options'>{rooms.map(room => <label className='check-label' key={room.id}><input type='checkbox' checked={selected.includes(room.id)} onChange={e => update(e.target.checked ? [...selected, room.id].slice(0, 20) : selected.filter(id => id !== room.id))}/>{room.name}</label>)}</div>;
  return <><ConversationNotificationDefaults roomId={serverId} server/><section className='product-section'><h3>Welcome experience</h3><form className='dialog-form' onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { const saved = await saveServerOnboarding(serverId, value, previous); setValue(saved); setPrevious(saved); toast.success('Welcome experience saved'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><fieldset disabled={busy}><label className='check-label'><input type='checkbox' checked={value.enabled} onChange={e => setValue({ ...value, enabled: e.target.checked })}/>Show welcome setup when members first open this server</label><label>Start here channel<select value={value.startChannel} onChange={e => setValue({ ...value, startChannel: e.target.value })}><option value=''>No preferred channel</option>{rooms.map(room => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label>{(['welcomeChannel', 'rulesChannel'] as const).map(key => <label key={key}>{key === 'welcomeChannel' ? 'Welcome channel' : 'Rules channel'}<select value={value[key]} onChange={event => setValue({ ...value, [key]: event.target.value })}><option value=''>None</option>{rooms.map(room => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label>)}<h4>Recommended channels</h4>{chooseChannels(value.recommended, recommended => setValue({ ...value, recommended }))}<h4>Interests</h4><p>Members choose interests to see relevant channel recommendations. Private channels still require an invitation.</p>{value.interests.map((interest, index) => <fieldset key={interest.id}><legend>Interest {index + 1}</legend><input required aria-label={'Interest ' + (index + 1)} maxLength={80} value={interest.label} onChange={e => setValue({ ...value, interests: value.interests.map(item => item.id === interest.id ? { ...item, label: e.target.value } : item) })}/>{chooseChannels(interest.channels, channels => setValue({ ...value, interests: value.interests.map(item => item.id === interest.id ? { ...item, channels } : item) }))}<button type='button' className='text-button' onClick={() => setValue({ ...value, interests: value.interests.filter(item => item.id !== interest.id) })}>Remove interest</button></fieldset>)}{value.interests.length < 12 && <button type='button' className='secondary-button' onClick={() => setValue({ ...value, interests: [...value.interests, { id: crypto.randomUUID(), label: '', channels: [] }] })}>Add interest</button>}<button className='primary-button'>Save welcome experience</button><button type='button' className='secondary-button' onClick={() => { const current = readServerOnboarding(serverId); setValue(current); setPrevious(current); setError(''); }}>Reload welcome settings</button></fieldset></form>{error && <p className='connect-error' role='alert'>{error}</p>}</section></>;
}
const preferencesKey = 'io.tavern.server_welcome';
export function ServerWelcomeFlow({ serverId, onSelect, forceOpen = false, autoOpen = true, onClosed }: { serverId: string; onSelect: (roomId: string) => void; forceOpen?: boolean; autoOpen?: boolean; onClosed?: () => void }) {
  const client = getMatrixClient(), config = readServerOnboarding(serverId), old = client?.getAccountData(preferencesKey as any)?.getContent()?.[serverId] as any;
  const [open, setOpen] = useState(forceOpen || autoOpen && config.enabled && !old?.completed), [selected, setSelected] = useState<string[]>(Array.isArray(old?.interests) ? old.interests.slice(0, 12) : []), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { if (forceOpen || autoOpen && config.enabled && !old?.completed) setOpen(true); }, [forceOpen, autoOpen, config.enabled, old?.completed]);
  useEffect(() => { const show = (event: Event) => { if ((event as CustomEvent).detail === serverId) setOpen(true); }; window.addEventListener('tavern:server-welcome', show); return () => window.removeEventListener('tavern:server-welcome', show); }, [serverId]);
  async function finish(roomId?: string) { if (!client || busy) return; setBusy(true); setError(''); try { if (roomId && client.getRoom(roomId)?.getMyMembership() !== 'join') await matrixApi('join', { id: roomId }); const fresh = await client.getAccountDataFromServer(preferencesKey as any) || {}; const entries = Object.fromEntries(Object.entries(fresh).slice(-499)); await client.setAccountData(preferencesKey as any, { ...entries, [serverId]: { completed: true, interests: selected, version: 1 } } as any); setOpen(false); onClosed?.(); if (roomId) onSelect(roomId); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={next => { if (!next && !busy) void finish(); }}><DialogContent className='tavern-dialog'><DialogHeader><DialogTitle>Welcome and channels</DialogTitle><DialogDescription>Get to know this server and find a place to start.</DialogDescription></DialogHeader><ServerWelcome serverId={serverId}/><div className='product-actions'>{([['Welcome channel', config.welcomeChannel], ['Read the rules', config.rulesChannel]] as const).filter(([, id]) => id && serverChannelIds(serverId).includes(id)).map(([label, id]) => <button key={label} className='secondary-button' disabled={busy} onClick={() => void finish(id)}>{label}: {client?.getRoom(id)?.name || 'Open channel'}</button>)}</div>{config.interests.length > 0 && <><h3>What are you interested in?</h3>{config.interests.map(interest => <label key={interest.id} className='check-label'><input type='checkbox' checked={selected.includes(interest.id)} onChange={e => setSelected(e.target.checked ? [...selected, interest.id] : selected.filter(id => id !== interest.id))}/>{interest.label}</label>)}</>}<div className='product-actions'>{recommendedChannels(config, selected).filter(id => serverChannelIds(serverId).includes(id)).map(id => { const room = client?.getRoom(id); return <button className='secondary-button' key={id} disabled={busy} onClick={() => void finish(id)}>{id === config.startChannel ? 'Start here: ' : ''}{room?.name || 'Open recommended channel'}{room?.getMyMembership() === 'invite' ? ' · Join invitation' : ''}</button>; })}</div><button className='primary-button' disabled={busy} onClick={() => void finish()}>Continue to server</button>{error && <p className='connect-error' role='alert'>{error}</p>}</DialogContent></Dialog>;
}
