import { useEffect, useState, type ReactNode } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { onMatrixUpdate } from '@/lib/matrix';
import { addServerEmoji, canManageServerEmoji, readServerEmoji, removeServerEmoji, tokenizeServerEmoji, type ServerEmoji } from '@/lib/server-emoji';
import { CommunityImage } from './community-settings';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
function useEmojis(serverId?: string) { const [, redraw] = useState(0); useEffect(() => onMatrixUpdate(() => redraw(v => v + 1)), []); return readServerEmoji(serverId); }
export function ServerEmojiManager({ serverId }: { serverId: string }) {
  const emojis = useEmojis(serverId), [name, setName] = useState(''), [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [remove, setRemove] = useState<ServerEmoji | null>(null);
  if (!canManageServerEmoji(serverId)) return null;
  return <section className="channel-admin"><h3>Server emoji</h3><p className="login-help">Upload up to 100 custom emoji. Use :name: in messages or pick an emoji when reacting.</p><form className="dialog-form" onSubmit={async e => { e.preventDefault(); if (!file) return; setBusy(true); setError(''); try { await addServerEmoji(serverId, name, file); setName(''); setFile(null); toast.success('Emoji added'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><label>Name<input required pattern="[a-z0-9_-]{1,32}" maxLength={32} value={name} placeholder="tavern_cheers" onChange={e => setName(e.target.value.toLowerCase())} disabled={busy} /></label><label>Image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e => setFile(e.target.files?.[0] || null)} disabled={busy} /></label><button className="primary-button" disabled={busy || !file || emojis.length >= 100}><Plus size={16} />Upload emoji</button></form>{error && <p role="alert" className="connect-error">{error}</p>}<div className="community-emoji-list">{emojis.map(emoji => <div key={emoji.name}><CommunityImage mxc={emoji.uri} name={':' + emoji.name + ':'} size={32} /><span>:{emoji.name}:</span><button type="button" aria-label={'Remove ' + emoji.name} disabled={busy} onClick={() => setRemove(emoji)}><Trash2 size={16} /></button></div>)}</div><AlertDialog open={!!remove} onOpenChange={open => { if (!open && !busy) setRemove(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove :{remove?.name}:?</AlertDialogTitle><AlertDialogDescription>This removes the emoji from the server picker. Existing messages and uploaded media may retain copies.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e => { e.preventDefault(); if (!remove) return; setBusy(true); removeServerEmoji(serverId, remove.name).then(() => { setRemove(null); toast.success('Emoji removed'); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }}>Remove emoji</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
export function ServerEmojiPicker({ serverId, onPick }: { serverId?: string; onPick: (emoji: ServerEmoji) => void }) { const emojis = useEmojis(serverId), [query, setQuery] = useState(''); if (!emojis.length) return null; return <div className="community-emoji-picker"><input aria-label="Search server emoji" type="search" placeholder="Search server emoji" value={query} onChange={e => setQuery(e.target.value)} /><div>{emojis.filter(e => e.name.includes(query.toLowerCase())).map(emoji => <button type="button" key={emoji.name} aria-label={':' + emoji.name + ':'} title={':' + emoji.name + ':'} onClick={() => onPick(emoji)}><CommunityImage mxc={emoji.uri} name={emoji.name} size={28} /></button>)}</div></div>; }
export function ServerEmojiText({ text, serverId, renderText }: { text: string; serverId?: string; renderText?: (text: string) => ReactNode }) { const emojis = useEmojis(serverId); return <>{tokenizeServerEmoji(text, emojis).map((part, i) => <span key={i}>{'text' in part ? renderText ? renderText(part.text) : part.text : <span className="community-inline-emoji" title={':' + part.emoji.name + ':'}><CommunityImage mxc={part.emoji.uri} name={':' + part.emoji.name + ':'} size={24} /></span>}</span>)}</>; }
