import {useEffect,useRef,useState} from 'react';
import {Sticker as StickerIcon} from 'lucide-react';
import {accountArtworkOwner} from '@/lib/api';
import {getMatrixClient,matrixApi,onMatrixUpdate} from '@/lib/matrix';
import {addSticker,canManageStickers,readStickerPacks,saveStickerPack} from '@/lib/stickers';
import {type Sticker} from '@/lib/sticker-model';
import {CommunityImage} from './community-settings';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {ExperienceError} from './experience-error';
function usePacks(serverId?:string){const[,tick]=useState(0);useEffect(()=>onMatrixUpdate(()=>tick(value=>value+1)),[]);const client=getMatrixClient();return serverId?readStickerPacks(serverId):(client?.getRooms()||[]).filter(room=>room.isSpaceRoom()&&room.getMyMembership()==='join').flatMap(room=>readStickerPacks(room.roomId)).slice(0,200);}
export function StickerPackManager({serverId}:{serverId:string}){
 const packs=usePacks(serverId),[id,setId]=useState(''),[name,setName]=useState(''),[alt,setAlt]=useState(''),[newPack,setNewPack]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),[revision,setRevision]=useState(0),[rename,setRename]=useState(''),generation=useRef(0),lock=useRef(false);
 const owner=accountArtworkOwner(),client=getMatrixClient(),pack=packs.find(value=>value.id===id)||packs[0],allowed=canManageStickers(serverId);
 useEffect(()=>{generation.current++;lock.current=false;setId('');setBusy(false);setError(null);setFile(null);setName('');setAlt('');setNewPack('');setRename('');setRevision(value=>value+1);return()=>{generation.current++;};},[client,owner,serverId]);
 async function run(task:()=>Promise<unknown>){if(lock.current)return;lock.current=true;const revision=generation.current,current=()=>revision===generation.current&&owner===accountArtworkOwner()&&client===getMatrixClient();setBusy(true);setError(null);try{const result=await task();if(current()){if(typeof result==='string')setId(result);setRevision(value=>value+1);setFile(null);setName('');setAlt('');setNewPack('');setRename('');}}catch(error){if(current())setError(error);}finally{if(current()){lock.current=false;setBusy(false);}}}
 return <section className="channel-admin"><h3>Sticker packs</h3><p>Shared server artwork for expressive messages. Sticker images are community assets; they are not private encrypted uploads. Messages using them follow the conversation’s encryption.</p>
 {allowed&&<form className="dialog-form" onSubmit={event=>{event.preventDefault();void run(async()=>{const id=crypto.randomUUID();await saveStickerPack(serverId,{id,name:newPack.trim(),stickers:[]},null);return id;});}}><label>New pack name<input required maxLength={60} value={newPack} onChange={event=>setNewPack(event.target.value)}/></label><button className="secondary-button" disabled={busy||packs.length>=20}>Create sticker pack</button></form>}
 {packs.length?<><label>Pack<select value={pack?.id||''} onChange={event=>setId(event.target.value)}>{packs.map(value=><option key={value.id} value={value.id}>{value.name} ({value.stickers.length})</option>)}</select></label><div className="sticker-grid">{pack.stickers.map(sticker=><article key={sticker.id}><CommunityImage mxc={sticker.url} name={sticker.alt} size={96}/><strong>{sticker.name}</strong>{allowed&&<button className="text-button" disabled={busy} onClick={()=>void run(()=>saveStickerPack(serverId,{...pack,stickers:pack.stickers.filter(value=>value.id!==sticker.id)},pack))}>Remove {sticker.name}</button>}</article>)}</div>
 {allowed&&<form className='dialog-form' onSubmit={event=>{event.preventDefault();void run(()=>saveStickerPack(serverId,{...pack,name:rename.trim()},pack));}}><label>Rename pack<input maxLength={60} required value={rename} placeholder={pack.name} onChange={event=>setRename(event.target.value)}/></label><button className='secondary-button' disabled={busy||!rename.trim()}>Save pack name</button></form>}
 {allowed&&<form className="dialog-form" onSubmit={event=>{event.preventDefault();if(file)void run(()=>addSticker(serverId,pack,file,name,alt));}}><label>Sticker name<input required maxLength={60} value={name} onChange={event=>setName(event.target.value)}/></label><label>Image description<input required maxLength={160} value={alt} onChange={event=>setAlt(event.target.value)} placeholder="A smiling cat waving hello"/></label><label>Artwork<input key={revision} type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif" required onChange={event=>setFile(event.target.files?.[0]||null)}/></label><p className="login-help">Images up to 10 MiB become optimized static square stickers. Animated uploads use a single frame.</p><button className="primary-button" disabled={busy||!file||pack.stickers.length>=50}>{busy?'Saving…':'Add sticker'}</button><button type="button" className="text-button" disabled={busy||!!pack.stickers.length} onClick={()=>void run(()=>saveStickerPack(serverId,pack,pack,true))}>Remove empty pack</button></form>}</>:<p>No sticker packs yet. A server manager can create the first one.</p>}
 <ExperienceError error={error} draft="Your selected pack and form entries are kept if a save fails."/></section>;
}
export function StickerPicker({roomId,serverId,parent,disabled,onSent}:{roomId:string;serverId?:string;parent?:string;disabled?:boolean;onSent:()=>void}){
 const packs=usePacks(serverId),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState<Sticker|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),nonce=useRef('');
 const client=getMatrixClient(),owner=accountArtworkOwner(),lock=useRef(false),generation=useRef(0);
 useEffect(()=>{generation.current++;lock.current=false;setOpen(false);setSelected(null);setBusy(false);setError(null);setQuery('');return()=>{generation.current++;};},[client,owner,roomId,parent]);
 async function send(sticker:Sticker,retry=false){if(lock.current||disabled)return;lock.current=true;const operation=generation.current,current=()=>operation===generation.current&&client===getMatrixClient()&&owner===accountArtworkOwner();if(!retry)nonce.current=crypto.randomUUID();setSelected(sticker);setBusy(true);setError(null);try{await matrixApi('send',{conversation:roomId,parent,body:sticker.alt,sticker,nonce:nonce.current,suppressMentions:true});if(current()){setOpen(false);setSelected(null);onSent();}}catch(error){if(current())setError(error);}finally{if(current()){lock.current=false;setBusy(false);}}}
 return <><button type="button" className="icon-button" aria-label="Stickers" disabled={disabled} onClick={()=>setOpen(true)}><StickerIcon size={18}/></button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="tavern-dialog"><DialogHeader><DialogTitle>Send a sticker</DialogTitle><DialogDescription>Choosing a sticker sends it immediately. Your message draft stays in the composer.</DialogDescription></DialogHeader><label>Find a sticker<input type="search" value={query} onChange={event=>setQuery(event.target.value)}/></label>
 {!packs.length&&<p>No sticker packs are available. Add artwork from Server settings → Stickers.</p>}{packs.map(pack=><section key={pack.id}><h3>{pack.name}</h3><div className="sticker-grid">{pack.stickers.filter(sticker=>(sticker.name+' '+sticker.alt).toLowerCase().includes(query.toLowerCase())).map(sticker=><button type="button" key={sticker.id} disabled={busy||!!error} aria-label={'Send '+sticker.name} onClick={()=>void send(sticker)}><CommunityImage mxc={sticker.url} name={sticker.alt} size={96}/><span>{sticker.name}</span></button>)}</div></section>)}
 <ExperienceError error={error} context="save" draft="Your text draft was kept." retry={selected?()=>void send(selected,true):undefined}/>{!!error&&<button className="secondary-button" onClick={()=>{setError(null);setSelected(null);}}>Choose another sticker</button>}</DialogContent></Dialog></>;
}
