import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { isManagedAccount, requestApi } from '@/lib/api';
import { getMatrixClient, onMatrixUpdate } from '@/lib/matrix';
import { roomContext } from '@/lib/channel-policy';
import { canBulkRedact } from '@/lib/bulk-moderation';
import { memberRoleRank } from '@/lib/roles';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Field } from './auth-gateway';

type Warning = { id: number; roomId: string; targetId: string; actor: string; reason: string; createdAt: number; status: 'active' | 'withdrawn'; withdrawnAt?: number | null; withdrawnBy?: string | null; read?: boolean };
type WarningPage = { warnings: Warning[]; next?: number | null; unread?: number };
const timestamp = (value?: number | null) => value ? new Date(value < 1e12 ? value * 1000 : value).toLocaleString() : 'Unavailable';
function canWarnMember(roomId: string, userId: string) {
  if (!canBulkRedact(roomId) || !/^@[^\s:]+:[^\s]+$/.test(userId)) return false;
  try { const { room, me, policies } = roomContext(roomId); return userId !== me && (room.getMember(me)?.powerLevel || 0) > (room.getMember(userId)?.powerLevel || 0) && policies.every(policy => memberRoleRank(policy, me) > memberRoleRank(policy, userId)); } catch { return false; }
}
function WarningRecord({ warning, children }: { warning: Warning; children?: React.ReactNode }) { return <article className='product-section' style={{ borderBottom: '1px solid var(--border)' }}><strong>Warning #{warning.id} · {warning.status === 'active' ? 'Active' : 'Withdrawn'}{warning.read === false ? ' · Unread' : ''}</strong><p style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{warning.reason}</p><p>Member: {warning.targetId}<br/>Issued by {warning.actor} · {timestamp(warning.createdAt)}<br/>Location: {getMatrixClient()?.getRoom(warning.roomId)?.name || warning.roomId}{warning.status === 'withdrawn' && <><br/>Withdrawn by {warning.withdrawnBy || 'a moderator'} · {timestamp(warning.withdrawnAt)}</>}</p>{children}</article>; }

export function ServerWarnings({ roomId, userId }: { roomId: string; userId?: string }) {
  const [data, setData] = useState<WarningPage | null>(null), [pages, setPages] = useState<number[]>([]), [filter, setFilter] = useState(userId || ''), [applied, setApplied] = useState(userId || ''), [revision, setRevision] = useState(0);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [creating, setCreating] = useState(false), [withdraw, setWithdraw] = useState<Warning | null>(null);
  const [target, setTarget] = useState(userId || ''), [reason, setReason] = useState(''), [confirmation, setConfirmation] = useState('');
  const [, redraw] = useState(0); useEffect(() => onMatrixUpdate(() => redraw(value => value + 1)), []);
  const allowed = isManagedAccount() && canBulkRedact(roomId);
  useEffect(() => {
    if (!allowed) { setData(null); return; }
    let live = true; setBusy(true); setError(''); setData(null); const query = new URLSearchParams({ roomId }); if (applied.trim()) query.set('targetId', applied.trim()); if (pages.length) query.set('before', String(pages.at(-1)));
    void requestApi<WarningPage>('/moderation/warnings?' + query).then(value => { if (live) setData(value); }).catch(e => { if (live) setError(e.message); }).finally(() => { if (live) setBusy(false); }); return () => { live = false; };
  }, [roomId, applied, pages, revision, allowed]);
  useEffect(() => { setFilter(userId || ''); setApplied(userId || ''); setPages([]); setCreating(false); setWithdraw(null); }, [roomId, userId]);
  if (!allowed) return null;
  async function submit() {
    const selected = withdraw?.targetId || target.trim(); if (confirmation !== selected || busy) return;
    setBusy(true); setError('');
    try { if (withdraw) await requestApi('/moderation/warnings/' + withdraw.id + '/withdraw', { confirmation }); else await requestApi('/moderation/warnings', { roomId, targetId: selected, reason: reason.trim(), confirmation }); toast.success(withdraw ? 'Warning withdrawn' : 'Warning delivered to the member’s warning inbox'); setWithdraw(null); setCreating(false); setReason(''); setConfirmation(''); setPages([]); setRevision(value => value + 1); }
    catch (e: any) { setError(e.message); } finally { setBusy(false); }
  }
  return <section className='product-section'><h3>Member warnings</h3><p>Warning reasons are private to authorized moderators and the recipient. They are stored separately from public room events. Current membership, native powers, and server role hierarchy are checked for every action.</p><form className='dialog-form' onSubmit={event => { event.preventDefault(); setApplied(filter.trim()); setPages([]); setRevision(value => value + 1); }}><Field label='Filter warnings by member ID'><input readOnly={!!userId} maxLength={255} value={filter} onChange={event => setFilter(event.target.value)} placeholder='@member:example.com'/></Field><div className='product-actions'><button className='secondary-button' disabled={busy}>Filter warnings</button><button type='button' className='primary-button' disabled={busy || !!userId && !canWarnMember(roomId, userId)} onClick={() => { setCreating(true); setWithdraw(null); setTarget(userId || applied); setReason(''); setConfirmation(''); setError(''); }}>Issue warning…</button></div></form>{busy && !creating && !withdraw && <p role='status'>Loading warnings…</p>}{error && !creating && !withdraw && <p role='alert' className='connect-error'>{error}</p>}{data && <>{data.warnings.map(warning => <WarningRecord key={warning.id} warning={warning}>{warning.status === 'active' && canWarnMember(roomId, warning.targetId) && <button className='secondary-button' disabled={busy} onClick={() => { setWithdraw(warning); setCreating(false); setConfirmation(''); setError(''); }}>Withdraw warning #{warning.id}…</button>}</WarningRecord>)}{!data.warnings.length && <p>No warnings match this location and member.</p>}<div className='product-actions'><button className='secondary-button' disabled={busy || !pages.length} onClick={() => setPages(previous => previous.slice(0, -1))}>Newer warnings</button><span>Page {pages.length + 1}</span><button className='secondary-button' disabled={busy || !data.next} onClick={() => setPages(previous => [...previous, data.next!])}>Older warnings</button></div></>}
    <Dialog open={creating || !!withdraw} onOpenChange={open => { if (!open && !busy) { setCreating(false); setWithdraw(null); setError(''); } }}><DialogContent className='tavern-dialog'><DialogHeader><DialogTitle>{withdraw ? 'Withdraw warning?' : 'Issue a private warning'}</DialogTitle><DialogDescription>{withdraw ? 'The warning remains in the audit history and the recipient’s inbox with its withdrawn status.' : 'The member can read this warning in their warning inbox. Their account access does not change.'}</DialogDescription></DialogHeader><form className='dialog-form' onSubmit={event => { event.preventDefault(); void submit(); }}>{withdraw ? <WarningRecord warning={withdraw}/> : <><Field label='Member to warn'><input required maxLength={255} value={target} readOnly={!!userId} onChange={event => { setTarget(event.target.value); setConfirmation(''); }} placeholder='@member:example.com'/></Field><Field label='Private warning reason'><textarea required maxLength={1000} value={reason} onChange={event => setReason(event.target.value)}/></Field></>}<Field label={'Type ' + (withdraw?.targetId || target.trim() || 'the member ID') + ' to confirm'}><input autoComplete='off' required value={confirmation} onChange={event => setConfirmation(event.target.value)}/></Field>{error && <p role='alert' className='connect-error'>{error}</p>}<div className='product-actions'><button className='primary-button' disabled={busy || confirmation !== (withdraw?.targetId || target.trim()) || !withdraw && (!reason.trim() || !canWarnMember(roomId, target.trim()))}>{busy ? 'Saving warning…' : withdraw ? 'Withdraw warning' : 'Send warning to member'}</button><button type='button' className='secondary-button' disabled={busy} onClick={() => { setCreating(false); setWithdraw(null); setError(''); }}>Cancel</button></div></form></DialogContent></Dialog>
  </section>;
}

export function MyWarnings() {
  const [data, setData] = useState<WarningPage | null>(null), [pages, setPages] = useState<number[]>([]), [revision, setRevision] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { const refresh = () => { if (!document.hidden) setRevision(value => value + 1); }; const timer = window.setInterval(refresh, 60000); window.addEventListener('focus', refresh); return () => { clearInterval(timer); window.removeEventListener('focus', refresh); }; }, []);
  useEffect(() => {
    let live = true; setBusy(true); setError(''); const query = pages.length ? '?before=' + pages.at(-1) : '';
    void requestApi<WarningPage>('/moderation/warnings/mine' + query).then(value => { if (live) setData(value); }).catch(e => { if (live) setError(e.message); }).finally(() => { if (live) setBusy(false); }); return () => { live = false; };
  }, [pages, revision]);
  const throughId = Math.max(0, ...(data?.warnings.map(warning => warning.id) || []));
  return <section className='product-section'><div className='product-actions'><h3>Your warning inbox{typeof data?.unread === 'number' ? ' · ' + data.unread + ' unread' : ''}</h3><button className='secondary-button' disabled={busy} onClick={() => setRevision(value => value + 1)}>Refresh warning inbox</button></div><p>Moderators can send you private warnings about behavior in their communities. Only you and currently authorized moderators can read these reasons. A warning does not change account access by itself.</p>{busy && <p role='status'>Checking your warnings…</p>}{error && <p role='alert' className='connect-error'>{error}</p>}{data && <>{data.warnings.map(warning => <WarningRecord key={warning.id} warning={warning}/>)}{!data.warnings.length && <p>No warnings in your inbox.</p>}<div className='product-actions'><button className='secondary-button' disabled={busy || !pages.length} onClick={() => setPages(previous => previous.slice(0, -1))}>Newer warnings</button><span>Page {pages.length + 1}</span><button className='secondary-button' disabled={busy || !data.next} onClick={() => setPages(previous => [...previous, data.next!])}>Older warnings</button></div>{throughId > 0 && <><button className='secondary-button' disabled={busy || !data.warnings.some(warning => !warning.read)} onClick={async () => { setBusy(true); setError(''); try { await requestApi('/moderation/warnings/read', { throughId }); setRevision(value => value + 1); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}>Mark through this page as read</button><p className='login-help'>This marks the warnings shown here and all older warnings as read across your devices.</p></>}</>}</section>;
}
