export const emojiTones = ['', '🏻', '🏼', '🏽', '🏾', '🏿'] as const;
export type EmojiPreferences = { version: 1; recent: string[]; favorites: string[]; counts: Record<string, number>; tone: string };
const valid = (value: unknown): value is string => typeof value === 'string' && value.length > 0 && value.length <= 1024 && (/^mxc:\/\/[^\s/?#]+\/[^\s/?#]+$/.test(value) || value.length <= 24 && /\p{Extended_Pictographic}|\p{Regional_Indicator}/u.test(value));
export function normalizeEmojiPreferences(value: any): EmojiPreferences { const list = (values: any, limit: number) => Array.isArray(values) ? [...new Set(values.filter(valid))].slice(0, limit) as string[] : []; return { version: 1, recent: list(value?.recent, 32), favorites: list(value?.favorites, 128), counts: Object.fromEntries(value?.counts && typeof value.counts === 'object' ? Object.entries(value.counts).filter(([id, count]) => valid(id) && Number.isSafeInteger(count) && Number(count) > 0).sort((a, b) => Number(b[1]) - Number(a[1])).slice(0, 512).map(([id, count]) => [id, Math.min(100000, Number(count))]) : []), tone: emojiTones.includes(value?.tone) ? value.tone : '' }; }
export function applyEmojiTone(emoji: string, tone: string) { const base = emoji.replace(/[\u{1F3FB}-\u{1F3FF}]/gu, ''); return /^\p{Emoji_Modifier_Base}\uFE0F?$/u.test(base) && emojiTones.includes(tone as any) ? tone ? base.replace(/\uFE0F/g, '') + tone : base : emoji; }
export function recordEmojiUse(preferences: EmojiPreferences, value: string) { if (!valid(value)) return preferences; return normalizeEmojiPreferences({ ...preferences, recent: [value, ...preferences.recent.filter(id => id !== value)], counts: { ...preferences.counts, [value]: (preferences.counts[value] || 0) + 1 } }); }
export function toggleFavoriteEmoji(preferences: EmojiPreferences, value: string) { return normalizeEmojiPreferences({ ...preferences, favorites: preferences.favorites.includes(value) ? preferences.favorites.filter(id => id !== value) : [...preferences.favorites, value] }); }
const key = (user: string) => 'tavern.emoji.preferences:' + (user || 'local');
export function readEmojiPreferences(user = '') { try { const saved = localStorage.getItem(key(user)); return normalizeEmojiPreferences(saved ? JSON.parse(saved) : { recent: JSON.parse(localStorage.getItem('tavern.emoji.recent') || '[]') }); } catch { return normalizeEmojiPreferences(undefined); } }
export function saveEmojiPreferences(preferences: EmojiPreferences, user = '') { const value = normalizeEmojiPreferences(preferences); try { localStorage.setItem(key(user), JSON.stringify(value)); } catch { /* Storage can be disabled; keep the picker usable in memory. */ } return value; }
