import { getMatrixClient } from './matrix';
export const rolesEvent = 'io.tavern.roles';
export const rolePermissions = { send_messages: 'Send messages and encrypted content', add_reactions: 'Add reactions', pin_messages: 'Pin messages', manage_messages: 'Remove others’ messages', join_calls: 'Join calls and conferences', invite: 'Invite people', kick: 'Remove members', ban: 'Ban members', timeout: 'Temporarily restrict members', manage_channels: 'Manage channels', manage_roles: 'Manage lower roles', manage_server: 'Manage server details' } as const;
export type RolePermission = keyof typeof rolePermissions;
export type ServerRole = { id: string; name: string; color: string; icon: string; position: number; permissions: RolePermission[]; mentionable: boolean; separate: boolean };
export type PermissionOverride = Partial<Record<RolePermission, -1 | 0 | 1>>;
export type PermissionTargets = { roles: Record<string, PermissionOverride>; users: Record<string, PermissionOverride> };
export type RolePolicy = { version: 1; owner: string; roles: ServerRole[]; members: Record<string, string[]>; overrides: Record<string, PermissionTargets>; categoryOverrides: Record<string, PermissionTargets> };
const policyServers = new WeakMap<RolePolicy, string>();
function validTargets(kinds: any, ids: Set<string>) { if (!kinds || typeof kinds !== 'object' || Array.isArray(kinds)) return false; for (const kind of ['roles', 'users']) { const targets = kinds[kind] || {}; if (typeof targets !== 'object' || Array.isArray(targets) || Object.keys(targets).length > 1000) return false; for (const [target, permissions] of Object.entries(targets)) { if ((kind === 'roles' ? !ids.has(target) : !target.startsWith('@')) || !permissions || typeof permissions !== 'object' || Array.isArray(permissions) || Object.entries(permissions).some(([p, v]) => !Object.hasOwn(rolePermissions, p) || ['manage_roles', 'manage_server'].includes(p) || ![-1, 0, 1].includes(v))) return false; } } return true; }
export function parseRolePolicy(value: any): RolePolicy | null {
  if (!value || value.version !== 1 || typeof value.owner !== 'string' || !value.owner.startsWith('@') || !Array.isArray(value.roles) || value.roles.length > 100 || !value.roles.length || !value.members || typeof value.members !== 'object' || Array.isArray(value.members)) return null;
  const ids = new Set<string>(), positions = new Set<number>();
  for (const role of value.roles) {
    if (!role || typeof role.id !== 'string' || !/^[\w-]{1,80}$/.test(role.id) || ids.has(role.id) || typeof role.name !== 'string' || !role.name.trim() || role.name.length > 60 || !Number.isInteger(role.position) || role.position < 0 || role.position >= 1000 || positions.has(role.position) || (role.id === 'everyone') !== (role.position === 0) || !Array.isArray(role.permissions) || role.permissions.some((p: string) => !Object.hasOwn(rolePermissions, p)) || (role.color && !/^#[a-f\d]{6}$/i.test(role.color)) || typeof (role.icon || '') !== 'string' || (role.icon || '').length > 16) return null;
    ids.add(role.id); positions.add(role.position);
  }
  if (!ids.has('everyone') || Object.keys(value.members).length > 1000 || Object.entries(value.members).some(([user, roles]) => !user.startsWith('@') || !Array.isArray(roles) || roles.length > 100 || roles.some(r => !ids.has(r)))) return null;
  const overrides = value.overrides || {}; if (typeof overrides !== 'object' || Array.isArray(overrides) || Object.keys(overrides).length > 1000) return null;
  for (const [room, kinds] of Object.entries(overrides)) if (!room.startsWith('!') || !validTargets(kinds, ids)) return null;
  const categoryOverrides = value.categoryOverrides || {}; if (typeof categoryOverrides !== 'object' || Array.isArray(categoryOverrides) || Object.keys(categoryOverrides).length > 100 || Object.entries(categoryOverrides).some(([id, targets]) => !/^[\w-]{1,80}$/.test(id) || !validTargets(targets, ids))) return null;
  const normalizedTargets = (values: Record<string, any>) => Object.fromEntries(Object.entries(values).map(([id, targets]) => [id, { roles: targets.roles || {}, users: targets.users || {} }]));
  return { version: 1, owner: value.owner, roles: value.roles.map((r: ServerRole) => ({ ...r, color: r.color || '', icon: r.icon || '', mentionable: r.mentionable === true, separate: r.separate === true })), members: value.members, overrides: normalizedTargets(overrides), categoryOverrides: normalizedTargets(categoryOverrides) };
}
export function defaultRolePolicy(owner: string): RolePolicy { return { version: 1, owner, roles: [{ id: 'everyone', name: 'Member', color: '', icon: '', position: 0, permissions: ['send_messages', 'add_reactions', 'join_calls', 'invite'], mentionable: false, separate: false }], members: {}, overrides: {}, categoryOverrides: {} }; }
export function readRolePolicy(serverId: string) { const policy = parseRolePolicy(getMatrixClient()?.getRoom(serverId)?.currentState.getStateEvents(rolesEvent, '')?.getContent()); if (policy) policyServers.set(policy, serverId); return policy; }
export function memberServerRoles(policy: RolePolicy, user: string) { const ids = new Set(['everyone', ...(policy.members[user] || [])]); return policy.roles.filter(r => ids.has(r.id)).sort((a, b) => b.position - a.position); }
export function memberRoleRank(policy: RolePolicy, user: string) { return user === policy.owner ? 1001 : Math.max(0, ...memberServerRoles(policy, user).map(r => r.position)); }
export function resolveRoomCategory(layout: any, roomId: string) { const id = Array.isArray(layout?.channels) ? layout.channels.find((c: any) => c?.id === roomId)?.category : undefined; return typeof id === 'string' && Array.isArray(layout?.categories) && layout.categories.some((c: any) => c?.id === id) ? id : undefined; }
function canonicalTargets(value: PermissionTargets | undefined) { return JSON.stringify(Object.fromEntries((['roles', 'users'] as const).flatMap(kind => { const targets = Object.entries(value?.[kind] || {}).sort(([a], [b]) => a.localeCompare(b)).flatMap(([id, permissions]) => { const values = Object.entries(permissions).filter(([, value]) => value !== 0).sort(([a], [b]) => a.localeCompare(b)); return values.length ? [[id, Object.fromEntries(values)]] : []; }); return targets.length ? [[kind, Object.fromEntries(targets)]] : []; }))); }
export function mayEditCategoryLayout(policy: RolePolicy, actor: string, before: any, after: any) { if (actor === policy.owner) return true; const rooms = new Set<string>([...(Array.isArray(before?.channels) ? before.channels : []), ...(Array.isArray(after?.channels) ? after.channels : [])].map(channel => channel?.id).filter((id): id is string => typeof id === 'string')); for (const id of rooms) { const previous = resolveRoomCategory(before, id), next = resolveRoomCategory(after, id); if (canonicalTargets(previous ? policy.categoryOverrides?.[previous] : undefined) !== canonicalTargets(next ? policy.categoryOverrides?.[next] : undefined)) return false; } return true; }
function policyCategory(policy: RolePolicy, roomId?: string) { const serverId = policyServers.get(policy); if (!serverId || !roomId) return undefined; return resolveRoomCategory(getMatrixClient()?.getRoom(serverId)?.currentState.getStateEvents('io.tavern.server.layout', '')?.getContent(), roomId); }
export function effectiveRolePermissions(policy: RolePolicy, user: string, roomId?: string, categoryId = policyCategory(policy, roomId)): Set<RolePermission> {
  if (user === policy.owner) return new Set(Object.keys(rolePermissions) as RolePermission[]);
  const roles = memberServerRoles(policy, user), result = new Set(roles.flatMap(r => r.permissions));
  for (const override of [categoryId ? policy.categoryOverrides?.[categoryId] : undefined, roomId ? policy.overrides[roomId] : undefined]) for (const p of Object.keys(rolePermissions) as RolePermission[]) { if (p === 'manage_roles' || p === 'manage_server') continue; const values = roles.map(r => override?.roles?.[r.id]?.[p] || 0); if (values.includes(-1)) result.delete(p); else if (values.includes(1)) result.add(p); const own = override?.users?.[user]?.[p]; if (own === -1) result.delete(p); else if (own === 1) result.add(p); }
  return result;
}
export function canManageServerRoles(serverId: string) { const c = getMatrixClient(), r = c?.getRoom(serverId), user = c?.getUserId(), policy = readRolePolicy(serverId); if (!c || !r || !user || !r.currentState.maySendStateEvent(rolesEvent, user)) return false; return policy ? effectiveRolePermissions(policy, user).has('manage_roles') : r.currentState.getStateEvents('m.room.create', '')?.getSender() === user; }
export async function saveRolePolicy(serverId: string, policy: RolePolicy) { const c = getMatrixClient(), me = c?.getUserId(), r = c?.getRoom(serverId); if (!c || !me || !r?.isSpaceRoom() || r.getMyMembership() !== 'join' || !r.currentState.maySendStateEvent(rolesEvent, me)) throw new Error('You do not have permission to manage this server.'); let fresh: RolePolicy | null = null; try { fresh = parseRolePolicy(await c.getStateEvent(serverId, rolesEvent as any, '')); if (!fresh) throw new Error('The saved role policy is invalid.'); } catch (e) { if ((e as any).errcode !== 'M_NOT_FOUND') throw e; } const ids = new Set(policy.roles.map(role => role.id)), categoryOverrides = Object.fromEntries(Object.entries(fresh?.categoryOverrides || policy.categoryOverrides || {}).map(([id, targets]) => [id, { ...targets, roles: Object.fromEntries(Object.entries(targets.roles || {}).filter(([role]) => ids.has(role))) }])); const next = { ...policy, categoryOverrides }; if (!parseRolePolicy(next)) throw new Error('The role policy is invalid. Check role positions and assigned members.'); await c.sendStateEvent(serverId, rolesEvent as any, next, ''); return next; }
export function canManageCategoryPermissions(serverId: string) { const policy = readRolePolicy(serverId), me = getMatrixClient()?.getUserId(); return !!(policy && me && canManageServerRoles(serverId) && effectiveRolePermissions(policy, me).has('manage_channels')); }
export function mergePermissionTargets(current: PermissionTargets, proposed: PermissionTargets, previous: PermissionTargets) { const next: PermissionTargets = { roles: { ...current.roles }, users: { ...current.users } }; for (const kind of ['roles', 'users'] as const) for (const target of new Set([...Object.keys(previous[kind]), ...Object.keys(proposed[kind])])) { const before = previous[kind][target] || {}, after = proposed[kind][target] || {}, fresh = { ...current[kind][target] }; for (const name of new Set([...Object.keys(before), ...Object.keys(after)]) as Set<RolePermission>) { if (before[name] === after[name]) continue; if (fresh[name] !== before[name] && fresh[name] !== after[name]) throw new Error('These permissions changed elsewhere. Reopen the category and retry.'); if (after[name] === undefined) delete fresh[name]; else fresh[name] = after[name]; } if (Object.keys(fresh).length) next[kind][target] = fresh; else delete next[kind][target]; } return next; }
export async function saveCategoryPermissions(serverId: string, categoryId: string, value: PermissionTargets, previous?: PermissionTargets) { const c = getMatrixClient(); if (!c || !canManageCategoryPermissions(serverId)) throw new Error('You do not have permission to manage category permissions.'); const [raw, layout] = await Promise.all([c.getStateEvent(serverId, rolesEvent as any, ''), c.getStateEvent(serverId, 'io.tavern.server.layout' as any, '')]), policy = parseRolePolicy(raw); if (!policy || !Array.isArray(layout.categories) || !layout.categories.some((cat: any) => cat.id === categoryId)) throw new Error('This category or role policy changed. Reopen it and retry.'); const merged = previous ? mergePermissionTargets(policy.categoryOverrides[categoryId] || { roles: {}, users: {} }, value, previous) : value, next = { ...policy, categoryOverrides: { ...policy.categoryOverrides, [categoryId]: merged } }; if (!parseRolePolicy(next)) throw new Error('These category permission settings are invalid.'); await c.sendStateEvent(serverId, rolesEvent as any, next, ''); return next; }

export function canAssignMemberRoles(serverId: string, userId: string) { const client = getMatrixClient(), me = client?.getUserId(), room = client?.getRoom(serverId), policy = readRolePolicy(serverId); return !!(client && me && room?.isSpaceRoom() && room.getMyMembership() === 'join' && room.getMember(userId)?.membership === 'join' && userId !== me && policy && canManageServerRoles(serverId) && memberRoleRank(policy, userId) < memberRoleRank(policy, me)); }
export function mergeMemberRoles(policy: RolePolicy, actor: string, userId: string, selected: string[], previous: string[]) {
  const actorRank = memberRoleRank(policy, actor), grants = effectiveRolePermissions(policy, actor);
  if (!grants.has('manage_roles') || actor === userId || memberRoleRank(policy, userId) >= actorRank) throw new Error('You can manage roles only for members below your highest role.');
  const desired = new Set(selected.filter(id => id !== 'everyone')), before = new Set(previous.filter(id => id !== 'everyone')), current = new Set(policy.members[userId] || []);
  for (const id of new Set([...desired, ...before])) {
    if (desired.has(id) === before.has(id)) continue;
    const role = policy.roles.find(role => role.id === id);
    if (!role || role.position >= actorRank) throw new Error('A selected role changed or is above your authority. Reopen this member’s roles.');
    if (desired.has(id)) { if (role.permissions.some(permission => !grants.has(permission))) throw new Error('You cannot grant permissions you do not have.'); current.add(id); } else current.delete(id);
  }
  const next = { ...policy, members: { ...policy.members, [userId]: [...current] } };
  if (memberRoleRank(next, userId) >= actorRank || !parseRolePolicy(next)) throw new Error('These role assignments are invalid or exceed your authority.');
  return next;
}
let memberRoleWrites: Promise<unknown> = Promise.resolve();
function stableRoleJson(value: any): string { if (Array.isArray(value)) return '[' + value.map(stableRoleJson).join(',') + ']'; if (value && typeof value === 'object') return '{' + Object.keys(value).sort().map(key => JSON.stringify(key) + ':' + stableRoleJson(value[key])).join(',') + '}'; return JSON.stringify(value); }
export function saveMemberRoles(serverId: string, userId: string, selected: string[], previous: string[]) {
  const client = getMatrixClient(); if (!client || !canAssignMemberRoles(serverId, userId)) return Promise.reject(new Error('You cannot manage this member’s roles.'));
  const task = memberRoleWrites.catch(() => {}).then(async () => {
    const observed = client.getRoom(serverId)?.currentState.getStateEvents(rolesEvent, ''), revision = observed?.getId(), snapshot = observed ? parseRolePolicy(structuredClone(observed.getContent())) : null;
    const [raw, member] = await Promise.all([client.getStateEvent(serverId, rolesEvent as any, ''), client.getStateEvent(serverId, 'm.room.member' as any, userId)]), policy = parseRolePolicy(raw), me = client.getUserId();
    if (client !== getMatrixClient() || !me || !policy || member.membership !== 'join' || !canManageServerRoles(serverId)) throw new Error('Your account, membership, or role policy changed. Reopen the member’s roles.');
    if (!revision || !snapshot || stableRoleJson(snapshot) !== stableRoleJson(policy)) throw new Error('Server roles changed while syncing. Wait for the latest state, reload assignments, and retry.');
    const next = mergeMemberRoles(policy, me, userId, selected, previous); await client.sendStateEvent(serverId, rolesEvent as any, { ...next, 'io.tavern.previous_event': revision }, ''); return next;
  }); memberRoleWrites = task; return task;
}
