import { getMatrixClient } from './matrix';
export type ServerFolder = { id: string; name: string; color: string; serverIds: string[] };
export type ServerNavigationState = { version: 1; folders: ServerFolder[]; order: string[]; collapsed: string[] };
const namespace = 'io.tavern.server_folders';
export function normalizeServerNavigation(value: unknown): ServerNavigationState { const p = (value && typeof value === 'object' ? value : {}) as any, ids = new Set<string>(), servers = new Set<string>(), folders: ServerFolder[] = []; for (const raw of Array.isArray(p.folders) ? p.folders.slice(0, 32) : []) { if (!raw || typeof raw.id !== 'string' || !/^[a-z0-9_-]{1,80}$/i.test(raw.id) || ids.has(raw.id) || typeof raw.name !== 'string' || !raw.name.trim()) continue; ids.add(raw.id); const serverIds: string[] = []; for (const id of Array.isArray(raw.serverIds) ? raw.serverIds.slice(0, 1000) : []) { if (typeof id !== 'string' || !id.startsWith('!') || id.length > 255 || servers.has(id)) continue; servers.add(id); serverIds.push(id); } folders.push({ id: raw.id, name: raw.name.trim().slice(0, 60), color: /^#[a-f\d]{6}$/i.test(raw.color) ? raw.color : '', serverIds }); } return { version: 1, folders, order: [...new Set<string>((Array.isArray(p.order) ? p.order : []).filter((id: unknown) => typeof id === 'string' && id.startsWith('!') && id.length <= 255))].slice(0, 1000), collapsed: [...new Set<string>((Array.isArray(p.collapsed) ? p.collapsed : []).filter((id: unknown) => typeof id === 'string' && ids.has(id)))] }; }
export function readServerNavigation() { return normalizeServerNavigation(getMatrixClient()?.getAccountData(namespace as any)?.getContent()); }
export function moveServerToFolder(state: ServerNavigationState, serverId: string, folderId: string) { if (folderId && !state.folders.some(f => f.id === folderId)) throw new Error('That folder no longer exists.'); return { ...state, folders: state.folders.map(folder => ({ ...folder, serverIds: [...folder.serverIds.filter(id => id !== serverId), ...(folder.id === folderId ? [serverId] : [])] })) }; }
let queue: Promise<unknown> = Promise.resolve();
export function updateServerNavigation(mutate: (old: ServerNavigationState) => ServerNavigationState) { const client = getMatrixClient(); if (!client) throw new Error('Sign in to organize your servers.'); const task = queue.catch(() => {}).then(async () => { const previous = normalizeServerNavigation(client.getAccountData(namespace as any)?.getContent()); const next = normalizeServerNavigation(mutate(previous)); await client.setAccountData(namespace as any, next as any); return next; }); queue = task; return task; }
