import { getMatrixClient } from './matrix';
import { cleanMxc, cropProfileImage, uploadProfileImage } from './community';
export const serverEmojiEvent = 'io.tavern.emoji';
export type ServerEmoji = { name: string; uri: string; creator: string };
export function parseServerEmoji(content: unknown): ServerEmoji[] { const emojis = (content as any)?.emoji; if (!Array.isArray(emojis)) return []; const seen = new Set<string>(); return emojis.slice(0, 100).flatMap(raw => { const name = typeof raw?.name === 'string' ? raw.name : '', uri = cleanMxc(raw?.uri); if (!/^[a-z0-9_-]{1,32}$/.test(name) || seen.has(name) || !uri) return []; seen.add(name); return [{ name, uri, creator: typeof raw?.creator === 'string' ? raw.creator.slice(0, 255) : '' }]; }); }
export function readServerEmoji(serverId?: string) { return serverId ? parseServerEmoji(getMatrixClient()?.getRoom(serverId)?.currentState.getStateEvents(serverEmojiEvent, '')?.getContent()) : []; }
export function canManageServerEmoji(serverId: string) { const c = getMatrixClient(), me = c?.getUserId(), room = c?.getRoom(serverId); return !!(me && room?.isSpaceRoom() && room.getMyMembership() === 'join' && room.currentState.maySendStateEvent(serverEmojiEvent, me)); }
let emojiQueue: Promise<unknown> = Promise.resolve();
async function mutateEmoji(serverId: string, fn: (old: ServerEmoji[]) => ServerEmoji[]) { const c = getMatrixClient(); if (!c || !canManageServerEmoji(serverId)) throw new Error('You do not have permission to manage server emoji.'); const task = emojiQueue.catch(() => {}).then(async () => { let old: ServerEmoji[] = []; try { old = parseServerEmoji(await c.getStateEvent(serverId, serverEmojiEvent as any, '')); } catch (e) { if ((e as any).errcode !== 'M_NOT_FOUND') throw e; } await c.sendStateEvent(serverId, serverEmojiEvent as any, { version: 1, emoji: fn(old) }, ''); }); emojiQueue = task; return task; }
export async function addServerEmoji(serverId: string, name: string, file: File) { name = name.trim().toLowerCase(); if (!/^[a-z0-9_-]{1,32}$/.test(name)) throw new Error('Emoji names use 1–32 lowercase letters, numbers, underscores, or hyphens.'); if (!canManageServerEmoji(serverId)) throw new Error('You do not have permission to manage server emoji.'); const current = readServerEmoji(serverId); if (current.length >= 100 || current.some(e => e.name === name)) throw new Error('Use a unique name; each server supports up to 100 emoji.'); const uri = await uploadProfileImage(await cropProfileImage(file)); return mutateEmoji(serverId, old => { if (old.length >= 100 || old.some(e => e.name === name)) throw new Error('That name is already used, or the emoji collection is full.'); return [...old, { name, uri, creator: getMatrixClient()!.getUserId()! }]; }); }
export async function removeServerEmoji(serverId: string, name: string) { return mutateEmoji(serverId, old => old.filter(e => e.name !== name)); }
export function tokenizeServerEmoji(text: string, emojis: ServerEmoji[]): ({ text: string } | { emoji: ServerEmoji })[] {
  const known = new Map(emojis.map(e => [e.name, e])), parts: ({ text: string } | { emoji: ServerEmoji })[] = []; let at = 0;
  for (const match of text.matchAll(/:([a-z0-9_-]{1,32}):/g)) { const found = known.get(match[1]); if (!found) continue; if (match.index! > at) parts.push({ text: text.slice(at, match.index) }); parts.push({ emoji: found }); at = match.index! + match[0].length; }
  if (at < text.length || !parts.length) parts.push({ text: text.slice(at) }); return parts;
}
export function serverEmojiHtml(text: string, emojis: ServerEmoji[]): string | undefined { const parts = tokenizeServerEmoji(text, emojis); if (!parts.some(p => 'emoji' in p)) return undefined; const escape = (text: string) => text.replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]!)); return parts.map(p => 'text' in p ? escape(p.text).replace(/\n/g, '<br>') : `<img data-mx-emoticon src="${escape(p.emoji.uri)}" alt=":${escape(p.emoji.name)}:" title=":${escape(p.emoji.name)}:" width="24" height="24">`).join(''); }
