"""Run real provisioning, then derive an isolated SFU config for native CI only.

The original config and credentials remain intact for restart validation. The
public-IP seed satisfies production input validation but is never used by the
running CI SFU. This is not a production provisioning option.
"""
import copy
import json
import os
from pathlib import Path
import sys

import yaml

STATE_ROOT = Path('/state')
EXPECTED = {
    'GITHUB_ACTIONS': 'true', 'TAVERN_CI_SMOKE': 'true',
    'COMPOSE_PROJECT_NAME': 'tavern-ci', 'TAVERN_DOMAIN': 'chat.example.test',
    'TAVERN_PUBLIC_URL': 'https://chat.example.test', 'TAVERN_CI_TLS': '/tmp/tavern-ci-tls',
    'CALLS_ENABLED': 'true', 'SFU_AUDIO_MODERATION_ENABLED': 'true',
    'OPERATIONS_ENABLED': 'true', 'INTEGRATIONS_ENABLED': 'true',
    'TURN_DOMAIN': 'turn.example.test', 'PUBLIC_IP': '1.1.1.1', 'TAVERN_DATA_DIR': '',
}


def require_ci(root, environment):
    if (sys.platform != 'linux' or root != STATE_ROOT or root.is_symlink()
            or root.resolve() != STATE_ROOT.resolve()
            or any(environment.get(key) != value for key, value in EXPECTED.items())
            or environment.get('TAVERN_STATE_ROOT', '/state') != '/state'
            or set(environment.get('COMPOSE_PROFILES', '').split(',')) != {'operations', 'calls', 'integrations'}):
        raise RuntimeError('Call config overrides require the exact isolated GitHub Actions stack.')
    for relative in ('calls', 'calls/livekit.yaml', 'calls/livekit.ci.yaml', 'calls/livekit.ci.yaml.pending',
                     'calls/turnserver.conf', 'calls/turnserver.ci.conf', 'calls/turnserver.ci.conf.pending',
                     'synapse', 'synapse/homeserver.yaml', 'synapse/homeserver.ci.yaml', 'synapse/homeserver.ci.yaml.pending'):
        if (root / relative).is_symlink():
            raise RuntimeError('The isolated call configuration must not follow a symbolic link.')


def prepare(root, environment, provisioner):
    require_ci(root, environment)
    # This is the same production function used by the canonical init image.
    # Native feature flags and credentials are never synthesized by the probe.
    provisioner(root, environment)
    require_ci(root, environment)
    source = root / 'calls/livekit.yaml'
    if not source.is_file() or source.stat().st_size > 65536:
        raise RuntimeError('The provisioned CI SFU configuration is unavailable.')
    original = source.read_bytes()
    config = yaml.safe_load(original)
    if (not isinstance(config, dict) or not isinstance(config.get('rtc'), dict)
            or config['rtc'].get('node_ip') != EXPECTED['PUBLIC_IP']
            or config['rtc'].get('use_external_ip') is not False
            or config.get('port') != 7880 or config.get('room', {}).get('auto_create') is not False
            or not isinstance(config.get('keys'), dict) or len(config['keys']) != 1):
        raise RuntimeError('The generated CI SFU configuration does not match the expected fixture.')
    key = (root / 'calls/livekit_key').read_text().strip()
    secret = (root / 'calls/livekit_secret').read_text().strip()
    if config['keys'] != {key: secret} or len(key) < 24 or len(secret) < 32:
        raise RuntimeError('The generated CI SFU credentials do not match.')
    homeserver = yaml.safe_load((root / 'synapse/homeserver.yaml').read_bytes())
    policies = [item.get('config') for item in homeserver.get('modules', []) if item.get('module') == 'tavern_policy.TavernPolicy']
    if homeserver.get('server_name') != EXPECTED['TAVERN_DOMAIN'] or len(policies) != 1 or policies[0].get('audio_moderation_enabled') is not True:
        raise RuntimeError('Native CI audio authority was not enabled by provisioning.')
    isolated = copy.deepcopy(config)
    isolated['bind_addresses'] = ['0.0.0.0']  # API access only on internal Docker networks.
    # The Linux browser reaches the owned internal bridge directly. Docker does
    # not publish ports for internal-only services; never enable external media.
    isolated['rtc'].update(node_ip='172.30.239.2', use_external_ip=False, tcp_port=0,
                           udp_port=7882, stun_servers=[], turn_servers=[],
                           enable_loopback_candidate=False, ips={'includes': ['172.30.239.2/32']})
    # NewConfig loads this explicit node_ip before RTC.Validate; the Go-only
    # NodeIPAutoGenerated flag remains false and no default STUN list is added.
    target = root / 'calls/livekit.ci.yaml'
    pending = target.with_suffix('.yaml.pending')
    pending.write_text(json.dumps(isolated, indent=2) + '\n', encoding='utf-8')
    original_stat = source.stat()
    os.chmod(pending, original_stat.st_mode & 0o777)
    if hasattr(os, 'chown'):
        os.chown(pending, original_stat.st_uid, original_stat.st_gid)
    pending.replace(target)
    if source.read_bytes() != original:
        raise RuntimeError('The original generated configuration changed during CI derivation.')
    # Native direct calls use real short-lived credentials from this Synapse.
    # Separate runtime files keep the original provisioned configuration intact.
    synapse_source, turn_source = root / 'synapse/homeserver.yaml', root / 'calls/turnserver.conf'
    synapse_bytes, turn_bytes = synapse_source.read_bytes(), turn_source.read_bytes()
    turn_lines = turn_bytes.decode('utf-8').splitlines()
    if (turn_lines.count('external-ip=' + EXPECTED['PUBLIC_IP']) != 1
            or sum(line.startswith('external-ip=') for line in turn_lines) != 1
            or 'static-auth-secret=' + homeserver.get('turn_shared_secret', '') not in turn_lines
            or homeserver.get('turn_uris') != ['turn:turn.example.test:3478?transport=udp', 'turn:turn.example.test:3478?transport=tcp']):
        raise RuntimeError('The generated native TURN configuration does not match the CI fixture.')
    native = copy.deepcopy(homeserver)
    native['turn_uris'] = ['turn:172.30.239.3:3478?transport=udp', 'turn:172.30.239.3:3478?transport=tcp']
    # The bounded policy matrix repeatedly invites the same disposable account.
    # Retain the pinned refill rate and all other limits; this CI-only burst is
    # not written to the original generated homeserver configuration.
    native.setdefault('rc_invites', {}).setdefault('per_user', {}).update(per_second=0.003, burst_count=50)
    for original_path, target, payload in (
        (synapse_source, root / 'synapse/homeserver.ci.yaml', json.dumps(native, indent=2) + '\n'),
        (turn_source, root / 'calls/turnserver.ci.conf', '\n'.join('external-ip=172.30.239.3' if line.startswith('external-ip=') else line for line in turn_lines) + '\n'),
    ):
        pending = target.with_suffix(target.suffix + '.pending')
        pending.write_text(payload, encoding='utf-8')
        original_stat = original_path.stat()
        os.chmod(pending, original_stat.st_mode & 0o777)
        if hasattr(os, 'chown'):
            os.chown(pending, original_stat.st_uid, original_stat.st_gid)
        pending.replace(target)
    if synapse_source.read_bytes() != synapse_bytes or turn_source.read_bytes() != turn_bytes:
        raise RuntimeError('The original native TURN configuration changed during CI derivation.')


def main():
    root = Path('/state')
    require_ci(root, os.environ)
    sys.path.insert(0, '/app')
    from provision import provision
    prepare(root, os.environ, provision)
    print('Prepared isolated bridge SFU config; original credentials and configuration preserved.')


if __name__ == '__main__':
    try:
        main()
    except (RuntimeError, OSError, ValueError, yaml.YAMLError):
        # Never print config documents, credentials, or raw upstream exceptions.
        print('Isolated call configuration failed validation.', file=sys.stderr)
        sys.exit(64)
