#!/usr/bin/env python3
"""Keep historical deployment filenames consistent with the canonical stack."""
import argparse
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]


def variants():
    canonical = (ROOT / 'compose.yaml').read_text(encoding='utf-8')
    git = 'https://github.com/Hans-Hans-Hans/Tavern_3.0.git#${TAVERN_GIT_REF:-V3}'
    remote = canonical.replace('${TAVERN_SOURCE_DIR:-.}', git).replace('${TAVERN_API_SOURCE_DIR:-./api}', git + ':api').replace('${TAVERN_INTEGRATIONS_SOURCE_DIR:-./integrations}', git + ':integrations')
    # A Git-backed manager must rebuild source after pulling the selected ref.
    remote = remote.replace('    build:\n', '    pull_policy: build\n    build:\n')
    remote = '# Generated by scripts/sync-compose-aliases.py. Complete stack; set COMPOSE_PROFILES for optional services.\n' + remote
    images = yaml.safe_load(canonical)
    for service in images['services'].values():
        service.pop('build', None)
    images = '# Generated image-only stack. Build images first or select published release images in the environment.\n' + yaml.safe_dump(images, sort_keys=False)
    return {'compose.github.yaml': remote, 'compose.github.full.yaml': remote,
            'compose.dockhand.yaml': images, 'compose.dockhand.full.yaml': images}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in variants().items():
        path = ROOT / name
        if args.check:
            if path.read_text(encoding='utf-8') != content:
                parser.exit(1, f'{name} differs from the canonical stack. Run this script without --check.\n')
        else:
            path.write_text(content, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
